// Project:         RoleplayRealism mod for Daggerfall Unity (http://www.dfworkshop.net)
// Copyright:       Copyright (C) 2022 Regnier
// License:         MIT License (http://www.opensource.org/licenses/mit-license.php)
// Author:          Regnier

using System.Collections;

namespace AmbientText
{
    public class AmbientText
    {
        /* Keys are in the following format, and if a key is not present no msg is displayed.
         *  Inside dungeon: <dungeonType><0-9>
         *  Outside:        <locType><climate><0-9>
         *                  <locType><dayNight><0-9>
         *                  <locType><dayNight><weather><0-9>
         * Where:
         *  locType  = None,TownCity,TownHamlet,TownVillage,HomeFarms,DungeonLabyrinth,ReligionTemple,Tavern,DungeonKeep,HomeWealthy,ReligionCult,DungeonRuin,HomePoor,Graveyard,Coven,HomeYourShips
         *  climate  = Desert, Swamp, Woods, Mountains, Ocean
         *  dayNight = Day, Night
         *  weather  = Clear, Cloudy, Rainy, Snowy
         *  dungeonType = Crypt,OrcStronghold,HumanStronghold,Prison,DesecratedTemple,Mine,NaturalCave,Coven,VampireHaunt,Laboratory,HarpyNest,RuinedCastle,SpiderNest,GiantStronghold,DragonsDen,BarbarianStronghold,VolcanicCaves,ScorpionNest,Cemetery
         */
        internal static IDictionary AmbientTexts = new Hashtable()
        {

            #region Climate texts:

//Wilderness Climates:
{ "NoneDesert0", "Your feet slide in the sand." },
{ "NoneDesert1", "There are some dried bones under the sand here." },
{ "NoneDesert2", "Wind rustles some dried plants." },
{ "NoneDesert3", "The heat rises off the sand behind you." },
{ "NoneDesert4", "A snake submerges in the sand." },
{ "NoneDesert5", "The sand finds it way into your pack." },
{ "NoneDesert6", "Thick fur is buried in sand." },
{ "NoneDesert7", "A breeze relieves some of the heat." },
{ "NoneDesert8", "The air dries your tongue and throat." },
{ "NoneDesert9", "You brush sand out of your eyes." },
//---
{ "NoneSwamp0", "Someone recently burned oil here." },
{ "NoneSwamp1", "A reptile calls in the distance." },
{ "NoneSwamp2", "Trails lead off through the mud." },
{ "NoneSwamp3", "The area is quite muddy." },
{ "NoneSwamp4", "The ground emits gas." },
{ "NoneSwamp5", "Your feet slide in the mud." },
{ "NoneSwamp6", "The breeze carries a stench." },
{ "NoneSwamp7", "You breathe the thick, damp air." },
{ "NoneSwamp8", "The bugs are unbearable." },
{ "NoneSwamp9", "You stub your toe on a rotten root." },
//---
{ "NoneWoods0", "A breeze rustles some branches." },
{ "NoneWoods1", "An animal calls in the distance." },
{ "NoneWoods2", "The air carries an arboreal scent." },
{ "NoneWoods3", "Twigs snap underneath your step." },
{ "NoneWoods4", "A Wood Elf made camp here." },
{ "NoneWoods5", "Broken bottles indicate an old campsite." },
{ "NoneWoods6", "You brush some twigs off your shoulder." },
{ "NoneWoods7", "An animal rustles in the tree near you." },
{ "NoneWoods8", "It looks like Spriggans have been here." },
{ "NoneWoods9", "You breathe the clean, fresh air." },
//---
{ "NoneMountains0", "You step in an old bear track." },
{ "NoneMountains1", "An animal can be heard in the distance." },
{ "NoneMountains2", "You cross over some old bones." },
{ "NoneMountains3", "The mountain ranges dominate the skyline." },
{ "NoneMountains4", "You tread carefully around the mountain rocks." },
{ "NoneMountains5", "The air is thin and unsatisfying." },
{ "NoneMountains6", "Sounds echo off the hills." },
{ "NoneMountains7", "Your foot lands next to a tough, spiky plant." },
{ "NoneMountains8", "You startle some birds." },
{ "NoneMountains9", "You feel watched." },
//---
{ "NoneOcean0", "Calm waves roll around you." },
{ "NoneOcean1", "The smell of the sea fills your lungs." },
{ "NoneOcean2", "You wonder what foul beasts reside in the deep." },
{ "NoneOcean3", "The waves are hypnotizing." },
{ "NoneOcean4", "Some seabirds shriek and flap their wings." },
{ "NoneOcean5", "You inhale some water." },
{ "NoneOcean6", "The ocean breeze revitalizes you." },
{ "NoneOcean7", "The sound of the ocean is like a lullaby." },
{ "NoneOcean8", "You remember that time you almost drowned." },
{ "NoneOcean9", "You check the water for Slaughterfish." },
//--- ---

//--- ---
//City Climates:
{ "TownCityDesert0", "You smell roasting scorpion." },
{ "TownCityDesert1", "The animals huff and scrape the ground." },
//{ "TownCityDesert2", "" },
{ "TownCityDesert3", "A breeze dusts you with sand." },
// { "TownCityDesert4", "" },
{ "TownCityDesert5", "A welcoming oasis in these lands." },
{ "TownCityDesert6", "The streets make walking in the sand a bit easier." },
{ "TownCityDesert7", "The cityfolk protect their belongings from the sand." },
{ "TownCityDesert8", "You smell oils being burned." },
{ "TownCityDesert9", "A lizard snatches a beetle and runs off." },
//---
{ "TownCitySwamp0", "Your toe catches on a lump of mud." },
{ "TownCitySwamp1", "Your feet weigh heavily in this damp soil." },
{ "TownCitySwamp2", "Plantgrowth adorns most houses." },
{ "TownCitySwamp3", "The smokey flames help keep the bugs away." },
{ "TownCitySwamp4", "You hear some croaking frogs in the distance." },
{ "TownCitySwamp5", "The smell of mud is replaced by fresh baked bread." },
//{ "TownCitySwamp6", "" },
//{ "TownCitySwamp7", "" },
// { "TownCitySwamp8", "" },
// { "TownCitySwamp9", "" },
//---
{ "TownCityWoods0", "The smell of roast pig fills the air." },
//{ "TownCityWoods1", "" },
{ "TownCityWoods2", "Some birds play in the tree near you." },
{ "TownCityWoods3", "The smell of wood smoke is soothing." },
{ "TownCityWoods4", "A fletcher was working here." },
{ "TownCityWoods5", "The breeze rustles some branches." },
// { "TownCityWoods6", "" },
//{ "TownCityWoods7", "" },
// { "TownCityWoods8", "" },
{ "TownCityWoods9", "The cityfolk attempt to ward off tree spirits." },
//---
{ "TownCityMountains0", "This area smells heavily of roast chicken." },
{ "TownCityMountains1", "The wind can be quite strong here." },
//{ "TownCityMountains2", "" },
{ "TownCityMountains3", "The cityfolk feel they are closer to The Gods here." },
{ "TownCityMountains4", "Some of the rocks have religious markings." },
{ "TownCityMountains5", "The city streets contain decorated mountain rocks." },
{ "TownCityMountains6", "Some believe the evergreens point to The Gods." },
// { "TownCityMountains7", "" },
// { "TownCityMountains8", "" },
// { "TownCityMountains9", "" },
//--- ---

//--- ---
//Hamlet Climates:
{ "TownHamletDesert0", "Some sand gathers on the window sills." },
{ "TownHamletDesert1", "Villagers shelter their possessions from the sand." },
{ "TownHamletDesert2", "There must be some camels nearby." },
{ "TownHamletDesert3", "You catch the smell of a hearty stew." },
{ "TownHamletDesert4", "A child's toy is half buried in the sand." },
//{ "TownHamletDesert5", "" },
{ "TownHamletDesert6", "The streets make it easier to traverse." },
{ "TownHamletDesert7", "You wipe some sand off your face." },
// { "TownHamletDesert8", "" },
// { "TownHamletDesert9", "" },
//---
// { "TownHamletSwamp0", "" },
{ "TownHamletSwamp1", "There seem to be fewer bugs in the village." },
// { "TownHamletSwamp2", "" },
//{ "TownHamletSwamp3", "" },
{ "TownHamletSwamp4", "Your foot slides on a root." },
{ "TownHamletSwamp5", "The moss grows rapidly in this area." },
//{ "TownHamletSwamp6", "" },
{ "TownHamletSwamp7", "A breeze provides some relief." },
{ "TownHamletSwamp8", "You can smell some smoking oil." },
// { "TownHamletSwamp9", "" },
//---
//{ "TownHamletWoods0", "" },
{ "TownHamletWoods1", "A soft breeze flutters some fabric." },
{ "TownHamletWoods2", "The smell of woodfire is welcoming." },
{ "TownHamletWoods3", "The trees make this a peaceful setting." },
{ "TownHamletWoods4", "The villagers seem concerned with Spriggans in the area." },
{ "TownHamletWoods5", "Someone has whittled a figure of the Eternal Champion." },
// { "TownHamletWoods6", "" },
// { "TownHamletWoods7", "" },
// { "TownHamletWoods8", "" },
// { "TownHamletWoods9", "" },
//---
{ "TownHamletMountains0", "You smell a wonderous spice from someone's window." },
{ "TownHamletMountains1", "Some fabric flaps in the breeze." },
{ "TownHamletMountains2", "The rocks are adorned with decoration." },
{ "TownHamletMountains3", "You can feel the breeze on your skin." },
{ "TownHamletMountains4", "The air is very fresh and clean up here." },
{ "TownHamletMountains5", "Birds ride the air currents above you." },
// { "TownHamletMountains6", "" },
{ "TownHamletMountains7", "Villagers pray atop the peaks." },
// { "TownHamletMountains8", "" },
// { "TownHamletMountains9", "" },
//--- ---

//--- ---
//Village Climates:
{ "TownVillageDesert0", "The sand builds on the sides of the homes." },
{ "TownVillageDesert1", "A beetle rests in the sand nearby." },
//{ "TownVillageDesert2", "" },
{ "TownVillageDesert3", "A pipe is being smoked." },
{ "TownVillageDesert4", "The locals fear Lizardmen may find their homes." },
{ "TownVillageDesert5", "A tiny lizard scampers about." },
{ "TownVillageDesert6", "Oil smoke scents the air." },
//{ "TownVillageDesert7", "" },
// { "TownVillageDesert8", "" },
// { "TownVillageDesert9", "" },
//---
{ "TownVillageSwamp0", "A child's toy is covered in mud." },
{ "TownVillageSwamp1", "The smell of woodfire replaces the stale bog." },
{ "TownVillageSwamp2", "The breeze smells of fresh bread." },
{ "TownVillageSwamp3", "A small snake slips by your foot." },
{ "TownVillageSwamp4", "A tiny lizard scurries into the plantgrowth." },
{ "TownVillageSwamp5", "You hear a bird fly off." },
{ "TownVillageSwamp6", "Your feet slide on the muddy ground." },
// { "TownVillageSwamp7", "" },
// { "TownVillageSwamp8", "" },
// { "TownVillageSwamp9", "" },
//---
{ "TownVillageWoods0", "You smell fresh firewood." },
{ "TownVillageWoods1", "You smell the smoke of a fireplace." },
{ "TownVillageWoods2", "A sturdy walking stick rests next to a home." },
// { "TownVillageWoods3", "" },
//{ "TownVillageWoods4", "" },
{ "TownVillageWoods5", "You step over a root in your path." },
{ "TownVillageWoods6", "It's a very simple life here." },
{ "TownVillageWoods7", "A heart is carved into one of the trees." },
{ "TownVillageWoods8", "You hear the wind rustle the leaves." },
// { "TownVillageWoods9", "" },
//---
{ "TownVillageMountains0", "Rocks are shaped and used as decoration." },
{ "TownVillageMountains1", "The wind pushes you slightly." },
{ "TownVillageMountains3", "A bubbling vegetable stew scents the air." },
{ "TownVillageMountains4", "The mountains dwarf this modest place." },
{ "TownVillageMountains5", "Mountain flowers adorn most windows." },
// { "TownVillageMountains6", "" },
// { "TownVillageMountains7", "" },
{ "TownVillageMountains8", "You hear some birds nearby." },
// { "TownVillageMountains9", "" },
//--- ---

//--- ---
//Tavern Climates:
{ "TavernDesert0", "You wipe the sand from your eyes." },
{ "TavernDesert1", "This place had better keep the drink flowing." },
{ "TavernDesert2", "There's a concerning clump of sand nearby." },
{ "TavernDesert3", "A lizard has made this tavern it's home." },
{ "TavernDesert4", "You smell freshly chopped wood." },
{ "TavernDesert5", "An old mug is half buried in the sand." },
{ "TavernDesert6", "A camel munches and grunts at you." },
//{ "TavernDesert7", "" },
//{ "TavernDesert8", "" },
{ "TavernDesert9", "You can smell the ale from here." },
//---
// { "TavernSwamp0", "" },
{ "TavernSwamp1", "The streets are rather muddy." },
{ "TavernSwamp2", "Many a weary traveller has stopped here." },
{ "TavernSwamp3", "The smell of ale is all you notice." },
//{ "TavernSwamp4", "" },
// { "TavernSwamp5", "" },
//{ "TavernSwamp6", "" },
{ "TavernSwamp7", "Someone was sleeping here." },
{ "TavernSwamp8", "A mud-free tavern is a welcome sight." },
{ "TavernSwamp9", "The patrons call for fresh food." },
//---
//{ "TavernWoods0", "" },
{ "TavernWoods1", "You smell freshly chopped firewood." },
// { "TavernWoods2", "" },
{ "TavernWoods3", "The scent of the fire pursues you." },
//{ "TavernWoods4", "" },
{ "TavernWoods5", "The residents tolerate the patrons." },
// { "TavernWoods6", "" },
{ "TavernWoods7", "This seems to be a popular establishment." },
//{ "TavernWoods8", "" },
// { "TavernWoods9", "" },
//---
{ "TavernMountains0", "The rocks are covered in broken bottles." },
//{ "TavernMountains1", "" },
{ "TavernMountains2", "The residents tolerate the rowdy patrons." },
{ "TavernMountains3", "You can almost feel the drink on your lips." },
{ "TavernMountains4", "Some birds are nesting in an old wine barrell." },
{ "TavernMountains5", "The wind is scented with ale." },
{ "TavernMountains6", "You can smell roasting meat." },
//{ "TavernMountains7", "" },
// { "TavernMountains8", "" },
// { "TavernMountains9", "" },
//--- ---

//--- ---
//Farm Climates:
//{ "HomeFarmsDesert0", "" },
{ "HomeFarmsDesert1", "It must be hard work to get a prosperous yield." },
{ "HomeFarmsDesert2", "The workers have carefully tended to the crops." },
{ "HomeFarmsDesert3", "When the wind subsides you can smell the farm." },
{ "HomeFarmsDesert4", "Some religious symbols are marked around the crops." },
// { "HomeFarmsDesert5", "" },
{ "HomeFarmsDesert6", "The Gods must help this family grow crops out here." },
// { "HomeFarmsDesert7", "" },
{ "HomeFarmsDesert8", "This farm feeds the nearby towns and villages." },
// { "HomeFarmsDesert9", "" },
//---
{ "HomeFarmsSwamp0", "There's plenty of water for the soil here." },
{ "HomeFarmsSwamp1", "You swat a fly away." },
{ "HomeFarmsSwamp2", "The smell is seeping into your clothes." },
// { "HomeFarmsSwamp3", "" },
// { "HomeFarmsSwamp4", "" },
// { "HomeFarmsSwamp5", "" },
// { "HomeFarmsSwamp6", "" },
{ "HomeFarmsSwamp7", "The birds have found some seeds to peck at." },
//{ "HomeFarmsSwamp8", "" },
{ "HomeFarmsSwamp9", "This farm feeds many of the locals." },
//---
//{ "HomeFarmsWoods0", "" },
{ "HomeFarmsWoods1", "They've cleared the trees to get sun on the crops." },
{ "HomeFarmsWoods2", "This land can be difficult to manage." },
// { "HomeFarmsWoods3", "" },
// { "HomeFarmsWoods4", "" },
// { "HomeFarmsWoods5", "" },
// { "HomeFarmsWoods6", "" },
{ "HomeFarmsWoods7", "This farm is vital to feeding the locals." },
{ "HomeFarmsWoods8", "This place feels private and peaceful." },
{ "HomeFarmsWoods9", "The breeze carries the scent of the forest." },
//---
{ "HomeFarmsMountains0", "A careful hand can grow a field of crops here." },
{ "HomeFarmsMountains1", "The Gods are held dear for mountain growers." },
{ "HomeFarmsMountains2", "Mountain rocks reinforce the walls." },
{ "HomeFarmsMountains3", "The wind carries the smell away." },
{ "HomeFarmsMountains4", "The farmhands work hard to maximize their yield." },
// { "HomeFarmsMountains5", "" },
// { "HomeFarmsMountains6", "" },
// { "HomeFarmsMountains7", "" },
{ "HomeFarmsMountains8", "The yield here will feed people in the surrounding area." },
// { "HomeFarmsMountains9", "" },
//--- ---

//--- ---
//Mansion Climates:
{ "HomeWealthyDesert0", "This estate is more well off than others." },
//{ "HomeWealthyDesert1", "" },
{ "HomeWealthyDesert2", "You wonder how this is afforded." },
{ "HomeWealthyDesert3", "The animals lead a good life." },
{ "HomeWealthyDesert4", "The air is scented with flowers." },
// { "HomeWealthyDesert5", "" },
{ "HomeWealthyDesert6", "Estates like this are maintained for lords of the region." },
// { "HomeWealthyDesert7", "" },
//{ "HomeWealthyDesert8", "" },
// { "HomeWealthyDesert9", "" },
//---
{ "HomeWealthySwamp0", "You see very high quality wares in use." },
{ "HomeWealthySwamp1", "The animals are kept in good condition." },
{ "HomeWealthySwamp2", "This place is more ornate than many others." },
{ "HomeWealthySwamp3", "The workers have styled the plantgrowth on the houses." },
{ "HomeWealthySwamp4", "The smell of the bog is replaced with perfume." },
// { "HomeWealthySwamp5", "" },
{ "HomeWealthySwamp6", "The ground isn't as muddy as most other places." },
{ "HomeWealthySwamp7", "You see a princely looking figure in the window." },
// { "HomeWealthySwamp8", "" },
// { "HomeWealthySwamp9", "" },
//---
{ "HomeWealthyWoods0", "These houses are sturdy and secure." },
{ "HomeWealthyWoods1", "Many caravans come through here with goods." },
{ "HomeWealthyWoods2", "There are some intricate carvings on the houses." },
// { "HomeWealthyWoods3", "" },
// { "HomeWealthyWoods4", "" },
// { "HomeWealthyWoods5", "" },
{ "HomeWealthyWoods6", "The animals have shiny, healthy coats." },
// { "HomeWealthyWoods7", "" },
{ "HomeWealthyWoods8", "You smell an incredibly rare spice." },
{ "HomeWealthyWoods9", "This is fit for a king." },
//---
{ "HomeWealthyMountains0", "The cost of these building materials is astounding." },
{ "HomeWealthyMountains1", "Rare scents fill your nose." },
{ "HomeWealthyMountains2", "Flowers decorate these buildings." },
{ "HomeWealthyMountains3", "They've left decorations on the surrounding rocks." },
{ "HomeWealthyMountains4", "You wonder what exotic items these walls hold." },
// { "HomeWealthyMountains5", "" },
// { "HomeWealthyMountains6", "" },
{ "HomeWealthyMountains7", "Some of the rocks have carvings inlet with gems." },
{ "HomeWealthyMountains8", "The animals' water is clear and plentiful." },
// { "HomeWealthyMountains9", "" },
//--- ---

//--- ---
//Hovel Climates:
{ "HomePoorDesert0", "The house has fallen into disrepair." },
{ "HomePoorDesert1", "There's a stale smell coming from the house." },
{ "HomePoorDesert2", "Some birds are pecking at old bones." },
// { "HomePoorDesert3", "" },
// { "HomePoorDesert4", "" },
// { "HomePoorDesert5", "" },
{ "HomePoorDesert6", "This place should be abandoned." },
{ "HomePoorDesert7", "The sand has covered some of the old structures." },
{ "HomePoorDesert8", "You pain to see someone live like this." },
//{ "HomePoorDesert9", "" },
//---
//{ "HomePoorSwamp0", "" },
// { "HomePoorSwamp1", "" },
{ "HomePoorSwamp2", "This house is barely standing." },
{ "HomePoorSwamp3", "The soil looks spent." },
{ "HomePoorSwamp4", "The swampland smells preferable to this place." },
// { "HomePoorSwamp5", "" },
{ "HomePoorSwamp6", "The wood here is rotting." },
// { "HomePoorSwamp7", "" },
// { "HomePoorSwamp8", "" },
{ "HomePoorSwamp9", "Some broken equipment is discarded nearby." },
//---
{ "HomePoorWoods0", "The forest is starting to swallow this place." },
//{ "HomePoorWoods1", "" },
{ "HomePoorWoods2", "The house looks broken down." },
{ "HomePoorWoods3", "A window shutter creaks in the breeze." },
{ "HomePoorWoods4", "The buildings look torn apart." },
{ "HomePoorWoods5", "There's a rotting stench." },
//{ "HomePoorWoods6", "" },
//{ "HomePoorWoods7", "" },
// { "HomePoorWoods8", "" },
// { "HomePoorWoods9", "" },
//---
{ "HomePoorMountains0", "The ground is rocky and uneven." },
//{ "HomePoorMountains1", "" },
//{ "HomePoorMountains2", "" },
// { "HomePoorMountains3", "" },
{ "HomePoorMountains4", "Only scavengers are seen near here." },
{ "HomePoorMountains5", "This place feels dreary." },
//{ "HomePoorMountains6", "" },
{ "HomePoorMountains7", "The wind relieves the smell." },
// { "HomePoorMountains8", "" },
{ "HomePoorMountains9", "Someone tried to scratch a religious symbol here." },

//--- ---
//Player Ship Climates:
{ "HomeYourShipsOcean0", "The waves sound like a lullaby." },
{ "HomeYourShipsOcean1", "The water extends for miles." },
{ "HomeYourShipsOcean2", "You check the water for beasts." },
{ "HomeYourShipsOcean3", "You can smell the water from here." },
{ "HomeYourShipsOcean4", "The ocean breeze moans \"Kelle\"." },
// { "HomeYourShipsOcean5", "" },
// { "HomeYourShipsOcean6", "" },
// { "HomeYourShipsOcean7", "" },
// { "HomeYourShipsOcean8", "" },
// { "HomeYourShipsOcean9", "" },

//--- ---
// Graveyard Climates:
{ "GraveyardDesert0", "Some bones are half buried in the sand." },
{ "GraveyardDesert1", "Scavengers indicate a recent burial." },
{ "GraveyardDesert2", "A fat lizard has burrowed near a grave." },
{ "GraveyardDesert3", "A vulture circles above you." },
{ "GraveyardDesert4", "Sand has found it's way into your gear." },
{ "GraveyardDesert5", "Shifting sands have toppled some gravestones." },
{ "GraveyardDesert6", "The crypt emits a humming sound." },
{ "GraveyardDesert7", "The smell makes your eyes water." },
{ "GraveyardDesert8", "There are some old, dried flowers buried in the sand." },
{ "GraveyardDesert9", "A religious symbol is scratched into the stone." },
//---
{ "GraveyardSwamp0", "Sounds are coming from the crypt." },
{ "GraveyardSwamp1", "The bugs are large and confident." },
{ "GraveyardSwamp2", "The vegetation has gone rancid." },
{ "GraveyardSwamp3", "It suddenly feels cold." },
{ "GraveyardSwamp4", "The mud seems to churn as you walk." },
{ "GraveyardSwamp5", "A tombstone is nearly buried." },
{ "GraveyardSwamp6", "There's a different kind of stench here." },
{ "GraveyardSwamp7", "Something was dragged through the mud." },
// { "GraveyardSwamp8", "" },
{ "GraveyardSwamp9", "An old symbol of The Gods has nearly vanished." },
//---
{ "GraveyardWoods0", "The trees around this site look diseased." },
{ "GraveyardWoods1", "The crows near here sound sick." },
{ "GraveyardWoods2", "You think you see something in the forest." },
{ "GraveyardWoods3", "The tree nearest to you shakes." },
{ "GraveyardWoods4", "Birds have abandoned their nests." },
{ "GraveyardWoods5", "The roots have pushed over a tombstone." },
{ "GraveyardWoods6", "A wooden decoration has rotted." },
{ "GraveyardWoods7", "The crypt sends out a ringing sound." },
{ "GraveyardWoods8", "This religious symbol is meant to protect the dead." },
{ "GraveyardWoods9", "You smell dirt and rotten flesh." },
//---
{ "GraveyardMountains0", "There are scratches on the rocks." },
{ "GraveyardMountains1", "Stones are used to decorate the graves." },
{ "GraveyardMountains2", "A noise echoes from the crypt." },
{ "GraveyardMountains3", "The ground here is discoloured." },
{ "GraveyardMountains4", "The mountain peaks loom over this place." },
{ "GraveyardMountains5", "Many believe those buried here are closer to The Gods." },
{ "GraveyardMountains6", "The wind eases the smell." },
{ "GraveyardMountains7", "A ritual was performed here." },
{ "GraveyardMountains8", "\"Here lies my only love\"." },
// { "GraveyardMountains9", "" },
//--- ---

//--- ---
// Coven Climates:
{ "CovenDesert0", "The beldam's presence is striking." },
{ "CovenDesert1", "Twisted patterns have formed in the sand." },
{ "CovenDesert2", "Some sort of energy melted the sand here." },
{ "CovenDesert3", "You smell strange ingredients." },
{ "CovenDesert4", "You feel pin pricks on your skin." },
// { "CovenDesert5", "" },
// { "CovenDesert6", "" },
// { "CovenDesert7", "" },
// { "CovenDesert8", "" },
// { "CovenDesert9", "" },
//---
{ "CovenSwamp0", "There are strange grooves in the mud." },
{ "CovenSwamp1", "The beldam stands facing you." },
{ "CovenSwamp2", "The smell sticks in your nose." },
{ "CovenSwamp3", "The bugs slink nearer." },
{ "CovenSwamp4", "Distant reptiles hiss and chatter." },
{ "CovenSwamp5", "There's an uncomfortable prickling sensation on your skin." },
// { "CovenSwamp6", "" },
// { "CovenSwamp7", "" },
// { "CovenSwamp8", "" },
// { "CovenSwamp9", "" },
//---
{ "CovenWoods0", "The trees seem to curl around you." },
{ "CovenWoods1", "The smell is trapped by the trees." },
{ "CovenWoods2", "You brush a spider off your leg." },
{ "CovenWoods3", "The beldam's eyes are hypnotizing." },
{ "CovenWoods4", "You sense pin pricks all over your skin." },
// { "CovenWoods5", "" },
// { "CovenWoods6", "" },
// { "CovenWoods7", "" },
// { "CovenWoods8", "" },
// { "CovenWoods9", "" },
//---
{ "CovenMountains0", "It's as if they have never moved from this spot." },
{ "CovenMountains1", "The beldam stares without blinking." },
{ "CovenMountains2", "Their chanting echoes in the hills." },
{ "CovenMountains3", "Not even the wind removes the smell." },
{ "CovenMountains4", "The rocks are decorated with bones." },
{ "CovenMountains5", "You feel a prickly sensation on your skin." },
// { "CovenMountains6", "" },
// { "CovenMountains7", "" },
// { "CovenMountains8", "" },
// { "CovenMountains9", "" },
//--- ---

//--- ---
// Temple Climates:
{ "ReligionTempleDesert0", "Pilgrims make the treck here to worship." },
{ "ReligionTempleDesert1", "The temple is accepting visitors." },
{ "ReligionTempleDesert2", "A soft tingling can be felt on your skin." },
{ "ReligionTempleDesert3", "You feel a concentration of energy." },
{ "ReligionTempleDesert4", "Many believe donations confer benefits." },
{ "ReligionTempleDesert5", "Temples are said to offer cures, even to strangers." },
{ "ReligionTempleDesert6", "You smell ceremonial fire." },
{ "ReligionTempleDesert7", "Some lizards rest near the temple." },
{ "ReligionTempleDesert8", "Caravans keep this place well stocked." },
{ "ReligionTempleDesert9", "The temple has resonated a pattern in the sand." },
//---
{ "ReligionTempleSwamp0", "Devotees place designs in the moss on the temple." },
{ "ReligionTempleSwamp1", "You can see people in the temple." },
{ "ReligionTempleSwamp2", "You feel a rush of energy." },
{ "ReligionTempleSwamp3", "Someone has scratched a mark for The Gods." },
{ "ReligionTempleSwamp4", "Donations help keep the temple clean." },
{ "ReligionTempleSwamp5", "If you are ill, the temple can help you." },
{ "ReligionTempleSwamp6", "The wildlife seems relaxed near the temple." },
{ "ReligionTempleSwamp7", "The dirt around the temple is forming a pattern." },
{ "ReligionTempleSwamp8", "Supply caravans exchange goods for blessings." },
{ "ReligionTempleSwamp9", "There's a slight tingling sensation on your skin." },
//---
{ "ReligionTempleWoods0", "There are religious markings on the trees." },
{ "ReligionTempleWoods1", "Someone has whittled a religious statue." },
{ "ReligionTempleWoods2", "Woodland animals rest near the temple." },
{ "ReligionTempleWoods3", "Your skin tingles near the temple." },
{ "ReligionTempleWoods4", "Someone lights a candle in the temple." },
{ "ReligionTempleWoods5", "The donations from locals are put to good use." },
{ "ReligionTempleWoods6", "Temples are known to cure any who seek it." },
{ "ReligionTempleWoods7", "Supply wagons help to sustain the temple." },
// { "ReligionTempleWoods8", "" },
{ "ReligionTempleWoods9", "You feel a swell of energy." },
//---
{ "ReligionTempleMountains0", "You feel a focus of energy." },
{ "ReligionTempleMountains1", "The rocks have religious markings." },
{ "ReligionTempleMountains2", "There are prayer sites in the surrounding hills." },
{ "ReligionTempleMountains3", "Someone just finished a prayer in the temple." },
{ "ReligionTempleMountains4", "Donations are accepted by members of the faith." },
//{ "ReligionTempleMountains5", "" },
{ "ReligionTempleMountains6", "You can cure an illness in the temple." },
{ "ReligionTempleMountains7", "Songbirds adorn the temple." },
{ "ReligionTempleMountains8", "You can feel your skin tingling slightly." },
// { "ReligionTempleMountains9", "" },
//--- ---

//--- ---
//Cult Climates:
{ "ReligionCultDesert0", "A discreet place to practice dark rituals." },
{ "ReligionCultDesert1", "Thick smoke pollutes the air." },
{ "ReligionCultDesert2", "You are met with intense eyes." },
{ "ReligionCultDesert3", "The building has been eroded by sand and wind." },
{ "ReligionCultDesert4", "Religious carvings are placed in the sand." },
{ "ReligionCultDesert5", "The air makes your skin itch." },
// { "ReligionCultDesert6", "" },
// { "ReligionCultDesert7", "" },
// { "ReligionCultDesert8", "" },
// { "ReligionCultDesert9", "" },
//---
{ "ReligionCultSwamp0", "Truely zealous devotees congregate here." },
{ "ReligionCultSwamp1", "The moss is creeping up the rocks." },
{ "ReligionCultSwamp2", "There's some discoloured smoke rising." },
{ "ReligionCultSwamp3", "Footprints litter the mud." },
{ "ReligionCultSwamp4", "You step on a bug you've never seen before." },
{ "ReligionCultSwamp5", "Your eyes are irritated by the stale air." },
// { "ReligionCultSwamp6", "" },
// { "ReligionCultSwamp7", "" },
// { "ReligionCultSwamp8", "" },
// { "ReligionCultSwamp9", "" },
//---
{ "ReligionCultWoods0", "A sickly smoke drifts nearby." },
{ "ReligionCultWoods1", "Strange plants grow here." },
{ "ReligionCultWoods2", "The crows sound haggard." },
{ "ReligionCultWoods3", "There are faces in the trees." },
{ "ReligionCultWoods4", "The air scratches your throat." },
{ "ReligionCultWoods5", "Pariahs are drawn to this place." },
// { "ReligionCultWoods6", "" },
// { "ReligionCultWoods7", "" },
// { "ReligionCultWoods8", "" },
// { "ReligionCultWoods9", "" },
//---
{ "ReligionCultMountains0", "Fanatics are intoxicated by ethereal power." },
{ "ReligionCultMountains1", "A scrap of parchment blows past." },
{ "ReligionCultMountains2", "Bug carcasses are scattered in a pattern." },
{ "ReligionCultMountains3", "The air has changed." },
{ "ReligionCultMountains4", "The ground rumbles slightly." },
{ "ReligionCultMountains5", "The smell sticks in your nose." },
// { "ReligionCultMountains6", "" },
// { "ReligionCultMountains7", "" },
// { "ReligionCultMountains8", "" },
// { "ReligionCultMountains9", "" },
//--- ---

//--- ---
// Dungeon Climates:
{ "DungeonLabyrinthDesert0", "A hot gust of wind burns your eyes." },
{ "DungeonLabyrinthDesert1", "The ground writhes and devours all the fallen." },
{ "DungeonLabyrinthDesert2", "The sand covers countless dead." },
{ "DungeonLabyrinthDesert3", "The sand feels like molten blades." },
{ "DungeonLabyrinthDesert4", "You hear horrible sounds underground." },
{ "DungeonLabyrinthDesert5", "The air burns your throat." },
{ "DungeonLabyrinthDesert6", "The plants are spiked and tough." },
{ "DungeonLabyrinthDesert7", "A religious item is stained in blood." },
{ "DungeonLabyrinthDesert8", "Pray the desert consumes this place." },
{ "DungeonLabyrinthDesert9", "There's a deathly howl coming from the deep." },
//---
{ "DungeonLabyrinthSwamp0", "The dirt near the dungeon is hissing." },
{ "DungeonLabyrinthSwamp1", "The wretched stench of death is powerful." },
{ "DungeonLabyrinthSwamp2", "The worms are fat and sickly." },
{ "DungeonLabyrinthSwamp3", "A crow seems to laugh at you." },
{ "DungeonLabyrinthSwamp4", "Painful faces appear in the mud." },
{ "DungeonLabyrinthSwamp5", "Bugs try to burrow in your skin." },
{ "DungeonLabyrinthSwamp6", "The mud is a deep reddish brown." },
{ "DungeonLabyrinthSwamp7", "Your mouth fills with rot as you breathe." },
// { "DungeonLabyrinthSwamp8", "" },
{ "DungeonLabyrinthSwamp9", "A body is mostly consumed in mud." },
//---
{ "DungeonLabyrinthWoods0", "There are scratches on the trees." },
{ "DungeonLabyrinthWoods1", "The branches are twisted like hooks." },
{ "DungeonLabyrinthWoods2", "The trees creak and moan." },
{ "DungeonLabyrinthWoods3", "The roots have grown wild and gluttonous." },
{ "DungeonLabyrinthWoods4", "Deadly enemies are coarsing underground." },
{ "DungeonLabyrinthWoods5", "The trees stab and slash at you." },
{ "DungeonLabyrinthWoods6", "Your nose bleeds from the harsh air." },
{ "DungeonLabyrinthWoods7", "You feel the suffering inflicted here." },
//{ "DungeonLabyrinthWoods8", "" },
{ "DungeonLabyrinthWoods9", "This area makes you nauseous." },
//---
{ "DungeonLabyrinthMountains0", "Screams echo off the mountains and hit your ear." },
{ "DungeonLabyrinthMountains1", "Blood is shed on the rocks." },
{ "DungeonLabyrinthMountains2", "The bugs leech your blood." },
{ "DungeonLabyrinthMountains3", "The plants are dying." },
{ "DungeonLabyrinthMountains4", "Those marks aren't human." },
{ "DungeonLabyrinthMountains5", "The corpses are deserted by scavengers." },
{ "DungeonLabyrinthMountains6", "There are few capable of surviving this place." },
{ "DungeonLabyrinthMountains7", "The thin air is noxious and painful." },
{ "DungeonLabyrinthMountains8", "Your footsteps stir up a stench." },
// { "DungeonLabyrinthMountains9", "" },
//--- ---

//--- ---
{ "DungeonKeepDesert0", "A vulture circles overhead." },
{ "DungeonKeepDesert1", "The sand rolls over some bones." },
//{ "DungeonKeepDesert2", "" },
{ "DungeonKeepDesert3", "A broken potion bottle has filled with sand." },
{ "DungeonKeepDesert4", "A religious marking was drawn here as a warning." },
{ "DungeonKeepDesert5", "Beetles are crawling on the archways." },
{ "DungeonKeepDesert6", "The sand grinds your feet and burns you." },
{ "DungeonKeepDesert7", "The lingering smell infects your clothing." },
{ "DungeonKeepDesert8", "Bugs swarm your eyes and ears." },
{ "DungeonKeepDesert9", "Your skin is burned and scratched by the sand." },
//---
{ "DungeonKeepSwamp0", "The bugs seem to attack you." },
{ "DungeonKeepSwamp1", "Animals scurry away carrying bones." },
{ "DungeonKeepSwamp2", "There seems to be a grave in the mud." },
{ "DungeonKeepSwamp3", "The moss around the entrance is dying." },
{ "DungeonKeepSwamp4", "You can smell the bloodshed." },
{ "DungeonKeepSwamp5", "Some hair is matted into the mud." },
{ "DungeonKeepSwamp6", "You taste the thick air as you breathe." },
{ "DungeonKeepSwamp7", "Your skin is itchy and irritated." },
{ "DungeonKeepSwamp8", "You think you hear a shriek." },
// { "DungeonKeepSwamp9", "" },
//---
{ "DungeonKeepWoods0", "The leaves drip an oily substance." },
{ "DungeonKeepWoods1", "Bugs crawl out of a skull." },
{ "DungeonKeepWoods2", "The trees are dead and dried out." },
{ "DungeonKeepWoods3", "The forest seems to whisper a warning." },
{ "DungeonKeepWoods4", "A religious relic has been desecrated." },
{ "DungeonKeepWoods5", "The woods twist around this place." },
{ "DungeonKeepWoods6", "The forest is playing tricks on you." },
{ "DungeonKeepWoods7", "A root seems to grab your foot." },
{ "DungeonKeepWoods8", "The stench in the air hurts your nose." },
{ "DungeonKeepWoods9", "Your eyes feel blurry and dry." },
//---
{ "DungeonKeepMountains0", "The plant life is sparse." },
{ "DungeonKeepMountains1", "Mountain stones are used to commemorate the dead." },
//{ "DungeonKeepMountains2", "" },
{ "DungeonKeepMountains3", "The trees direct the dead to the afterlife." },
{ "DungeonKeepMountains4", "You think you hear a crash underground." },
{ "DungeonKeepMountains5", "Some destruction magic was cast here." },
{ "DungeonKeepMountains6", "The rocks are grimy and cold to the touch." },
{ "DungeonKeepMountains7", "You can't get a full breath of air." },
{ "DungeonKeepMountains8", "Something was killed here." },
{ "DungeonKeepMountains9", "Your head aches in this area." },
//--- ---

//--- ---
{ "DungeonRuinDesert0", "An old axe head has been dulled by the sand." },
{ "DungeonRuinDesert1", "The sand is coarser than usual." },
{ "DungeonRuinDesert2", "The bugs scurry away as you approach." },
//{ "DungeonRuinDesert3", "" },
{ "DungeonRuinDesert4", "The wind blows sand into the dungeon entrance." },
{ "DungeonRuinDesert5", "You can smell dried blood." },
{ "DungeonRuinDesert6", "Sand has gotten into an old potion." },
{ "DungeonRuinDesert7", "There's an air current from the dungeon." },
{ "DungeonRuinDesert8", "Your lungs strain in this air." },
{ "DungeonRuinDesert9", "The doorway is worn and scuffed." },
//---
{ "DungeonRuinSwamp0", "Tracks lead into the dungeon." },
{ "DungeonRuinSwamp1", "The door is rotting off it's hinges." },
{ "DungeonRuinSwamp2", "A jawbone sticks out of the mud." },
{ "DungeonRuinSwamp3", "You can hear the wildlife chatter." },
{ "DungeonRuinSwamp4", "The bugs are more aggressive." },
{ "DungeonRuinSwamp5", "Some moths rest near the entrance." },
{ "DungeonRuinSwamp6", "Something tried to eat a rat." },
{ "DungeonRuinSwamp7", "The swamp air is particularly thick." },
{ "DungeonRuinSwamp8", "The dungeon door jostles in the breeze." },
{ "DungeonRuinSwamp9", "This area makes your skin itch." },
//---
{ "DungeonRuinWoods0", "The lingering air is sour." },
{ "DungeonRuinWoods1", "A crow caws and flies away." },
{ "DungeonRuinWoods2", "The trees seem to reach for you." },
{ "DungeonRuinWoods3", "The bark looks like it has ash on it." },
{ "DungeonRuinWoods4", "Someone was making some arrows here." },
{ "DungeonRuinWoods5", "You can feel an air current from the dungeon." },
{ "DungeonRuinWoods6", "Some dust irritates your eyes." },
{ "DungeonRuinWoods7", "Wind rustles the leaves like a whisper." },
// { "DungeonRuinWoods8", "" },
// { "DungeonRuinWoods9", "" },
//---
{ "DungeonRuinMountains0", "Religious symbols are freshly painted on the rocks." },
{ "DungeonRuinMountains1", "A rock mound is used as a makeshift grave." },
{ "DungeonRuinMountains2", "Only spiky grass grows easily here." },
{ "DungeonRuinMountains3", "The dungeon air whistles through the doorway." },
{ "DungeonRuinMountains4", "There are footprints around the entrance." },
{ "DungeonRuinMountains5", "The breeze smells bitter." },
{ "DungeonRuinMountains6", "The air feels very thin." },
{ "DungeonRuinMountains7", "A bat was cooked and eaten." },
{ "DungeonRuinMountains8", "Your eyes are strained and sore." },
{ "DungeonRuinMountains9", "The mountain peaks loom over you." },
//--- --- 


            #endregion

            #region Weather texts:

// Wilderness Weather:
{ "NoneDayClear0", "" },
{ "NoneDayClear1", "You squint your eyes in the sun." },
{ "NoneDayClear2", "A beautiful day to travel." },
{ "NoneDayClear3", "You can feel the sun on some exposed skin." },
{ "NoneDayClear4", "You watch your shadow creep along the landscape." },
//---
{ "NoneNightClear0", "The stars are endless." },
{ "NoneNightClear1", "The tales of the Magna Ge come to mind." },
{ "NoneNightClear2", "You feel small under the expanse of stars." },
{ "NoneNightClear3", "The moons remind you of Baar Dau." },
{ "NoneNightClear4", "Masser and Secunda dominate the sky." },
//---
{ "NoneDayCloudy0", "The cloud cover shields the suns rays." },
{ "NoneDayCloudy1", "Strong winds move the clouds." },
// { "NoneDayCloudy2", "" },
// { "NoneDayCloudy3", "" },
// { "NoneDayCloudy4", "" },
//---
{ "NoneNightCloudy0", "It is difficult to travel without some moonlight." },
{ "NoneNightCloudy1", "The dark clouds cloak some movement." },
// { "NoneNightCloudy2", "" },
// { "NoneNightCloudy3", "" },
// { "NoneNightCloudy4", "" },
//---
{ "NoneDayRainy0", "A bug scurries out from under your footstep." },
{ "NoneDayRainy1", "Tracks here suggest a recent ambush." },
{ "NoneDayRainy2", "The rains drops splash on your shoulder." },
// { "NoneDayRainy3", "" },
// { "NoneDayRainy4", "" },
//---
{ "NoneNightRainy0", "A miserable night for travel." },
{ "NoneNightRainy1", "You feel a cold stream down your back." },
{ "NoneNightRainy2", "The drops fall in a rhythm." },
// { "NoneNightRainy3", "" },
// { "NoneNightRainy4", "" },
//---
{ "NoneDaySnowy0", "There's evidence of a recent camp here." },
{ "NoneDaySnowy1", "The crystalline snow shines in your eyes." },
{ "NoneDaySnowy2", "The cold wind stings your face." },
{ "NoneDaySnowy3", "You shake some snow off your head." },
// { "NoneDaySnowy4", "" },
//---
{ "NoneNightSnowy0", "Snowfall and darkness cover your tracks." },
{ "NoneNightSnowy1", "Your fingertips tingle in the cold." },
// { "NoneNightSnowy2", "" },
// { "NoneNightSnowy3", "" },
// { "NoneNightSnowy4", "" },

//--- ---
// City Weather:
//{ "TownCityDayClear0", "" },
{ "TownCityDayClear1", "The cityfolk enjoy the sunshine." },
{ "TownCityDayClear2", "A fresh breeze brushes past you." },
// { "TownCityDayClear3", "" },
// { "TownCityDayClear4", "" },
//---
{ "TownCityNightClear0", "You spot a cat sneaking around the corner." },
{ "TownCityNightClear1", "You hear the echo of someone running away." },
//{ "TownCityNightClear2", "" },
//{ "TownCityNightClear3", "" },
// { "TownCityNightClear4", "" },
//---
//{ "TownCityDayCloudy0", "" },
//{ "TownCityDayCloudy1", "." },
//{ "TownCityDayCloudy2", "." },
// { "TownCityDayCloudy3", "" },
// { "TownCityDayCloudy4", "" },
//---
{ "TownCityNightCloudy0", "You can hear some of the city night life." },
//{ "TownCityNightCloudy1", "" },
{ "TownCityNightCloudy2", "The streetlamps and windows light your path." },
//{ "TownCityNightCloudy3", "" },
// { "TownCityNightCloudy4", "" },
//---
{ "TownCityDayRainy0", "Your cloth feels heavy in the damp air." },
{ "TownCityDayRainy1", "Cityfolk watch the rain from their windows." },
{ "TownCityDayRainy2", "Someone sighs, \"More miserable rain.\"." },
//{ "TownCityDayRainy3", "" },
//{ "TownCityDayRainy4", "" },
//---
{ "TownCityNightRainy0", "The cityfolk shelter their belongings from the rain." },
{ "TownCityNightRainy1", "It sounds like someone is dealing with a leak." },
{ "TownCityNightRainy2", "" },
// { "TownCityNightRainy3", "" },
// { "TownCityNightRainy4", "" },
//---
{ "TownCityDaySnowy0", "The falling snow is relaxing." },
//{ "TownCityDaySnowy1", "" },
{ "TownCityDaySnowy2", "The crunch of the snow is satisfying." },
// { "TownCityDaySnowy3", "" },
// { "TownCityDaySnowy4", "" },
//---
{ "TownCityNightSnowy0", "The days' footprints are covered partially by the snow." },
//{ "TownCityNightSnowy1", "" },
{ "TownCityNightSnowy2", "You hear roaring fires in the homes." },
{ "TownCityNightSnowy3", "You can hear echoes in the still air." },
{ "TownCityNightSnowy4", "The crunchy snow is loud under your feet." },

//--- ---
// Hamlet Weather:
// { "TownHamletDayClear0", "" },
{ "TownHamletDayClear1", "The villagers are enjoying the sun." },
//{ "TownHamletDayClear2", "" },
// { "TownHamletDayClear3", "" },
// { "TownHamletDayClear4", "" },
//---
// { "TownHamletNightClear0", "" },
{ "TownHamletNightClear1", "A child peers through their window at the stars." },
//{ "TownHamletNightClear2", "" },
{ "TownHamletNightClear3", "The moonlight provides some illumination." },
//{ "TownHamletNightClear4", "" },
//---
{ "TownHamletDayCloudy0", "You think you feel a droplet of rain." },
//{ "TownHamletDayCloudy1", "" },
{ "TownHamletDayCloudy2", "Someone calls out, \"Fresh brewed ale!\"" },
// { "TownHamletDayCloudy3", "" },
// { "TownHamletDayCloudy4", "" },
//---
//{ "TownHamletNightCloudy0", "" },
//{ "TownHamletNightCloudy1", "" },
// { "TownHamletNightCloudy2", "" },
// { "TownHamletNightCloudy3", "" },
// { "TownHamletNightCloudy4", "" },
//---
// { "TownHamletDayRainy0", "" },
//{ "TownHamletDayRainy1", "" },
//{ "TownHamletDayRainy2", "" },
{ "TownHamletDayRainy3", "People peer at you out of their windows." },
//{ "TownHamletDayRainy4", "" },
//---
// { "TownHamletNightRainy0", "" },
{ "TownHamletNightRainy1", "A tavern will ease the gloom." },
{ "TownHamletNightRainy2", "The rain masks your footsteps." },
//{ "TownHamletNightRainy3", "" },
// { "TownHamletNightRainy4", "" },
//---
//{ "TownHamletDaySnowy0", "" },
{ "TownHamletDaySnowy1", "The villagers bundle their clothing for warmth." },
//{ "TownHamletDaySnowy2", "" },
{ "TownHamletDaySnowy3", "Someone has formed snow into the shape of a man." },
// { "TownHamletDaySnowy4", "" },
//---
//{ "TownHamletNightSnowy0", "" },
{ "TownHamletNightSnowy1", "The crunch of your footsteps echo off the houses." },
{ "TownHamletNightSnowy2", "The snow may soon cover everything in sight." },
{ "TownHamletNightSnowy3", "A horse shakes some snow off it's head." },
// { "TownHamletNightSnowy4", "" },

//--- ---
// Village Weather:
{ "TownVillageDayClear0", "The birds sing and flutter." },
{ "TownVillageDayClear1", "The sunlight warms your shoulders." },
//{ "TownVillageDayClear2", "" },
//{ "TownVillageDayClear3", "" },
//{ "TownVillageDayClear4", "" },
//---
//{ "TownVillageNightClear0", "" },
{ "TownVillageNightClear1", "Young children gaze at the constellations from their windows." },
// { "TownVillageNightClear2", "" },
// { "TownVillageNightClear3", "" },
// { "TownVillageNightClear4", "" },
//---
{ "TownVillageDayCloudy0", "A small droplet of rain lands on your shoulder." },
//{ "TownVillageDayCloudy1", "" },
//{ "TownVillageDayCloudy2", "" },
//{ "TownVillageDayCloudy3", "" },
//{ "TownVillageDayCloudy4", "" },
//---
{ "TownVillageNightCloudy0", "You hear some soft chatter in the homes." },
//{ "TownVillageNightCloudy1", "" },
{ "TownVillageNightCloudy2", "The sparse light helps you navigate these streets." },
// { "TownVillageNightCloudy3", "" },
// { "TownVillageNightCloudy4", "" },
//---
{ "TownVillageDayRainy0", "Many of the locals are keeping out of the rain." },
//{ "TownVillageDayRainy1", "" },
// { "TownVillageDayRainy2", "" },
// { "TownVillageDayRainy3", "" },
// { "TownVillageDayRainy4", "" },
//---
{ "TownVillageNightRainy0", "The rain taps on the rooftops." },
{ "TownVillageNightRainy1", "A warm, dry bed would be welcome." },
// { "TownVillageNightRainy2", "" },
// { "TownVillageNightRainy3", "" },
// { "TownVillageNightRainy4", "" },
//---
//{ "TownVillageDaySnowy0", "" },
{ "TownVillageDaySnowy1", "The locals help each other clear the snow." },
{ "TownVillageDaySnowy2", "You're thankful to be around some civilization." },
//{ "TownVillageDaySnowy3", "" },
//{ "TownVillageDaySnowy4", "" },
//---
{ "TownVillageNightSnowy0", "The snow crunches underfoot." },
//{ "TownVillageNightSnowy1", "" },
{ "TownVillageNightSnowy2", "The snow may bury this whole town." },
// { "TownVillageNightSnowy3", "" },
// { "TownVillageNightSnowy4", "" },

//--- ---
// Dungeon Weather:
{ "DungeonLabyrinthDayClear0", "The sun can't cleanse a place so evil." },
{ "DungeonLabyrinthDayClear1", "The Gods weep at the sight of this place." },
// { "DungeonLabyrinthDayClear2", "" },
// { "DungeonLabyrinthDayClear3", "" },
// { "DungeonLabyrinthDayClear4", "" },
//---
//{ "DungeonLabyrinthNightClear0", "" },
//{ "DungeonLabyrinthNightClear1", "" },
// { "DungeonLabyrinthNightClear2", "" },
// { "DungeonLabyrinthNightClear3", "" },
// { "DungeonLabyrinthNightClear4", "" },
//---
{ "DungeonLabyrinthDayCloudy0", "Stale air bursts forth like a breath." },
//{ "DungeonLabyrinthDayCloudy1", "" },
{ "DungeonLabyrinthDayCloudy2", "The clouds billow and writhe." },
// { "DungeonLabyrinthDayCloudy3", "" },
// { "DungeonLabyrinthDayCloudy4", "" },
//---
{ "DungeonLabyrinthNightCloudy0", "Little moonlight falls on this hellish place." },
{ "DungeonLabyrinthNightCloudy1", "Cloud cover cloaks the dead." },
{ "DungeonLabyrinthNightCloudy2", "Darkness breaches the edges of your vision." },
// { "DungeonLabyrinthNightCloudy3", "" },
// { "DungeonLabyrinthNightCloudy4", "" },
//---
{ "DungeonLabyrinthDayRainy0", "The rain can't wash away the filth." },
{ "DungeonLabyrinthDayRainy1", "The puddles are dirty and greasy." },
{ "DungeonLabyrinthDayRainy2", "The rain intensifies the stench." },
// { "DungeonLabyrinthDayRainy3", "" },
// { "DungeonLabyrinthDayRainy4", "" },
//---
{ "DungeonLabyrinthNightRainy0", "The rain hides the sound of footsteps." },
{ "DungeonLabyrinthNightRainy1", "Any amount of rainfall is preferable to this Oblivion hole." },
// { "DungeonLabyrinthNightRainy2", "" },
{ "DungeonLabyrinthNightRainy3", "The smell is unlike anything you've experienced." },
// { "DungeonLabyrinthNightRainy4", "" },
//---
{ "DungeonLabyrinthDaySnowy0", "Carnage lays just beneath this peaceful snow covering." },
{ "DungeonLabyrinthDaySnowy1", "You can just make out dead figures under the snow." },
{ "DungeonLabyrinthDaySnowy2", "Twisted shapes form in the dirty snow." },
{ "DungeonLabyrinthDaySnowy3", "The glare off the snow seeks to blind you." },
{ "DungeonLabyrinthDaySnowy4", "Your fingers have gone numb." },
//---
{ "DungeonLabyrinthNightSnowy0", "The snow shatters like glass as you move." },
{ "DungeonLabyrinthNightSnowy1", "A shiver runs up your back." },
//{ "DungeonLabyrinthNightSnowy2", "" },
{ "DungeonLabyrinthNightSnowy3", "The cold, sharp air hurts to breathe." },
//{ "DungeonLabyrinthNightSnowy4", "" },

//--- ---
{ "DungeonKeepDayClear0", "The day darkens near here." },
{ "DungeonKeepDayClear1", "The suns rays fall onto this dreary place." },
// { "DungeonKeepDayClear2", "" },
// { "DungeonKeepDayClear3", "" },
// { "DungeonKeepDayClear4", "" },
//---
{ "DungeonKeepNightClear0", "The stars offer a warning of this place." },
{ "DungeonKeepNightClear1", "Eery moonlight illuminates the area." },
// { "DungeonKeepNightClear2", "" },
// { "DungeonKeepNightClear3", "" },
// { "DungeonKeepNightClear4", "" },
//---
{ "DungeonKeepDayCloudy0", "You can smell rotting flesh." },
{ "DungeonKeepDayCloudy1", "The clouds twist above the dungeon." },
// { "DungeonKeepDayCloudy2", "" },
// { "DungeonKeepDayCloudy3", "" },
// { "DungeonKeepDayCloudy4", "" },
//---
{ "DungeonKeepNightCloudy0", "The damp air is sickly." },
{ "DungeonKeepNightCloudy1", "Sounds echo and turn sinister." },
// { "DungeonKeepNightCloudy2", "" },
// { "DungeonKeepNightCloudy3", "" },
// { "DungeonKeepNightCloudy4", "" },
//---
{ "DungeonKeepDayRainy0", "It smells like the dead." },
{ "DungeonKeepDayRainy1", "The rain feels heavy and grimy." },
{ "DungeonKeepDayRainy2", "A bleak day to tread these grounds." },
// { "DungeonKeepDayRainy3", "" },
// { "DungeonKeepDayRainy4", "" },
//---
{ "DungeonKeepNightRainy0", "The rain is still preferable to this place." },
{ "DungeonKeepNightRainy1", "Steam rises off the ground near the dungeon." },
{ "DungeonKeepNightRainy2", "The rain tastes foul." },
// { "DungeonKeepNightRainy3", "" },
// { "DungeonKeepNightRainy4", "" },
//---
{ "DungeonKeepDaySnowy0", "Strange figures jut out of the ground, covered by snow." },
{ "DungeonKeepDaySnowy1", "The daylight shimmers off the snow and pierces your eyes." },
{ "DungeonKeepDaySnowy2", "Large footprints litter the snow." },
// { "DungeonKeepDaySnowy3", "" },
// { "DungeonKeepDaySnowy4", "" },
//---
{ "DungeonKeepNightSnowy0", "The entrance may get snowed in." },
{ "DungeonKeepNightSnowy1", "The cold air from the dungeon is oppressive." },
{ "DungeonKeepNightSnowy2", "A frozen body is buried in the snow." },
// { "DungeonKeepNightSnowy3", "" },
// { "DungeonKeepNightSnowy4", "" },

//--- ---
{ "DungeonRuinDayClear0", "The plantlife looks unwell here." },
{ "DungeonRuinDayClear1", "The Gods' light shines on this sad place." },
// { "DungeonRuinDayClear2", "" },
// { "DungeonRuinDayClear3", "" },
// { "DungeonRuinDayClear4", "" },
//---
//{ "DungeonRuinNightClear0", "" },
{ "DungeonRuinNightClear1", "A dark figure scampers away." },
// { "DungeonRuinNightClear2", "" },
// { "DungeonRuinNightClear3", "" },
// { "DungeonRuinNightClear4", "" },
//---
{ "DungeonRuinDayCloudy0", "The wind wrestles you as you move." },
{ "DungeonRuinDayCloudy1", "The clouds form a weird pattern." },
// { "DungeonRuinDayCloudy2", "" },
// { "DungeonRuinDayCloudy3", "" },
// { "DungeonRuinDayCloudy4", "" },
//---
{ "DungeonRuinNightCloudy0", "The air around the dungeon has a fine mist." },
{ "DungeonRuinNightCloudy1", "The clouds look discoloured." },
// { "DungeonRuinNightCloudy2", "" },
// { "DungeonRuinNightCloudy3", "" },
// { "DungeonRuinNightCloudy4", "" },
//---
{ "DungeonRuinDayRainy0", "The air is rather stale." },
//{ "DungeonRuinDayRainy1", "" },
{ "DungeonRuinDayRainy2", "The drops are heavy on your shoulder." },
// { "DungeonRuinDayRainy3", "" },
// { "DungeonRuinDayRainy4", "" },
//---
{ "DungeonRuinNightRainy0", "The air smells a little foul." },
{ "DungeonRuinNightRainy1", "The drops seem to be tapping your shoulder." },
// { "DungeonRuinNightRainy2", "" },
// { "DungeonRuinNightRainy3", "" },
// { "DungeonRuinNightRainy4", "" },
//---
{ "DungeonRuinDaySnowy0", "An adventurers horse was parked here." },
{ "DungeonRuinDaySnowy1", "The snow covers some animal tracks." },
// { "DungeonRuinDaySnowy2", "" },
// { "DungeonRuinDaySnowy3", "" },
// { "DungeonRuinDaySnowy4", "" },
//---
{ "DungeonRuinNightSnowy0", "The snow hides movement in the distance." },
{ "DungeonRuinNightSnowy1", "A spell disrupted the snow here." },
// { "DungeonRuinNightSnowy2", "" },
// { "DungeonRuinNightSnowy3", "" },
// { "DungeonRuinNightSnowy4", "" },

//--- ---
// Graveyard Weather:
{ "GraveyardDayClear0", "The plantlife looks sick." },
{ "GraveyardDayClear1", "There seem to be faces in the plantgrowth." },
// { "GraveyardDayClear2", "" },
// { "GraveyardDayClear3", "" },
// { "GraveyardDayClear4", "" },
//---
{ "GraveyardNightClear0", "You hear a distant yell." },
//{ "GraveyardNightClear1", "" },
{ "GraveyardNightClear2", "The Gods call lost spirits into the expanse." },
// { "GraveyardNightClear3", "" },
// { "GraveyardNightClear4", "" },
//---
{ "GraveyardDayCloudy0", "The locals say ghosts can be seen in the morning fog." },
{ "GraveyardDayCloudy1", "Shadows move above the clouds." },
// { "GraveyardDayCloudy2", "" },
// { "GraveyardDayCloudy3", "" },
// { "GraveyardDayCloudy4", "" },
//---
{ "GraveyardNightCloudy0", "You smell a rotten stench." },
{ "GraveyardNightCloudy1", "The clouds have picked up speed." },
// { "GraveyardNightCloudy2", "" },
// { "GraveyardNightCloudy3", "" },
// { "GraveyardNightCloudy4", "" },
//---
{ "GraveyardDayRainy0", "Worms are writhing near you." },
{ "GraveyardDayRainy1", "Years of rain has eroded the gravestones." },
// { "GraveyardDayRainy2", "" },
// { "GraveyardDayRainy3", "" },
// { "GraveyardDayRainy4", "" },
//---
{ "GraveyardNightRainy0", "Stale water drips in your eyes." },
{ "GraveyardNightRainy1", "Some of the raindrops sizzle on the hedgerows." },
{ "GraveyardNightRainy2", "There is a small gravestone with a child's toy on it." },
// { "GraveyardNightRainy3", "" },
// { "GraveyardNightRainy4", "" },
//---
{ "GraveyardDaySnowy0", "A shiver runs up your back." },
{ "GraveyardDaySnowy1", "There is some melting snow over a grave." },
// { "GraveyardDaySnowy2", "" },
// { "GraveyardDaySnowy3", "" },
// { "GraveyardDaySnowy4", "" },
//---
{ "GraveyardNightSnowy0", "The wind is colder than usual." },
{ "GraveyardNightSnowy1", "There are strange footsteps in the snow." },
// { "GraveyardNightSnowy2", "" },
// { "GraveyardNightSnowy3", "" },
// { "GraveyardNightSnowy4", "" },
//--- ---

            #endregion

            #region Day / Night texts:


// Wilderness Day/Night:
//{ "NoneDay0", "" },
//{ "NoneDay1", "" },
{ "NoneDay2", "Magnus' light guides the fate of Nirn." },
// { "NoneDay3", "" },
// { "NoneDay4", "" },
// { "NoneDay5", "" },
// { "NoneDay6", "" },
// { "NoneDay7", "" },
// { "NoneDay8", "" },
// { "NoneDay9", "" },
//---
{ "NoneNight0", "The night can be dangerous for some." },
{ "NoneNight1", "You think you hear movement behind you." },
{ "NoneNight2", "Shadows shift in the distance." },
{ "NoneNight3", "Beings with ill intent lurk in the night." },
{ "NoneNight4", "Two animals are fighting in the distance." },
{ "NoneNight5", "The Mnemoli weave Nirn's fateful melody." },
// { "NoneNight6", "" },
// { "NoneNight7", "" },
// { "NoneNight8", "" },
// { "NoneNight9", "" },
//--- ---
// City Day/Night:
{ "TownCityDay0", "You hear some neighbours arguing." },
{ "TownCityDay1", "You smell some freshly chopped wood." },
{ "TownCityDay2", "You catch the scent of a warm meal." },
//{ "TownCityDay3", "" },
{ "TownCityDay4", "Someone is playing a tune." },
{ "TownCityDay5", "You hear a merchant pushing his wares." },
{ "TownCityDay6", "Someone hollers for guards in the distance." },
//{ "TownCityDay7", "" },
//{ "TownCityDay8", "" },
//{ "TownCityDay9", "" },
//---
{ "TownCityNight0", "The cityfolk secure their houses at night." },
{ "TownCityNight1", "Someone is humming a tune." },
{ "TownCityNight2", "You hear someone fiddling with a lock." },
{ "TownCityNight3", "Distant guards call for a criminal to halt." },
{ "TownCityNight4", "You hear some laughter in a house." },
{ "TownCityNight5", "You can hear some drunken patrons." },
{ "TownCityNight6", "Someone is snoring loudly." },
{ "TownCityNight7", "Feline eyes flash at you and disappear." },
// { "TownCityNight8", "" },
// { "TownCityNight9", "" },
//--- ---
// Hamlet Day/Night:
{ "TownHamletDay0", "Some herbs are being smoked." },
{ "TownHamletDay1", "Someone is chopping wood." },
//{ "TownHamletDay2", "" },
{ "TownHamletDay3", "A waft of exciting spices finds your nose." },
// { "TownHamletDay4", "" },
//{ "TownHamletDay5", "" },
// { "TownHamletDay6", "" },
{ "TownHamletDay7", "A horse neighs and scrapes the ground." },
//{ "TownHamletDay8", "" },
//{ "TownHamletDay9", "" },
//---
{ "TownHamletNight0", "You hear someone trying a lock." },
{ "TownHamletNight1", "Someone is smoking something." },
{ "TownHamletNight2", "The homes are filled with life and laughter." },
{ "TownHamletNight3", "You see figures in the windows." },
{ "TownHamletNight4", "You hear some restless animals." },
{ "TownHamletNight5", "A cat scurries after a rodent." },
//{ "TownHamletNight6", "" },
// { "TownHamletNight7", "" },
// { "TownHamletNight8", "" },
//{ "TownHamletNight9", "" },
//--- ---
// Village Day/Night:
//{ "TownVillageDay0", "" },
{ "TownVillageDay1", "Someone calls for a dog in the distance." },
//{ "TownVillageDay2", "" },
{ "TownVillageDay3", "The smell of fresh bread fills the air." },
{ "TownVillageDay4", "A local is chopping firewood." },
{ "TownVillageDay5", "Someone is smoking some meat." },
{ "TownVillageDay6", "Some neighbours are laughing together." },
//{ "TownVillageDay7", "" },
//{ "TownVillageDay8", "" },
{ "TownVillageDay9", "A local is cleaning their window." },
//---
{ "TownVillageNight0", "A pig has gotten into some cabbages." },
{ "TownVillageNight1", "A quiet walk in peaceful streets." },
{ "TownVillageNight2", "You can hear someone's fire crackling." },
{ "TownVillageNight3", "The street lights bounce off the homes." },
{ "TownVillageNight4", "Seeing the glow of the fires is soothing." },
//{ "TownVillageNight5", "" },
{ "TownVillageNight6", "You nearly trip on a cat." },
//{ "TownVillageNight7", "" },
// { "TownVillageNight8", "" },
// { "TownVillageNight9", "" },
//--- ---
// Tavern Day/Night:
{ "TavernDay0", "A few adventurers have just left." },
{ "TavernDay1", "A plate is smashed, followed by laughter." },
{ "TavernDay2", "Many of the residents are tavern workers." },
{ "TavernDay3", "A man is walking gingerly, covering his eyes." },
//{ "TavernDay4", "" },
{ "TavernDay5", "The patrons scare the birds." },
//{ "TavernDay6", "" },
//{ "TavernDay7", "" },
{ "TavernDay8", "A drunkard thinks he's your friend." },
//---
{ "TavernNight0", "A drunk figure stumbles off." },
{ "TavernNight1", "You hear the patrons bellowing a tune." },
{ "TavernNight2", "You pass a questionable puddle." },
{ "TavernNight3", "You can smell the fire, feast and foam." },
{ "TavernNight4", "Shapes move in the windows, a lively tavern." },
{ "TavernNight5", "Someone was passed out here recently." },
//{ "TavernNight6", "" },
{ "TavernNight7", "It sounds like a fight has broken out." },
//--- ---
// Farms Day/Night:
//{ "HomeFarmsDay0", "" },
{ "HomeFarmsDay1", "The air is a mix of scents." },
{ "HomeFarmsDay2", "A rather attractive worker smiles at you." },
{ "HomeFarmsDay3", "The animals make their presence known." },
{ "HomeFarmsDay4", "A slight breeze sways the crops." },
{ "HomeFarmsDay5", "You see some wagon tracks here." },
{ "HomeFarmsDay6", "One of the workers is jealous of his friend's new hoe." },
//---
{ "HomeFarmsNight0", "There are some decomposing vegetables near." },
//{ "HomeFarmsNight1", "" },
{ "HomeFarmsNight2", "The animals are settling down." },
{ "HomeFarmsNight3", "The workers arrive around dawn." },
//{ "HomeFarmsNight4", "" },
//--- ---
// WealthyHomes Day/Night:
{ "HomeWealthyDay0", "The sun shines on polished metals." },
{ "HomeWealthyDay1", "These people have afforded a comfortable life." },
{ "HomeWealthyDay2", "Some of the people seem very annoyed by your presence." },
{ "HomeWealthyDay3", "You see fine fabrics with ornate buckles." },
// { "HomeWealthyDay4", "" },
//{ "HomeWealthyDay5", "" },
{ "HomeWealthyDay6", "Workers tend to the gardens." },
{ "HomeWealthyDay7", "Even the animals have quality accomodations." },
{ "HomeWealthyDay8", "You spot a young woman wearing nordic silk." },
{ "HomeWealthyDay9", "The residents carry trinkets you've never seen before." },
//---
{ "HomeWealthyNight0", "A thief's dream." },
{ "HomeWealthyNight1", "The residents secure their belongings at night." },
{ "HomeWealthyNight2", "A cat slinks by with a brass bell on it's collar." },
//{ "HomeWealthyNight3", "" },
{ "HomeWealthyNight4", "A pony can be heard nearby." },
{ "HomeWealthyNight5", "A silver caraff is being used as a flower pot." },
//--- ---
// PoorHomes Day/Night:
{ "HomePoorDay0", "This is a rather depressing area." },
{ "HomePoorDay1", "You watch your step among the droppings." },
{ "HomePoorDay2", "Someone is coughing." },
//{ "HomePoorDay3", "" },
{ "HomePoorDay4", "You can see where a wagon trail used to exist." },
{ "HomePoorDay5", "There's garbage strewn about." },
{ "HomePoorDay6", "Holes in the roof are patched haphazardly." },
// { "HomePoorDay7", "" },
// { "HomePoorDay8", "" },
// { "HomePoorDay9", "" },
//---
{ "HomePoorNight0", "A sneeze can be heard from the house." },
{ "HomePoorNight1", "Something doesn't smell good." },
{ "HomePoorNight2", "Some rodents squeak and scatter." },
{ "HomePoorNight3", "You think something was buried here." },
{ "HomePoorNight4", "You hear someone crying." },
//--- ---
// PlayerShip Day/Night:
{ "HomeYourShipsDay0", "You see some movement in the distance." },
{ "HomeYourShipsDay1", "You hear the wind whipping the sails." },
// { "HomeYourShipsDay2", "" },
// { "HomeYourShipsDay3", "" },
// { "HomeYourShipsDay4", "" },
//---
//{ "HomeYourShipsNight0", "" },
// { "HomeYourShipsNight1", "" },
{ "HomeYourShipsNight2", "The sails flap lazily in the breeze." },
// { "HomeYourShipsNight3", "" },
// { "HomeYourShipsNight4", "" },
//--- ---
// Graveyard Day/Night:
{ "GraveyardDay0", "Some decorations wilt on a tombstone." },
{ "GraveyardDay1", "A makeshift grave was dug here." },
{ "GraveyardDay2", "A shovel has been discarded nearby." },
{ "GraveyardDay3", "This engraving is from ages ago." },
{ "GraveyardDay4", "You feel as if you aren't alone." },
//---
{ "GraveyardNight0", "Some fresh flowers rest on a grave." },
{ "GraveyardNight1", "Something is making a thumping noise." },
{ "GraveyardNight2", "Something is running away." },
{ "GraveyardNight3", "Pray the dead stay dead." },
{ "GraveyardNight4", "One of the graves has some fresh turned earth." },
//--- ---
// Coven Day/Night:
{ "CovenDay0", "You smell a bubbling pot." },
{ "CovenDay1", "Some potions are stashed out of the light." },
{ "CovenDay2", "They stare at you." },
{ "CovenDay3", "\"The Stricture\" can be read on a piece of parchment." },
{ "CovenDay4", "Access to great power can be obtained here." },
{ "CovenDay5", "A thick smoke rises." },
// { "CovenDay6", "" },
// { "CovenDay7", "" },
// { "CovenDay8", "" },
//---
{ "CovenNight0", "A strange shadow drifts away." },
{ "CovenNight1", "A dark energy lingers here." },
{ "CovenNight2", "Potions glow faintly under some cloth." },
{ "CovenNight3", "Ancient rituals disturb the locals." },
{ "CovenNight4", "A witch has succumbed to a trance." },
{ "CovenNight5", "They speak not, but you hear." },
{ "CovenNight6", "An arrid smoke lingers." },
// { "CovenNight7", "" },
// { "CovenNight8", "" },
//--- ---
// Temple Day/Night:
{ "ReligionTempleDay0", "The residents recite religious texts." },
{ "ReligionTempleDay1", "Some devotees are wearing ceremonial garb." },
{ "ReligionTempleDay2", "An elder blesses your path." },
{ "ReligionTempleDay3", "A young pilgrim gestures to the sky." },
{ "ReligionTempleDay4", "A beggar receives some aid." },
{ "ReligionTempleDay5", "Some chimes signal a prayer." },
{ "ReligionTempleDay6", "People speak softly near the temple." },
{ "ReligionTempleDay7", "An elder is reading a holy book." },
{ "ReligionTempleDay8", "The worshippers seem to float as they walk." },
{ "ReligionTempleDay9", "A pilgrim is stitching some religious attire." },
//---
{ "ReligionTempleNight0", "A pipe is being smoked." },
{ "ReligionTempleNight1", "You hear people chanting." },
{ "ReligionTempleNight2", "The windows have religious markings." },
{ "ReligionTempleNight3", "You hear laughter in one of the houses." },
{ "ReligionTempleNight4", "There is a tranquil ambience." },
{ "ReligionTempleNight5", "Chanting can be heard \"Obey your Emperor\"." },
{ "ReligionTempleNight6", "Chanting can be heard \"Study the Covenants\"." },
{ "ReligionTempleNight7", "Chanting can be heard \"Worship the Eight\"." },
{ "ReligionTempleNight8", "Chanting can be heard \"Do your duty\"." },
{ "ReligionTempleNight9", "Chanting can be heard \"Heed the commands of the Saints and Priests\"." },
//--- ---
// Cult Day/Night:
{ "ReligionCultDay0", "The day illuminates all deeds." },
{ "ReligionCultDay1", "Special herbs are being burned." },
{ "ReligionCultDay2", "The years have aged this place." },
{ "ReligionCultDay3", "You hear some magic." },
{ "ReligionCultDay4", "This building is contorted." },
//---
{ "ReligionCultNight0", "A low humming can be heard." },
{ "ReligionCultNight1", "An unusual smell lingers in the air." },
{ "ReligionCultNight2", "Many voices stop at once." },
{ "ReligionCultNight3", "A distant laugh echoes past." },
{ "ReligionCultNight4", "A blade is being sharpened." },
//--- ---
// Dungeon Day/Night:
{ "DungeonLabyrinthDay0", "The daylight reveals blood stains." },
{ "DungeonLabyrinthDay1", "There are shreds of a cloak on the ground." },
{ "DungeonLabyrinthDay2", "Scraps of metal and bone are everywhere." },
{ "DungeonLabyrinthDay3", "A warning is scratched onto the entrance." },
{ "DungeonLabyrinthDay4", "A religious marking has been corrupted." },
{ "DungeonLabyrinthDay5", "You hear a thousand whispers beneath you." },
{ "DungeonLabyrinthDay6", "Many travellers have fallen here." },
{ "DungeonLabyrinthDay7", "You feel a strange draw to the dungeon entrance." },
{ "DungeonLabyrinthDay8", "Anguish shapes the minds of those who enter." },
{ "DungeonLabyrinthDay9", "A Gods forsaken Oblivion hole." },
//---
{ "DungeonLabyrinthNight0", "You feel bones underfoot." },
{ "DungeonLabyrinthNight1", "Ghostly warnings haunt your ears." },
{ "DungeonLabyrinthNight2", "This place tests the resolve of mortals." },
{ "DungeonLabyrinthNight3", "The forces of evil lurk here." },
{ "DungeonLabyrinthNight4", "The torment of Oblivion flashes in your mind." },
//{ "DungeonLabyrinthNight5", "" },
// { "DungeonLabyrinthNight6", "" },
{ "DungeonLabyrinthNight7", "You hear a desperate cry from the deep." },
{ "DungeonLabyrinthNight8", "The entrance is a blinding darkness." },
// { "DungeonLabyrinthNight9", "" },
//--- ---

{ "DungeonKeepDay0", "Ritual markings are to protect those who tread." },
{ "DungeonKeepDay1", "Many adventurers fall pray to these depths." },
{ "DungeonKeepDay2", "There are some tracks leading into the dungeon." },
{ "DungeonKeepDay3", "A book of destruction magic is mostly burned." },
{ "DungeonKeepDay4", "Blood was spilled recently." },
{ "DungeonKeepDay5", "A tribute was left for the dead." },
{ "DungeonKeepDay6", "Something big was dragged away from here." },
{ "DungeonKeepDay7", "A ripped cloak is discarded nearby." },
{ "DungeonKeepDay8", "There is a great sadness here." },
{ "DungeonKeepDay9", "An inscription reads \"may the Gods protect you\"." },
//---
{ "DungeonKeepNight0", "You think you hear something below." },
{ "DungeonKeepNight1", "Only the hearty survive." },
{ "DungeonKeepNight2", "The air is deadly still." },
{ "DungeonKeepNight3", "You feel watched." },
{ "DungeonKeepNight4", "Birds call out a warning." },
//{ "DungeonKeepNight5", "" },
{ "DungeonKeepNight6", "A brutal death flashes in your mind." },
{ "DungeonKeepNight7", "The darkness hides the entrance." },
// { "DungeonKeepNight8", "" },
// { "DungeonKeepNight9", "" },
//--- ---

{ "DungeonRuinDay0", "Adventurers have been here recently." },
{ "DungeonRuinDay1", "Someone was camping nearby." },
{ "DungeonRuinDay2", "These religious symbols are rather fresh." },
{ "DungeonRuinDay3", "Someone tried to draw a map." },
{ "DungeonRuinDay4", "The door is ajar." },
{ "DungeonRuinDay5", "Someone had their wagon nearby." },
{ "DungeonRuinDay6", "Birds chirp and fly overhead." },
//{ "DungeonRuinDay7", "" },
{ "DungeonRuinDay8", "You think you hear something." },
{ "DungeonRuinDay9", "A broken sword is discarded nearby." },
//---
{ "DungeonRuinNight0", "A loose stone tumbles to the ground." },
{ "DungeonRuinNight1", "The air is musty." },
//{ "DungeonRuinNight2", "" },
{ "DungeonRuinNight3", "The darkness is cloaking the entrance." },
{ "DungeonRuinNight4", "A smashed potion bottle is nearly buried." },
//{ "DungeonRuinNight5", "" },
// { "DungeonRuinNight6", "" },
// { "DungeonRuinNight7", "" },
// { "DungeonRuinNight8", "" },
// { "DungeonRuinNight9", "" },
//--- ---


            #endregion

            #region Dungeon texts:



// Dungeon: Crypt
{ "Crypt0", "You sense something creeping behind you." },
{ "Crypt1", "A gust of cold air blows past you." },
{ "Crypt2", "You hear some distant rattling." },
{ "Crypt3", "You brush a cobweb off your shoulder." },
{ "Crypt4", "The air here is very stiff." },
{ "Crypt5", "This place smells strongly of death." },
{ "Crypt6", "You hear very faint whispers." },
{ "Crypt7", "A strange shadow moves and vanishes." },
{ "Crypt8", "Tiny bugs scurry away from you." },
{ "Crypt9", "You hear unholy sounds." },

// Dungeon: OrcStronghold
{ "OrcStronghold0", "Your nose fills with soot when you breath." },
{ "OrcStronghold1", "The cobwebs fill with fur." },
{ "OrcStronghold2", "Animal marks are everywhere." },
{ "OrcStronghold3", "A crude potion recipe has withered nearby." },
{ "OrcStronghold4", "You see writing in some primitive Orcish script." },
{ "OrcStronghold5", "You hear some snorting in the distance." },
{ "OrcStronghold6", "Some bones have been crushed." },
{ "OrcStronghold7", "A symbol of Malacath is just visible under the soot." },
{ "OrcStronghold8", "Charcoal smoke lingers in the air." },
{ "OrcStronghold9", "The floor and walls have slash marks." },

// Dungeon: HumanStronghold
{ "HumanStronghold0", "You hear the distant shot of an arrow." },
{ "HumanStronghold1", "Someone is whispering in the distance." },
{ "HumanStronghold2", "Deep scratches cover the floor." },
{ "HumanStronghold3", "Weapon fragments litter the floor." },
{ "HumanStronghold4", "You can smell some blood." },
{ "HumanStronghold5", "You smell burnt wood." },
{ "HumanStronghold6", "Someone spilled ale here." },
{ "HumanStronghold7", "A magicka rune is just visible under the dust." },
{ "HumanStronghold8", "There's some strange fur here." },
{ "HumanStronghold9", "The shadows play tricks." },

// Dungeon: Prison
{ "Prison0", "Nearby scrawlings plead for release." },
{ "Prison1", "You see old, tormented scribblings nearby." },
{ "Prison2", "The scent of a rotten corpse gathers here." },
{ "Prison3", "Part of a broken key lays on the ground." },
{ "Prison4", "You notice tally marks scratched nearby." },
{ "Prison5", "You hear whispers from the darkness." },
{ "Prison6", "The shadows change and move." },
{ "Prison7", "You smell the remnants of poison." },
{ "Prison8", "Someone tried digging here." },
{ "Prison9", "Metal bars rattle in the distance." },

// Dungeon: Desecrated Temple
{ "DesecratedTemple0", "You sense strong magic in the air." },
{ "DesecratedTemple1", "You see a prayer to the Gods scrawled here." },
{ "DesecratedTemple2", "Someone scratched a religious symbol." },
{ "DesecratedTemple3", "The feeling of death is overwhelming here." },
{ "DesecratedTemple4", "You feel a rift of energy." },
{ "DesecratedTemple5", "Vengeful spirits roam these depths." },
{ "DesecratedTemple6", "Unholy energies permeate this area." },
{ "DesecratedTemple7", "Your thoughts are invaded by Daedra." },
{ "DesecratedTemple8", "Movement blends into shadows." },
{ "DesecratedTemple9", "The sanctity of this place has been fouled." },

// Dungeon: Mine
{ "Mine0", "It smells like Orc blood." },
{ "Mine1", "Small bugs flee your step." },
{ "Mine2", "Heavy footsteps have worn this ground smooth." },
{ "Mine3", "You notice writing in a strange language." },
{ "Mine4", "Spider webs fill some cracks in the wall." },
{ "Mine5", "The ground is unusually warm here." },
{ "Mine6", "Some animals have marked their territory." },
{ "Mine7", "A rock tumbles to the ground in the distance." },
{ "Mine8", "Someone tried to dig here." },
{ "Mine9", "Something pounds a surface, far away." },

// Dungeon: Natural Cave
{ "NaturalCave0", "You hear a tiny bat flutter away." },
{ "NaturalCave1", "The shadows change shape." },
{ "NaturalCave2", "A bug slinks across your path." },
{ "NaturalCave3", "There's some smashed pottery here." },
{ "NaturalCave4", "You hear something rustling about." },
{ "NaturalCave5", "A moth flutters by." },
{ "NaturalCave6", "You see some gnarled fur here." },
{ "NaturalCave7", "Cobwebs fill the cracks and corners." },
{ "NaturalCave8", "There's some stomping in the distance." },
{ "NaturalCave9", "Animals have made a home in here." },

// Dungeon: Coven
{ "Coven0", "You see someone when you close your eyes." },
{ "Coven1", "You hear whispering." },
{ "Coven2", "Chanting pursues you from afar." },
{ "Coven3", "You feel very dark energies here." },
{ "Coven4", "You wipe some oddly-colored dust from your face." },
{ "Coven5", "Daedra lurk in the depths." },
{ "Coven6", "Magic has stained the walls." },
{ "Coven7", "This area smells of festered concoctions." },
{ "Coven8", "Smashed potion bottles litter the area." },
{ "Coven9", "Laughter echoes off the walls." },

// Dungeon: VampireHaunt
{ "VampireHaunt0", "There's a faded message in an ancient language." },
{ "VampireHaunt1", "Indistinct hissing comes from afar." },
{ "VampireHaunt2", "You smell blood." },
{ "VampireHaunt3", "Something was recently dragged through here." },
{ "VampireHaunt4", "The air here is disturbed." },
{ "VampireHaunt5", "Unintelligible markings cover the ground." },
{ "VampireHaunt6", "The shadows dominate your vision." },
{ "VampireHaunt7", "A smashed vial of blood crinkles underfoot." },
{ "VampireHaunt8", "A cold gust of air catches you off guard." },
{ "VampireHaunt9", "You can feel your heart beating." },

// Dungeon: Laboratory
{ "Laboratory0", "A tingling vapour flows over your feet." },
{ "Laboratory1", "The air is a mix of noxious vapours." },
{ "Laboratory2", "Insane scrawlings fade on the walls." },
{ "Laboratory3", "You see some notes, nearly destroyed." },
{ "Laboratory4", "You feel concentrated magical forces." },
{ "Laboratory5", "Something is stomping around." },
{ "Laboratory6", "The air suddenly turns cold." },
{ "Laboratory7", "You sense volatile magicka in this area." },
{ "Laboratory8", "An evil laugh echoes past." },
{ "Laboratory9", "Some shattered glass crinkles underfoot." },

// Dungeon: HarpyNest
{ "HarpyNest0", "Some bones have nearly vanished." },
{ "HarpyNest1", "The stench of harpy is unbearable here." },
{ "HarpyNest2", "You avoid stepping in animal droppings." },
{ "HarpyNest3", "You just catch the sound of footsteps." },
{ "HarpyNest4", "Caustic magicka festered here." },
{ "HarpyNest5", "Shreds of an old cloak are covered in cobwebs." },
{ "HarpyNest6", "The floor and walls bear faint scratch marks." },
{ "HarpyNest7", "A primitive spell was cast here." },
{ "HarpyNest8", "Carrion stench strikes your nose." },
{ "HarpyNest9", "The scurrying bugs sound like a whisper." },

// Dungeon: RuinedCastle
{ "RuinedCastle0", "You hear the distant sound of a sword." },
{ "RuinedCastle1", "The shadows trick your eyes." },
{ "RuinedCastle2", "You see ancient markings here." },
{ "RuinedCastle3", "Fur is floating in a puddle of mead." },
{ "RuinedCastle4", "The smell of death fills the air." },
{ "RuinedCastle5", "Dust fills the cobwebs." },
{ "RuinedCastle6", "An old potion bottle is smashed on the floor." },
{ "RuinedCastle7", "The undead poison the air." },
{ "RuinedCastle8", "Your mouth fills with soot when you breathe." },
{ "RuinedCastle9", "Unholy sounds echo off the walls." },

// Dungeon: SpiderNest
{ "SpiderNest0", "Webs fill the cracks in the walls." },
{ "SpiderNest1", "A tiny spider skitters across the ground." },
{ "SpiderNest2", "You hear bugs scurrying." },
{ "SpiderNest3", "Something is scratching a surface nearby." },
{ "SpiderNest4", "The floor is slightly sticky." },
{ "SpiderNest5", "You hear creaking movement." },
{ "SpiderNest6", "Enemies lurk in the darkness." },
{ "SpiderNest7", "The husks of bug carcasses litter your path." },
{ "SpiderNest8", "Something hisses in the distance." },
{ "SpiderNest9", "A small spider crawls out of your possessions." },

// Dungeon: GiantStronghold
{ "GiantStronghold0", "Animals have left their marks." },
{ "GiantStronghold1", "The stench of unbathed skin fills the air." },
{ "GiantStronghold2", "Bare footprints cover the ground." },
{ "GiantStronghold3", "You hear some distant snorting." },
{ "GiantStronghold4", "You think you hear stomping." },
{ "GiantStronghold5", "A fight left deep scratches and grooves." },
{ "GiantStronghold6", "Your movement has stirred up some fur." },
{ "GiantStronghold7", "Orcs have drawn some markings here." },
{ "GiantStronghold8", "The ground rumbles as something lumbers about." },
{ "GiantStronghold9", "Daedric energies darken the halls." },

// Dungeon: DragonsDen
{ "DragonsDen0", "You see some wilted dragon scales." },
{ "DragonsDen1", "The floor here has been hardened by heat." },
{ "DragonsDen2", "There are scratches on the walls." },
{ "DragonsDen3", "A symbol of Akatosh is drawn in blood." },
{ "DragonsDen4", "You are reminded of Akavir." },
{ "DragonsDen5", "Magic was used here." },
{ "DragonsDen6", "Ancient power courses through the air." },
{ "DragonsDen7", "You smell smoke." },
{ "DragonsDen8", "Some bones have gnaw marks." },
{ "DragonsDen9", "Fur was shed here." },

// Dungeon: BarbarianStronghold
{ "BarbarianStronghold0", "There are bootprints in the dust." },
{ "BarbarianStronghold1", "Ancient evil darkens these corridors." },
{ "BarbarianStronghold2", "There are remnants of cobwebs." },
{ "BarbarianStronghold3", "Something is stomping the ground." },
{ "BarbarianStronghold4", "You see thick, coarse fur." },
{ "BarbarianStronghold5", "You smell the smoke of a fireplace." },
{ "BarbarianStronghold6", "You vaguely smell some wine." },
{ "BarbarianStronghold7", "A fire spell scorched the ground here." },
{ "BarbarianStronghold8", "A sigil is just visible here." },
{ "BarbarianStronghold9", "You think you hear distant laughter." },

// Dungeon: VolcanicCaves
{ "VolcanicCaves0", "You feel some air currents along the ground." },
{ "VolcanicCaves1", "The air is moving quickly here." },
{ "VolcanicCaves2", "Some fur blows by you." },
{ "VolcanicCaves3", "The earth rumbles softly." },
{ "VolcanicCaves4", "Animals are attracted to the warmth." },
{ "VolcanicCaves5", "A whiff of sulfur singes your nose." },
{ "VolcanicCaves6", "The air burns your throat." },
{ "VolcanicCaves7", "A summoning sigil was drawn, then erased." },
{ "VolcanicCaves8", "The darkness plays tricks on you." },
{ "VolcanicCaves9", "You smell something burning." },

// Dungeon: ScorpionNest
{ "ScorpionNest0", "Tiny bits of animal bones litter this area." },
{ "ScorpionNest1", "You see the remains of a molted shell." },
{ "ScorpionNest2", "The shadows move behind you." },
{ "ScorpionNest3", "You hear distant rattling and scratching." },
{ "ScorpionNest4", "Dark forces twist the life here." },
{ "ScorpionNest5", "Rat fur litters the cobwebs." },
{ "ScorpionNest6", "A tiny scorpion crawls out from your possessions." },
{ "ScorpionNest7", "The air is stale." },
{ "ScorpionNest8", "Some venom scarred the floor here." },
{ "ScorpionNest9", "The insects near you scatter." },

// Dungeon: Cemetery
{ "Cemetery0", "A bug creeps over your foot." },
{ "Cemetery1", "Pray the dead do not seek vengeance." },
{ "Cemetery2", "You smell decomposing bodies." },
{ "Cemetery3", "The air is dense here." },
{ "Cemetery4", "There's a thumping sound." },
{ "Cemetery5", "Faint whispers fill the air." },
{ "Cemetery6", "You feel unwelcome here." },
{ "Cemetery7", "You feel the gaze of the dead upon you." },
{ "Cemetery8", "Someone attempted to dig the ground here." },
{ "Cemetery9", "Bugs scurry into hiding."}

            #endregion
        };

    }
}