// Project:         RoleplayRealism mod for Daggerfall Unity (http://www.dfworkshop.net)
// Copyright:       Copyright (C) 2022 Regnier
// License:         MIT License (http://www.opensource.org/licenses/mit-license.php)
// Author:          Regnier

using System.Collections;

namespace AmbientText
{
    public class AmbientText
    {
        /* Keys are in the following format, and if a key is not present no msg is displayed.
         *  Inside dungeon: <dungeonType><0-9>
         *  Outside:        <locType><climate><0-9>
         *                  <locType><dayNight><0-9>
         *                  <locType><dayNight><weather><0-9>
         * Where:
         *  locType  = None,TownCity,TownHamlet,TownVillage,HomeFarms,DungeonLabyrinth,ReligionTemple,Tavern,DungeonKeep,HomeWealthy,ReligionCult,DungeonRuin,HomePoor,Graveyard,Coven,HomeYourShips
         *  climate  = Desert, Swamp, Woods, Mountains, Ocean
         *  dayNight = Day, Night
         *  weather  = Clear, Cloudy, Rainy, Snowy
         *  dungeonType = Crypt,OrcStronghold,HumanStronghold,Prison,DesecratedTemple,Mine,NaturalCave,Coven,VampireHaunt,Laboratory,HarpyNest,RuinedCastle,SpiderNest,GiantStronghold,DragonsDen,BarbarianStronghold,VolcanicCaves,ScorpionNest,Cemetery
         */
        internal static IDictionary AmbientTexts = new Hashtable()
        {

            #region Climate texts:

//Wilderness Climates:  338
{ "NoneDesert0", "Your feet slide in the sand." },
{ "NoneDesert1", "There are some dried bones under the sand." },
{ "NoneDesert2", "The wind rustles some dried plants." },
{ "NoneDesert3", "The heat rises off the sand." },
{ "NoneDesert4", "A snake submerges in the sand." },
{ "NoneDesert5", "The sand finds its way into your pack." },
//{ "NoneDesert6", "" },
{ "NoneDesert7", "A breeze cools you." },
//{ "NoneDesert8", "" },
{ "NoneDesert9", "You brush sand out of your eyes." },
//---
{ "NoneSwamp0", "Someone burned oil here." },
//{ "NoneSwamp1", "" },
//{ "NoneSwamp2", "" },
{ "NoneSwamp3", "The area is quite muddy." },
//{ "NoneSwamp4", "" },
{ "NoneSwamp5", "Your feet slide in the mud." },
{ "NoneSwamp6", "The breeze carries a stench." },
{ "NoneSwamp7", "You breathe the thick, damp air." },
//{ "NoneSwamp8", "" },
{ "NoneSwamp9", "You stub your toe on a root." },
//---
{ "NoneWoods0", "A breeze rustles some branches." },
{ "NoneWoods1", "An animal calls in the distance." },
{ "NoneWoods2", "The air carries a sylvan scent." },
{ "NoneWoods3", "Twigs snap underneath your step." },
//{ "NoneWoods4", "" },
//{ "NoneWoods5", "" },
{ "NoneWoods6", "You brush some twigs off your shoulder." },
{ "NoneWoods7", "An animal rustles in the tree near you." },
//{ "NoneWoods8", "" },
{ "NoneWoods9", "You breathe the clean, fresh air." },
//---
//{ "NoneMountains0", "" },
{ "NoneMountains1", "An animal can be heard in the distance." },
{ "NoneMountains2", "You cross over some old bones." },
{ "NoneMountains3", "The mountain ranges dominate the skyline." },
//{ "NoneMountains4", "" },
{ "NoneMountains5", "The air is rather thin." },
{ "NoneMountains6", "Sounds echo off the hills." },
//{ "NoneMountains7", "" },
//{ "NoneMountains8", "" },
//{ "NoneMountains9", "" },
//---
{ "NoneOcean0", "Calm waves roll around you." },
{ "NoneOcean1", "The smell of the sea fills your lungs." },
//{ "NoneOcean2", "" },
{ "NoneOcean3", "The waves are hypnotizing." },
{ "NoneOcean4", "" },
{ "NoneOcean5", "You inhale some water." },
{ "NoneOcean6", "The ocean breeze revitalizes you." },
{ "NoneOcean7", "The sound of the ocean is like a lullaby." },
//{ "NoneOcean8", "" },
//{ "NoneOcean9", "" },
//--- ---

//--- ---
//City Climates:
{ "TownCityDesert0", "You smell roasting scorpion." },
{ "TownCityDesert1", "The animals huff and scrape the ground." },
//{ "TownCityDesert2", "" },
{ "TownCityDesert3", "A breeze dusts you with sand." },
// { "TownCityDesert4", "" },
//{ "TownCityDesert5", "" },
//{ "TownCityDesert6", "" },
//{ "TownCityDesert7", "" },
{ "TownCityDesert8", "You smell scented oils being burned." },
//{ "TownCityDesert9", "" },
//---
//{ "TownCitySwamp0", "" },
//{ "TownCitySwamp1", "" },
{ "TownCitySwamp2", "Plantgrowth adorns most houses." },
{ "TownCitySwamp3", "The smokey flames help keep the bugs away." },
//{ "TownCitySwamp4", "" },
{ "TownCitySwamp5", "The smell of mud is replaced by fresh baked bread." },
//{ "TownCitySwamp6", "" },
//{ "TownCitySwamp7", "" },
// { "TownCitySwamp8", "" },
// { "TownCitySwamp9", "" },
//---
{ "TownCityWoods0", "The smell of roast pig fills the air." },
//{ "TownCityWoods1", "" },
{ "TownCityWoods2", "Some birds play in the tree near you." },
{ "TownCityWoods3", "The smell of woodsmoke is soothing." },
//{ "TownCityWoods4", "" },
{ "TownCityWoods5", "A breeze rustles some branches." },
// { "TownCityWoods6", "" },
//{ "TownCityWoods7", "" },
// { "TownCityWoods8", "" },
//{ "TownCityWoods9", "" },
//---
{ "TownCityMountains0", "This area smells heavily of roast chicken." },
{ "TownCityMountains1", "The wind can be quite strong here." },
//{ "TownCityMountains2", "" },
{ "TownCityMountains3", "The cityfolk feel they are closer to the Gods here." },
{ "TownCityMountains4", "Some of the rocks have religious markings." },
{ "TownCityMountains5", "The city streets contain mountain rocks." },
//{ "TownCityMountains6", "" },
// { "TownCityMountains7", "" },
// { "TownCityMountains8", "" },
// { "TownCityMountains9", "" },
//--- ---

//--- ---
//Hamlet Climates:
{ "TownHamletDesert0", "Some sand gathers on the window sills." },
//{ "TownHamletDesert1", "" },
{ "TownHamletDesert2", "There must be some camels nearby." },
{ "TownHamletDesert3", "You catch the scent of a hearty stew." },
//{ "TownHamletDesert4", "" },
//{ "TownHamletDesert5", "" },
//{ "TownHamletDesert6", "" },
{ "TownHamletDesert7", "You wipe some sand off your face." },
//{ "TownHamletDesert8", "" },
//{ "TownHamletDesert9", "" },
//---
// { "TownHamletSwamp0", "" },
//{ "TownHamletSwamp1", "" },
//{ "TownHamletSwamp2", "" },
//{ "TownHamletSwamp3", "" },
//{ "TownHamletSwamp4", "." },
{ "TownHamletSwamp5", "The moss grows rapidly on the houses." },
//{ "TownHamletSwamp6", "" },
{ "TownHamletSwamp7", "A breeze provides some relief." },
{ "TownHamletSwamp8", "You can smell some smoking oil." },
//{ "TownHamletSwamp9", "" },
//---
{ "TownHamletWoods0", "You smell freshly chopped firewood." },
{ "TownHamletWoods1", "A soft breeze flutters some fabric." },
{ "TownHamletWoods2", "The smell of woodfire is welcoming." },
//{ "TownHamletWoods3", "" },
//{ "TownHamletWoods4", "" },
//{ "TownHamletWoods5", "" },
//{ "TownHamletWoods6", "" },
//{ "TownHamletWoods7", "" },
//{ "TownHamletWoods8", "" },
//{ "TownHamletWoods9", "" },
//---
{ "TownHamletMountains0", "You smell a wonderous spice from someones window." },
{ "TownHamletMountains1", "Some fabric flaps in the breeze." },
{ "TownHamletMountains2", "Some rocks are adorned with small decorations." },
{ "TownHamletMountains3", "You can feel the breeze on your skin." },
{ "TownHamletMountains4", "The air is very fresh and clean." },
//{ "TownHamletMountains5", "" },
//{ "TownHamletMountains6", "" },
//{ "TownHamletMountains7", "" },
//{ "TownHamletMountains8", "" },
//{ "TownHamletMountains9", "" },
//--- ---

//--- ---
//Village Climates:
{ "TownVillageDesert0", "The sand builds on the sides of the homes." },
{ "TownVillageDesert1", "A beetle rests in the sand nearby." },
//{ "TownVillageDesert2", "" },
{ "TownVillageDesert3", "A pipe is being smoked." },
//{ "TownVillageDesert4", "" },
//{ "TownVillageDesert5", "" },
{ "TownVillageDesert6", "Oil smoke scents the air." },
//{ "TownVillageDesert7", "" },
//{ "TownVillageDesert8", "" },
//{ "TownVillageDesert9", "" },
//---
//{ "TownVillageSwamp0", "" },
{ "TownVillageSwamp1", "The smell of woodfire replaces the stale bog." },
{ "TownVillageSwamp2", "The breeze smells of fresh bread." },
//{ "TownVillageSwamp3", "" },
{ "TownVillageSwamp4", "A tiny lizard scurries into the plantgrowth." },
{ "TownVillageSwamp5", "You hear a bird fly off." },
{ "TownVillageSwamp6", "Your feet slide on the muddy ground." },
// { "TownVillageSwamp7", "" },
// { "TownVillageSwamp8", "" },
// { "TownVillageSwamp9", "" },
//---
//{ "TownVillageWoods0", "" },
{ "TownVillageWoods1", "You smell the smoke of a fireplace." },
{ "TownVillageWoods2", "You hear some fabric flapping in the breeze." },
//{ "TownVillageWoods3", "" },
{ "TownVillageWoods4", "The smell of seared pork fills the air." },
//{ "TownVillageWoods5", "" },
//{ "TownVillageWoods6", "" },
//{ "TownVillageWoods7", "" },
{ "TownVillageWoods8", "You hear the wind rustle some branches." },
//{ "TownVillageWoods9", "" },
//---
//{ "TownVillageMountains0", "" },
{ "TownVillageMountains1", "The wind pushes you slightly." },
{ "TownVillageMountains3", "A bubbling stew scents the air." },
{ "TownVillageMountains4", "The mountains dwarf this modest place." },
{ "TownVillageMountains5", "Mountain flowers adorn some windows." },
//{ "TownVillageMountains6", "" },
//{ "TownVillageMountains7", "" },
{ "TownVillageMountains8", "You hear some birds nearby." },
//{ "TownVillageMountains9", "" },
//--- ---

//--- ---
//Tavern Climates:
{ "TavernDesert0", "You wipe the sand from your eyes." },
//{ "TavernDesert1", "" },
{ "TavernDesert2", "There's a concerning clump of sand nearby." },
//{ "TavernDesert3", "" },
{ "TavernDesert4", "You smell freshly chopped wood." },
//{ "TavernDesert5", "" },
//{ "TavernDesert6", "" },
//{ "TavernDesert7", "" },
//{ "TavernDesert8", "" },
{ "TavernDesert9", "You can smell the ale from here." },
//---
//{ "TavernSwamp0", "" },
{ "TavernSwamp1", "The streets are rather muddy." },
//{ "TavernSwamp2", "" },
{ "TavernSwamp3", "The scent of ale is all you notice." },
//{ "TavernSwamp4", "" },
//{ "TavernSwamp5", "" },
//{ "TavernSwamp6", "" },
{ "TavernSwamp7", "Someone was sleeping here." },
//{ "TavernSwamp8", "" },
{ "TavernSwamp9", "The patrons call for fresh food." },
//---
//{ "TavernWoods0", "" },
{ "TavernWoods1", "The patrons holler and laugh." },
{ "TavernWoods2", "The scent of ale fills the air." },
{ "TavernWoods3", "The scent of a fireplace beckons you." },
//{ "TavernWoods4", "" },
//{ "TavernWoods5", "" },
//{ "TavernWoods6", "" },
//{ "TavernWoods7", "" },
//{ "TavernWoods8", "" },
//{ "TavernWoods9", "" },
//---
{ "TavernMountains0", "The rocks are covered in broken bottles." },
//{ "TavernMountains1", "" },
//{ "TavernMountains2", "" },
//{ "TavernMountains3", "" },
//{ "TavernMountains4", "" },
{ "TavernMountains5", "The wind is scented with ale." },
{ "TavernMountains6", "You can smell roasting meat." },
//{ "TavernMountains7", "" },
// { "TavernMountains8", "" },
// { "TavernMountains9", "" },
//--- ---

//--- ---
//Farm Climates:
//{ "HomeFarmsDesert0", "" },
//{ "HomeFarmsDesert1", "" },
{ "HomeFarmsDesert2", "The workers have carefully tended to the crops." },
{ "HomeFarmsDesert3", "The wind hides the smell of the farm." },
{ "HomeFarmsDesert4", "Religious symbols are marked around the crops." },
// { "HomeFarmsDesert5", "" },
{ "HomeFarmsDesert6", "The Gods must help this family grow crops out here." },
// { "HomeFarmsDesert7", "" },
{ "HomeFarmsDesert8", "This farm feeds the nearby towns and villages." },
// { "HomeFarmsDesert9", "" },
//---
{ "HomeFarmsSwamp0", "There's plenty of water for the soil here." },
//{ "HomeFarmsSwamp1", "" },
{ "HomeFarmsSwamp2", "The smell is seeping into your belongings." },
// { "HomeFarmsSwamp3", "" },
// { "HomeFarmsSwamp4", "" },
// { "HomeFarmsSwamp5", "" },
// { "HomeFarmsSwamp6", "" },
{ "HomeFarmsSwamp7", "Some birds have found seeds to peck at." },
//{ "HomeFarmsSwamp8", "" },
{ "HomeFarmsSwamp9", "This farm feeds many of the locals." },
//---
//{ "HomeFarmsWoods0", "" },
{ "HomeFarmsWoods1", "Trees were cleared to get sun on the crops." },
//{ "HomeFarmsWoods2", "" },
// { "HomeFarmsWoods3", "" },
// { "HomeFarmsWoods4", "" },
// { "HomeFarmsWoods5", "" },
// { "HomeFarmsWoods6", "" },
{ "HomeFarmsWoods7", "This farm is vital to feeding the locals." },
//{ "HomeFarmsWoods8", "" },
{ "HomeFarmsWoods9", "The breeze carries the scent of the forest." },
//---
//{ "HomeFarmsMountains0", "" },
{ "HomeFarmsMountains1", "The Gods are held dear for mountain growers." },
{ "HomeFarmsMountains2", "Mountain rocks reinforce the walls." },
{ "HomeFarmsMountains3", "The wind carries away the smell." },
//{ "HomeFarmsMountains4", "" },
//{ "HomeFarmsMountains5", "" },
//{ "HomeFarmsMountains6", "" },
//{ "HomeFarmsMountains7", "" },
{ "HomeFarmsMountains8", "The yield here will feed the locals." },
// { "HomeFarmsMountains9", "" },
//--- ---

//--- ---
//Mansion Climates:
{ "HomeWealthyDesert0", "This estate is more well off than others." },
{ "HomeWealthyDesert1", "You see very high quality wares in use." },
//{ "HomeWealthyDesert2", "" },
{ "HomeWealthyDesert3", "The animals lead a good life." },
{ "HomeWealthyDesert4", "The air is scented with flowers." },
// { "HomeWealthyDesert5", "" },
//{ "HomeWealthyDesert6", "" },
// { "HomeWealthyDesert7", "" },
//{ "HomeWealthyDesert8", "" },
// { "HomeWealthyDesert9", "" },
//---
//{ "HomeWealthySwamp0", "" },
{ "HomeWealthySwamp1", "The animals are kept in good condition." },
{ "HomeWealthySwamp2", "This place is more ornate than many others." },
{ "HomeWealthySwamp3", "There is styled plantgrowth on the houses." },
{ "HomeWealthySwamp4", "The smell of the bog is replaced with perfume." },
// { "HomeWealthySwamp5", "" },
{ "HomeWealthySwamp6", "The ground isn't as muddy as most other places." },
{ "HomeWealthySwamp7", "You see a princely looking figure in the window." },
// { "HomeWealthySwamp8", "" },
// { "HomeWealthySwamp9", "" },
//---
{ "HomeWealthyWoods0", "These houses are sturdy and secure." },
//{ "HomeWealthyWoods1", "" },
{ "HomeWealthyWoods2", "There are some intricate carvings on the houses." },
// { "HomeWealthyWoods3", "" },
// { "HomeWealthyWoods4", "" },
// { "HomeWealthyWoods5", "" },
{ "HomeWealthyWoods6", "The animals have shiny, healthy coats." },
// { "HomeWealthyWoods7", "" },
{ "HomeWealthyWoods8", "You smell an incredibly rare spice." },
//{ "HomeWealthyWoods9", "" },
//---
//{ "HomeWealthyMountains0", "" },
{ "HomeWealthyMountains1", "Rare scents fill your nose." },
{ "HomeWealthyMountains2", "Flowers decorate these buildings." },
//{ "HomeWealthyMountains3", "" },
//{ "HomeWealthyMountains4", "" },
// { "HomeWealthyMountains5", "" },
// { "HomeWealthyMountains6", "" },
{ "HomeWealthyMountains7", "Some of the rocks have carvings inlet with gems." },
//{ "HomeWealthyMountains8", "" },
// { "HomeWealthyMountains9", "" },
//--- ---

//--- ---
//Hovel Climates:
{ "HomePoorDesert0", "The house has fallen into disrepair." },
{ "HomePoorDesert1", "There's a stale smell coming from the house." },
//{ "HomePoorDesert2", "" },
// { "HomePoorDesert3", "" },
// { "HomePoorDesert4", "" },
// { "HomePoorDesert5", "" },
//{ "HomePoorDesert6", "" },
{ "HomePoorDesert7", "Sand has covered some of the old structures." },
//{ "HomePoorDesert8", "" },
//{ "HomePoorDesert9", "" },
//---
//{ "HomePoorSwamp0", "" },
// { "HomePoorSwamp1", "" },
{ "HomePoorSwamp2", "This house is barely standing." },
{ "HomePoorSwamp3", "The soil looks spent." },
{ "HomePoorSwamp4", "The swampland smells preferable to this place." },
// { "HomePoorSwamp5", "" },
{ "HomePoorSwamp6", "The wood here is rotting." },
// { "HomePoorSwamp7", "" },
// { "HomePoorSwamp8", "" },
//{ "HomePoorSwamp9", "" },
//---
{ "HomePoorWoods0", "The forest is starting to swallow this place." },
//{ "HomePoorWoods1", "" },
{ "HomePoorWoods2", "The house looks broken down." },
//{ "HomePoorWoods3", "" },
{ "HomePoorWoods4", "The buildings look torn apart." },
{ "HomePoorWoods5", "There's a rotting stench." },
//{ "HomePoorWoods6", "" },
//{ "HomePoorWoods7", "" },
// { "HomePoorWoods8", "" },
// { "HomePoorWoods9", "" },
//---
{ "HomePoorMountains0", "The ground is rocky and uneven." },
//{ "HomePoorMountains1", "" },
//{ "HomePoorMountains2", "" },
// { "HomePoorMountains3", "" },
{ "HomePoorMountains4", "Only scavengers are seen near here." },
{ "HomePoorMountains5", "This place feels dreary." },
//{ "HomePoorMountains6", "" },
{ "HomePoorMountains7", "The wind relieves the smell." },
// { "HomePoorMountains8", "" },
//{ "HomePoorMountains9", "" },

//--- ---
//Player Ship Climates:
{ "HomeYourShipsOcean0", "The waves sound like a lullaby." },
{ "HomeYourShipsOcean1", "The water extends to the horizon." },
//{ "HomeYourShipsOcean2", "" },
{ "HomeYourShipsOcean3", "You can smell the water from here." },
{ "HomeYourShipsOcean4", "The ocean breeze moans \"Kelle\"." },
// { "HomeYourShipsOcean5", "" },
// { "HomeYourShipsOcean6", "" },
// { "HomeYourShipsOcean7", "" },
// { "HomeYourShipsOcean8", "" },
// { "HomeYourShipsOcean9", "" },

//--- ---
// Graveyard Climates:
{ "GraveyardDesert0", "Some bones are half buried in the sand." },
//{ "GraveyardDesert1", "" },
//{ "GraveyardDesert2", "" },
{ "GraveyardDesert3", "A vulture circles you in the sky." },
{ "GraveyardDesert4", "Sand has found its way into your gear." },
{ "GraveyardDesert5", "Shifting sands have toppled some gravestones." },
{ "GraveyardDesert6", "The tomb emits a humming sound." },
{ "GraveyardDesert7", "The smell makes your eyes water." },
{ "GraveyardDesert8", "There are some dried flowers buried in the sand." },
{ "GraveyardDesert9", "A religious symbol is scratched into the stone." },
//---
{ "GraveyardSwamp0", "Sounds are coming from the tomb." },
//{ "GraveyardSwamp1", "" },
{ "GraveyardSwamp2", "The vegetation has gone rancid." },
{ "GraveyardSwamp3", "It suddenly feels cold." },
{ "GraveyardSwamp4", "The mud seems to churn as you walk." },
{ "GraveyardSwamp5", "A gravestone is nearly buried." },
{ "GraveyardSwamp6", "There's a different kind of stench here." },
{ "GraveyardSwamp7", "Something was dragged through the mud." },
// { "GraveyardSwamp8", "" },
{ "GraveyardSwamp9", "An old symbol of the Gods has nearly vanished." },
//---
{ "GraveyardWoods0", "The trees around this site look diseased." },
{ "GraveyardWoods1", "The bugs near here sound sick." },
//{ "GraveyardWoods2", "" },
{ "GraveyardWoods3", "The tree nearest to you shakes." },
{ "GraveyardWoods4", "Birds have abandoned their nests." },
{ "GraveyardWoods5", "The roots have pushed over a gravestone." },
{ "GraveyardWoods6", "A wooden decoration has rotted." },
{ "GraveyardWoods7", "The tomb sends out a ringing sound." },
{ "GraveyardWoods8", "This religious marking is meant to protect the dead." },
{ "GraveyardWoods9", "You smell dirt and rotten flesh." },
//---
{ "GraveyardMountains0", "There are scratches on the rocks." },
{ "GraveyardMountains1", "Stones are used to decorate the graves." },
{ "GraveyardMountains2", "A noise echoes from the tomb." },
{ "GraveyardMountains3", "The ground here is discoloured." },
{ "GraveyardMountains4", "The mountain peaks loom over this place." },
{ "GraveyardMountains5", "Many believe those buried here are closer to the Gods." },
{ "GraveyardMountains6", "The wind eases the smell." },
{ "GraveyardMountains7", "A ritual was performed here." },
{ "GraveyardMountains8", "\"Here lies my only love\"." },
// { "GraveyardMountains9", "" },
//--- ---

//--- ---
// Coven Climates:
{ "CovenDesert0", "The beldam's presence is striking." },
{ "CovenDesert1", "Twisted patterns have formed in the sand." },
{ "CovenDesert2", "Some sort of energy melted the sand here." },
{ "CovenDesert3", "You smell strange ingredients." },
{ "CovenDesert4", "You feel pin pricks on your skin." },
// { "CovenDesert5", "" },
// { "CovenDesert6", "" },
// { "CovenDesert7", "" },
// { "CovenDesert8", "" },
// { "CovenDesert9", "" },
//---
{ "CovenSwamp0", "There are strange grooves in the mud." },
{ "CovenSwamp1", "The beldam stands facing you." },
{ "CovenSwamp2", "The smell stings your nose." },
{ "CovenSwamp3", "The bugs slink nearer." },
{ "CovenSwamp4", "Distant reptiles hiss and chatter." },
{ "CovenSwamp5", "There's an uncomfortable prickling sensation on your skin." },
// { "CovenSwamp6", "" },
// { "CovenSwamp7", "" },
// { "CovenSwamp8", "" },
// { "CovenSwamp9", "" },
//---
{ "CovenWoods0", "The trees seem to curl around you." },
{ "CovenWoods1", "The smell is trapped by the trees." },
{ "CovenWoods2", "You brush a spider off your leg." },
{ "CovenWoods3", "The beldam's eyes are hypnotizing." },
{ "CovenWoods4", "You sense pin pricks all over your skin." },
// { "CovenWoods5", "" },
// { "CovenWoods6", "" },
// { "CovenWoods7", "" },
// { "CovenWoods8", "" },
// { "CovenWoods9", "" },
//---
//{ "CovenMountains0", "" },
{ "CovenMountains1", "The beldam stares without blinking." },
{ "CovenMountains2", "Their chanting echoes in the hills." },
{ "CovenMountains3", "Not even the wind removes the smell." },
{ "CovenMountains4", "The rocks are decorated with bones." },
{ "CovenMountains5", "You feel a prickly sensation on your skin." },
// { "CovenMountains6", "" },
// { "CovenMountains7", "" },
// { "CovenMountains8", "" },
// { "CovenMountains9", "" },
//--- ---

//--- ---
// Temple Climates:
//{ "ReligionTempleDesert0", "" },
{ "ReligionTempleDesert1", "The temple is accepting visitors." },
{ "ReligionTempleDesert2", "A soft tingling can be felt on your skin." },
{ "ReligionTempleDesert3", "You feel a concentration of energy." },
{ "ReligionTempleDesert4", "Many believe donations confer benefits." },
{ "ReligionTempleDesert5", "Temples are said to offer cures, even to strangers." },
{ "ReligionTempleDesert6", "You smell ceremonial fire." },
{ "ReligionTempleDesert7", "Some lizards nest near the temple." },
//{ "ReligionTempleDesert8", "" },
{ "ReligionTempleDesert9", "The temple has resonated a pattern in the sand." },
//---
{ "ReligionTempleSwamp0", "Temple devotees place designs in the moss." },
{ "ReligionTempleSwamp1", "You can see people in the temple." },
{ "ReligionTempleSwamp2", "You feel a rush of energy." },
//{ "ReligionTempleSwamp3", "" },
{ "ReligionTempleSwamp4", "Donations help keep the temple clean." },
{ "ReligionTempleSwamp5", "If you are ill, the temple can provide aid." },
{ "ReligionTempleSwamp6", "Wildlife seems relaxed near the temple." },
{ "ReligionTempleSwamp7", "The dirt around the temple is forming a pattern." },
//{ "ReligionTempleSwamp8", "" },
{ "ReligionTempleSwamp9", "There's a slight tingling sensation on your skin." },
//---
{ "ReligionTempleWoods0", "There are religious markings on the trees." },
//{ "ReligionTempleWoods1", "" },
{ "ReligionTempleWoods2", "Woodland animals nest near the temple." },
{ "ReligionTempleWoods3", "Your skin tingles near the temple." },
{ "ReligionTempleWoods4", "Someone lights a candle in the temple." },
{ "ReligionTempleWoods5", "The donations from locals are put to good use." },
{ "ReligionTempleWoods6", "Temples are known to cure any who seek it." },
//{ "ReligionTempleWoods7", "" },
// { "ReligionTempleWoods8", "" },
{ "ReligionTempleWoods9", "You feel a swell of energy." },
//---
{ "ReligionTempleMountains0", "You feel a focus of energy." },
{ "ReligionTempleMountains1", "The rocks have religious markings." },
//{ "ReligionTempleMountains2", "" },
{ "ReligionTempleMountains3", "Someone just finished a prayer in the temple." },
{ "ReligionTempleMountains4", "Donations are accepted by members of the faith." },
{ "ReligionTempleMountains5", "Some believe the evergreens point to the Gods." },
{ "ReligionTempleMountains6", "You can cure an illness in the temple." },
{ "ReligionTempleMountains7", "Songbirds adorn the temple." },
{ "ReligionTempleMountains8", "You can feel your skin tingling slightly." },
// { "ReligionTempleMountains9", "" },
//--- ---

//--- ---
//Cult Climates:
{ "ReligionCultDesert0", "A discreet place to practice dark rituals." },
{ "ReligionCultDesert1", "Thick smoke pollutes the air." },
//{ "ReligionCultDesert2", "" },
{ "ReligionCultDesert3", "The building has been eroded by sand and wind." },
//{ "ReligionCultDesert4", "" },
{ "ReligionCultDesert5", "The air makes your skin itch." },
// { "ReligionCultDesert6", "" },
// { "ReligionCultDesert7", "" },
// { "ReligionCultDesert8", "" },
// { "ReligionCultDesert9", "" },
//---
{ "ReligionCultSwamp0", "Truely zealous devotees congregate here." },
{ "ReligionCultSwamp1", "The moss is creeping up the rocks." },
{ "ReligionCultSwamp2", "There's some discoloured smoke rising." },
{ "ReligionCultSwamp3", "Footprints litter the mud." },
{ "ReligionCultSwamp4", "You step on a bug you've never seen before." },
{ "ReligionCultSwamp5", "Your eyes are irritated by the stale air." },
// { "ReligionCultSwamp6", "" },
// { "ReligionCultSwamp7", "" },
// { "ReligionCultSwamp8", "" },
// { "ReligionCultSwamp9", "" },
//---
{ "ReligionCultWoods0", "A sickly smoke drifts nearby." },
{ "ReligionCultWoods1", "Strange plants grow here." },
//{ "ReligionCultWoods2", "" },
//{ "ReligionCultWoods3", "" },
{ "ReligionCultWoods4", "The air scratches your throat." },
{ "ReligionCultWoods5", "Pariahs are drawn to this place." },
// { "ReligionCultWoods6", "" },
// { "ReligionCultWoods7", "" },
// { "ReligionCultWoods8", "" },
// { "ReligionCultWoods9", "" },
//---
{ "ReligionCultMountains0", "Fanatics are intoxicated by supernatural power." },
//{ "ReligionCultMountains1", "" },
{ "ReligionCultMountains2", "Bug carcasses are scattered in a pattern." },
{ "ReligionCultMountains3", "The air has changed." },
{ "ReligionCultMountains4", "The ground rumbles slightly." },
{ "ReligionCultMountains5", "The smell sticks in your nose." },
// { "ReligionCultMountains6", "" },
// { "ReligionCultMountains7", "" },
// { "ReligionCultMountains8", "" },
// { "ReligionCultMountains9", "" },
//--- ---

//--- ---
// Dungeon Climates:
{ "DungeonLabyrinthDesert0", "A hot gust of wind burns your eyes." },
//{ "DungeonLabyrinthDesert1", "" },
{ "DungeonLabyrinthDesert2", "The sand covers countless dead." },
{ "DungeonLabyrinthDesert3", "The sand feels like molten blades." },
//{ "DungeonLabyrinthDesert4", "" },
{ "DungeonLabyrinthDesert5", "The air burns your throat." },
{ "DungeonLabyrinthDesert6", "The plants are spiked and tough." },
{ "DungeonLabyrinthDesert7", "A religious item is stained in blood." },
{ "DungeonLabyrinthDesert8", "Pray the desert consumes this place." },
//{ "DungeonLabyrinthDesert9", "" },
//---
{ "DungeonLabyrinthSwamp0", "The dirt near the dungeon is hissing." },
{ "DungeonLabyrinthSwamp1", "The wretched stench of death is powerful." },
//{ "DungeonLabyrinthSwamp2", "" },
//{ "DungeonLabyrinthSwamp3", "" },
{ "DungeonLabyrinthSwamp4", "Painful faces appear in the mud." },
{ "DungeonLabyrinthSwamp5", "Bugs try to burrow in your skin." },
{ "DungeonLabyrinthSwamp6", "The mud is a deep reddish brown." },
{ "DungeonLabyrinthSwamp7", "Your mouth fills with rot as you breathe." },
//{ "DungeonLabyrinthSwamp8", "" },
{ "DungeonLabyrinthSwamp9", "A body is mostly consumed by the mud." },
//---
{ "DungeonLabyrinthWoods0", "There are scratches on the trees." },
{ "DungeonLabyrinthWoods1", "The branches are twisted like hooks." },
{ "DungeonLabyrinthWoods2", "The trees creak and moan." },
{ "DungeonLabyrinthWoods3", "The roots have grown wild and gluttonous." },
//{ "DungeonLabyrinthWoods4", "" },
{ "DungeonLabyrinthWoods5", "The trees stab and slash at you." },
{ "DungeonLabyrinthWoods6", "Your nose bleeds from the harsh air." },
{ "DungeonLabyrinthWoods7", "You feel the suffering inflicted here." },
//{ "DungeonLabyrinthWoods8", "" },
{ "DungeonLabyrinthWoods9", "This area makes you nauseous." },
//---
//{ "DungeonLabyrinthMountains0", "" },
{ "DungeonLabyrinthMountains1", "Blood is shed on the rocks." },
{ "DungeonLabyrinthMountains2", "The bugs leech your blood." },
{ "DungeonLabyrinthMountains3", "The plants are dying." },
{ "DungeonLabyrinthMountains4", "Those marks aren't human." },
//{ "DungeonLabyrinthMountains5", "" },
{ "DungeonLabyrinthMountains6", "There are few capable of surviving this place." },
{ "DungeonLabyrinthMountains7", "The thin air is noxious and painful." },
{ "DungeonLabyrinthMountains8", "Your footsteps stir up a stench." },
//{ "DungeonLabyrinthMountains9", "" },
//--- ---

//--- ---
{ "DungeonKeepDesert0", "A vulture circles overhead." },
{ "DungeonKeepDesert1", "The sand rolls over some bones." },
//{ "DungeonKeepDesert2", "" },
//{ "DungeonKeepDesert3", "" },
{ "DungeonKeepDesert4", "A religious marking was drawn here as a warning." },
{ "DungeonKeepDesert5", "Beetles are crawling on the archways." },
{ "DungeonKeepDesert6", "The sand grinds your feet and burns you." },
{ "DungeonKeepDesert7", "The lingering smell infects your clothing." },
{ "DungeonKeepDesert8", "Bugs swarm your eyes and ears." },
{ "DungeonKeepDesert9", "Your skin is burned and scratched by the sand." },
//---
{ "DungeonKeepSwamp0", "The bugs seem to attack you." },
//{ "DungeonKeepSwamp1", "" },
{ "DungeonKeepSwamp2", "There seems to be a grave in the mud." },
{ "DungeonKeepSwamp3", "The moss around the entrance is dying." },
{ "DungeonKeepSwamp4", "You can smell the bloodshed." },
{ "DungeonKeepSwamp5", "Some hair is matted into the mud." },
{ "DungeonKeepSwamp6", "You taste the thick air as you breathe." },
{ "DungeonKeepSwamp7", "Your skin is itchy and irritated." },
//{ "DungeonKeepSwamp8", "" },
//{ "DungeonKeepSwamp9", "" },
//---
{ "DungeonKeepWoods0", "The leaves drip an oily substance." },
//{ "DungeonKeepWoods1", "" },
{ "DungeonKeepWoods2", "The trees are dead and dried out." },
{ "DungeonKeepWoods3", "The forest seems to whisper a warning." },
{ "DungeonKeepWoods4", "A religious relic has been desecrated." },
{ "DungeonKeepWoods5", "The woods twist around this place." },
{ "DungeonKeepWoods6", "The forest is playing tricks on you." },
{ "DungeonKeepWoods7", "A root seems to grab your foot." },
{ "DungeonKeepWoods8", "The stench in the air hurts your nose." },
{ "DungeonKeepWoods9", "Your eyes feel blurry and dry." },
//---
{ "DungeonKeepMountains0", "The plant life is sparse." },
{ "DungeonKeepMountains1", "Mountain stones are used to commemorate the dead." },
//{ "DungeonKeepMountains2", "" },
{ "DungeonKeepMountains3", "The trees direct the dead to the afterlife." },
//{ "DungeonKeepMountains4", "" },
{ "DungeonKeepMountains5", "Some magic was cast here." },
{ "DungeonKeepMountains6", "The rocks are grimy and cold to the touch." },
{ "DungeonKeepMountains7", "You can't get a full breath of air here." },
{ "DungeonKeepMountains8", "Something was killed here." },
{ "DungeonKeepMountains9", "Your head aches in this area." },
//--- ---

//--- ---
//{ "DungeonRuinDesert0", "" },
{ "DungeonRuinDesert1", "The sand is coarser than usual." },
{ "DungeonRuinDesert2", "The bugs scurry away as you approach." },
//{ "DungeonRuinDesert3", "" },
//{ "DungeonRuinDesert4", "" },
{ "DungeonRuinDesert5", "You can smell dried blood." },
//{ "DungeonRuinDesert6", "" },
{ "DungeonRuinDesert7", "There's an air current from the dungeon." },
{ "DungeonRuinDesert8", "The air irritates your throat" },
{ "DungeonRuinDesert9", "The doorway is worn and scuffed." },
//---
{ "DungeonRuinSwamp0", "Tracks lead into the dungeon." },
//{ "DungeonRuinSwamp1", "" },
//{ "DungeonRuinSwamp2", "" },
{ "DungeonRuinSwamp3", "You can hear the wildlife chatter." },
{ "DungeonRuinSwamp4", "The bugs are more aggressive." },
{ "DungeonRuinSwamp5", "Some moths rest near the entrance." },
//{ "DungeonRuinSwamp6", "" },
{ "DungeonRuinSwamp7", "The swamp air is particularly thick." },
//{ "DungeonRuinSwamp8", "" },
{ "DungeonRuinSwamp9", "This area makes your skin itch." },
//---
{ "DungeonRuinWoods0", "The lingering air is sour." },
//{ "DungeonRuinWoods1", "" },
{ "DungeonRuinWoods2", "The trees seem to reach for you." },
{ "DungeonRuinWoods3", "The bark is grimy." },
//{ "DungeonRuinWoods4", "" },
{ "DungeonRuinWoods5", "You can feel an air current from the dungeon." },
{ "DungeonRuinWoods6", "Some dust irritates your eyes." },
{ "DungeonRuinWoods7", "Wind rustles the leaves like a whisper." },
// { "DungeonRuinWoods8", "" },
// { "DungeonRuinWoods9", "" },
//---
{ "DungeonRuinMountains0", "Religious symbols are painted on the rocks." },
//{ "DungeonRuinMountains1", "" },
{ "DungeonRuinMountains2", "Only spiky grass grows easily here." },
//{ "DungeonRuinMountains3", "" },
{ "DungeonRuinMountains4", "There are footprints around the entrance." },
{ "DungeonRuinMountains5", "The breeze smells bitter." },
{ "DungeonRuinMountains6", "Your lungs strain in the thin air." },
//{ "DungeonRuinMountains7", "" },
{ "DungeonRuinMountains8", "Your eyes are strained and sore." },
{ "DungeonRuinMountains9", "The mountain peaks loom over you." },
//--- --- 


            #endregion

            #region Weather texts:

// Wilderness Weather:   189
//{ "NoneDayClear0", "" },
{ "NoneDayClear1", "You squint your eyes in the sun." },
{ "NoneDayClear2", "A beautiful day to travel." },
{ "NoneDayClear3", "You can feel the sun on your skin." },
//{ "NoneDayClear4", "" },
//---
{ "NoneNightClear0", "The stars are endless." },
{ "NoneNightClear1", "The tales of the Magna Ge come to mind." },
//{ "NoneNightClear2", "" },
{ "NoneNightClear3", "The moons remind you of Baar Dau." },
{ "NoneNightClear4", "Masser and Secunda dominate the sky." },
//---
{ "NoneDayCloudy0", "The cloud cover shields the suns rays." },
{ "NoneDayCloudy1", "Strong winds move the clouds." },
// { "NoneDayCloudy2", "" },
// { "NoneDayCloudy3", "" },
// { "NoneDayCloudy4", "" },
//---
//{ "NoneNightCloudy0", "" },
{ "NoneNightCloudy1", "The dark clouds cloak some movement." },
// { "NoneNightCloudy2", "" },
// { "NoneNightCloudy3", "" },
// { "NoneNightCloudy4", "" },
//---
{ "NoneDayRainy0", "A bug scurries out from under your footstep." },
//{ "NoneDayRainy1", "" },
{ "NoneDayRainy2", "The raindrops splash on your shoulder." },
// { "NoneDayRainy3", "" },
// { "NoneDayRainy4", "" },
//---
{ "NoneNightRainy0", "A miserable night for travel." },
{ "NoneNightRainy1", "You feel a cold stream down your back." },
{ "NoneNightRainy2", "The drops fall in a rhythm." },
// { "NoneNightRainy3", "" },
// { "NoneNightRainy4", "" },
//---
//{ "NoneDaySnowy0", "" },
{ "NoneDaySnowy1", "The crystalline snow shines in your eyes." },
{ "NoneDaySnowy2", "The cold wind stings your face." },
{ "NoneDaySnowy3", "You shake some snow off your head." },
// { "NoneDaySnowy4", "" },
//---
{ "NoneNightSnowy0", "Snowfall and darkness cover your tracks." },
{ "NoneNightSnowy1", "Your fingertips tingle in the cold." },
// { "NoneNightSnowy2", "" },
// { "NoneNightSnowy3", "" },
// { "NoneNightSnowy4", "" },

//--- ---
// City Weather:
//{ "TownCityDayClear0", "" },
{ "TownCityDayClear1", "The cityfolk are enjoying the sunshine." },
{ "TownCityDayClear2", "A fresh breeze flows around you." },
// { "TownCityDayClear3", "" },
// { "TownCityDayClear4", "" },
//---
{ "TownCityNightClear0", "You spot a cat sneaking around the corner." },
//{ "TownCityNightClear1", "" },
//{ "TownCityNightClear2", "" },
//{ "TownCityNightClear3", "" },
// { "TownCityNightClear4", "" },
//---
//{ "TownCityDayCloudy0", "" },
{ "TownCityDayCloudy1", "The cloudcover softens the daylight." },
//{ "TownCityDayCloudy2", "." },
// { "TownCityDayCloudy3", "" },
// { "TownCityDayCloudy4", "" },
//---
//{ "TownCityNightCloudy0", "" },
//{ "TownCityNightCloudy1", "" },
{ "TownCityNightCloudy2", "The streetlamps and windows light your path." },
//{ "TownCityNightCloudy3", "" },
// { "TownCityNightCloudy4", "" },
//---
{ "TownCityDayRainy0", "Your movement feels heavy in the damp air." },
{ "TownCityDayRainy1", "Cityfolk watch the rain from their windows." },
{ "TownCityDayRainy2", "Someone sighs, \"More miserable rain.\"." },
{ "TownCityDayRainy3", "Your foot splashes in a puddle." },
//{ "TownCityDayRainy4", "" },
//---
{ "TownCityNightRainy0", "The cityfolk shelter their belongings from the rain." },
{ "TownCityNightRainy1", "It sounds like someone is dealing with a leak." },
//{ "TownCityNightRainy2", "" },
// { "TownCityNightRainy3", "" },
// { "TownCityNightRainy4", "" },
//---
//{ "TownCityDaySnowy0", "" },
{ "TownCityDaySnowy1", "You smell roaring fires in the homes." },
{ "TownCityDaySnowy2", "The crunch of the snow is satisfying." },
// { "TownCityDaySnowy3", "" },
// { "TownCityDaySnowy4", "" },
//---
{ "TownCityNightSnowy0", "The days footprints are covered partially by snow." },
//{ "TownCityNightSnowy1", "" },
//{ "TownCityNightSnowy2", "" },
{ "TownCityNightSnowy3", "You can hear echoes in the still air." },
{ "TownCityNightSnowy4", "The crunchy snow is loud under your feet." },

//--- ---
// Hamlet Weather:
// { "TownHamletDayClear0", "" },
{ "TownHamletDayClear1", "The villagers are enjoying the sun." },
//{ "TownHamletDayClear2", "" },
// { "TownHamletDayClear3", "" },
// { "TownHamletDayClear4", "" },
//---
// { "TownHamletNightClear0", "" },
{ "TownHamletNightClear1", "A child peers through their window at the stars." },
//{ "TownHamletNightClear2", "" },
{ "TownHamletNightClear3", "The moonlight provides some illumination." },
//{ "TownHamletNightClear4", "" },
//---
{ "TownHamletDayCloudy0", "The clouds ease the suns rays." },
//{ "TownHamletDayCloudy1", "" },
//{ "TownHamletDayCloudy2", "" },
// { "TownHamletDayCloudy3", "" },
// { "TownHamletDayCloudy4", "" },
//---
{ "TownHamletNightCloudy0", "The clouds steal the moonlight." },
//{ "TownHamletNightCloudy1", "" },
// { "TownHamletNightCloudy2", "" },
// { "TownHamletNightCloudy3", "" },
// { "TownHamletNightCloudy4", "" },
//---
// { "TownHamletDayRainy0", "" },
//{ "TownHamletDayRainy1", "" },
{ "TownHamletDayRainy2", "Puddles are forming in the streets." },
{ "TownHamletDayRainy3", "People peer at you through their windows." },
//{ "TownHamletDayRainy4", "" },
//---
// { "TownHamletNightRainy0", "" },
{ "TownHamletNightRainy1", "A tavern will ease the gloom." },
{ "TownHamletNightRainy2", "The rain masks your footsteps." },
//{ "TownHamletNightRainy3", "" },
// { "TownHamletNightRainy4", "" },
//---
//{ "TownHamletDaySnowy0", "" },
{ "TownHamletDaySnowy1", "The villagers bundle their clothing for warmth." },
//{ "TownHamletDaySnowy2", "" },
{ "TownHamletDaySnowy3", "Someone has formed snow into the shape of a man." },
// { "TownHamletDaySnowy4", "" },
//---
//{ "TownHamletNightSnowy0", "" },
{ "TownHamletNightSnowy1", "The crunch of your footsteps echo off the houses." },
{ "TownHamletNightSnowy2", "The snow may soon cover everything in sight." },
{ "TownHamletNightSnowy3", "A horse shakes some snow off its head." },
// { "TownHamletNightSnowy4", "" },

//--- ---
// Village Weather:
{ "TownVillageDayClear0", "The birds sing and flutter." },
{ "TownVillageDayClear1", "The sunlight warms your shoulders." },
//{ "TownVillageDayClear2", "" },
//{ "TownVillageDayClear3", "" },
//{ "TownVillageDayClear4", "" },
//---
//{ "TownVillageNightClear0", "" },
{ "TownVillageNightClear1", "Villagers gaze at the constellations from their windows." },
// { "TownVillageNightClear2", "" },
// { "TownVillageNightClear3", "" },
// { "TownVillageNightClear4", "" },
//---
{ "TownVillageDayCloudy0", "The clouds shield you from the sun." },
//{ "TownVillageDayCloudy1", "" },
//{ "TownVillageDayCloudy2", "" },
//{ "TownVillageDayCloudy3", "" },
//{ "TownVillageDayCloudy4", "" },
//---
{ "TownVillageNightCloudy0", "You hear some soft chatter in the homes." },
//{ "TownVillageNightCloudy1", "" },
{ "TownVillageNightCloudy2", "The sparse light helps you navigate the streets." },
// { "TownVillageNightCloudy3", "" },
// { "TownVillageNightCloudy4", "" },
//---
{ "TownVillageDayRainy0", "Many of the locals are keeping out of the rain." },
{ "TownVillageDayRainy1", "Puddles have formed in the streets." },
// { "TownVillageDayRainy2", "" },
// { "TownVillageDayRainy3", "" },
// { "TownVillageDayRainy4", "" },
//---
{ "TownVillageNightRainy0", "The rain taps on the rooftops." },
{ "TownVillageNightRainy1", "Your toe splashes in a puddle." },
// { "TownVillageNightRainy2", "" },
// { "TownVillageNightRainy3", "" },
// { "TownVillageNightRainy4", "" },
//---
{ "TownVillageDaySnowy0", "Snowflakes rest on your shoulder." },
{ "TownVillageDaySnowy1", "The locals help each other clear the snow." },
//{ "TownVillageDaySnowy2", "" },
//{ "TownVillageDaySnowy3", "" },
//{ "TownVillageDaySnowy4", "" },
//---
{ "TownVillageNightSnowy0", "The snow crunches underfoot." },
//{ "TownVillageNightSnowy1", "" },
{ "TownVillageNightSnowy2", "The snow may bury this whole town." },
// { "TownVillageNightSnowy3", "" },
// { "TownVillageNightSnowy4", "" },

//--- ---
// Dungeon Weather:
{ "DungeonLabyrinthDayClear0", "The sun can't cleanse a place so evil." },
{ "DungeonLabyrinthDayClear1", "The Gods weep at the sight of this place." },
{ "DungeonLabyrinthDayClear2", "The plantlife is singed by the sun." },
{ "DungeonLabyrinthDayClear3", "The daylight reveals blood stains." },
// { "DungeonLabyrinthDayClear4", "" },
//---
{ "DungeonLabyrinthNightClear0", "The moonlight casts sinister shadows." },
//{ "DungeonLabyrinthNightClear1", "" },
// { "DungeonLabyrinthNightClear2", "" },
// { "DungeonLabyrinthNightClear3", "" },
// { "DungeonLabyrinthNightClear4", "" },
//---
{ "DungeonLabyrinthDayCloudy0", "Stale air bursts forth like a breath." },
//{ "DungeonLabyrinthDayCloudy1", "" },
{ "DungeonLabyrinthDayCloudy2", "The clouds billow and writhe." },
// { "DungeonLabyrinthDayCloudy3", "" },
// { "DungeonLabyrinthDayCloudy4", "" },
//---
{ "DungeonLabyrinthNightCloudy0", "Little moonlight falls on this hellish place." },
{ "DungeonLabyrinthNightCloudy1", "Cloud cover cloaks the dead." },
{ "DungeonLabyrinthNightCloudy2", "Darkness breaches the edges of your vision." },
// { "DungeonLabyrinthNightCloudy3", "" },
// { "DungeonLabyrinthNightCloudy4", "" },
//---
{ "DungeonLabyrinthDayRainy0", "The rain can't wash away the filth." },
{ "DungeonLabyrinthDayRainy1", "The puddles are filled with blood." },
{ "DungeonLabyrinthDayRainy2", "The rain intensifies the stench." },
// { "DungeonLabyrinthDayRainy3", "" },
// { "DungeonLabyrinthDayRainy4", "" },
//---
{ "DungeonLabyrinthNightRainy0", "The rain stings your eyes." },
{ "DungeonLabyrinthNightRainy1", "The puddles are bloody." },
// { "DungeonLabyrinthNightRainy2", "" },
//{ "DungeonLabyrinthNightRainy3", "" },
// { "DungeonLabyrinthNightRainy4", "" },
//---
//{ "DungeonLabyrinthDaySnowy0", "" },
{ "DungeonLabyrinthDaySnowy1", "You can just make out dead figures under the snow." },
{ "DungeonLabyrinthDaySnowy2", "Twisted shapes form in the dirty snow." },
{ "DungeonLabyrinthDaySnowy3", "The glare off the snow seeks to blind you." },
{ "DungeonLabyrinthDaySnowy4", "The cold stings your skin." },
//---
{ "DungeonLabyrinthNightSnowy0", "The snow crunches like glass as you move." },
{ "DungeonLabyrinthNightSnowy1", "A shiver runs up your back." },
//{ "DungeonLabyrinthNightSnowy2", "" },
{ "DungeonLabyrinthNightSnowy3", "The cold, sharp air hurts to breathe." },
//{ "DungeonLabyrinthNightSnowy4", "" },

//--- ---
{ "DungeonKeepDayClear0", "The day darkens near here." },
{ "DungeonKeepDayClear1", "The suns rays fall onto this dreary place." },
{ "DungeonKeepDayClear2", "The plantlife is desiccated by the sun." },
// { "DungeonKeepDayClear3", "" },
// { "DungeonKeepDayClear4", "" },
//---
{ "DungeonKeepNightClear0", "The stars offer a warning of this place." },
{ "DungeonKeepNightClear1", "Eery moonlight illuminates the area." },
// { "DungeonKeepNightClear2", "" },
// { "DungeonKeepNightClear3", "" },
// { "DungeonKeepNightClear4", "" },
//---
{ "DungeonKeepDayCloudy0", "You can smell rotting flesh." },
{ "DungeonKeepDayCloudy1", "The clouds twist above the dungeon." },
// { "DungeonKeepDayCloudy2", "" },
// { "DungeonKeepDayCloudy3", "" },
// { "DungeonKeepDayCloudy4", "" },
//---
{ "DungeonKeepNightCloudy0", "The damp air is sickly." },
{ "DungeonKeepNightCloudy1", "Sounds echo and turn sinister." },
// { "DungeonKeepNightCloudy2", "" },
// { "DungeonKeepNightCloudy3", "" },
// { "DungeonKeepNightCloudy4", "" },
//---
{ "DungeonKeepDayRainy0", "The rain smells like the dead." },
{ "DungeonKeepDayRainy1", "The rain feels heavy and grimy." },
{ "DungeonKeepDayRainy2", "A bleak day to tread these grounds." },
// { "DungeonKeepDayRainy3", "" },
// { "DungeonKeepDayRainy4", "" },
//---
{ "DungeonKeepNightRainy0", "The rain is preferable to this place." },
{ "DungeonKeepNightRainy1", "Steam rises off the ground near the dungeon." },
{ "DungeonKeepNightRainy2", "The rain tastes foul." },
{ "DungeonKeepNightRainy3", "You soak your foot in a filthy puddle." },
// { "DungeonKeepNightRainy4", "" },
//---
//{ "DungeonKeepDaySnowy0", "" },
{ "DungeonKeepDaySnowy1", "The daylight shimmers off the snow and stings your eyes." },
{ "DungeonKeepDaySnowy2", "Large footprints litter the snow." },
// { "DungeonKeepDaySnowy3", "" },
// { "DungeonKeepDaySnowy4", "" },
//---
{ "DungeonKeepNightSnowy0", "The entrance may get snowed in." },
{ "DungeonKeepNightSnowy1", "The cold air from the dungeon is oppressive." },
//{ "DungeonKeepNightSnowy2", "" },
// { "DungeonKeepNightSnowy3", "" },
// { "DungeonKeepNightSnowy4", "" },

//--- ---
{ "DungeonRuinDayClear0", "The plantlife looks harmed by the sun." },
{ "DungeonRuinDayClear1", "The light of the Gods shines on this sad place." },
// { "DungeonRuinDayClear2", "" },
// { "DungeonRuinDayClear3", "" },
// { "DungeonRuinDayClear4", "" },
//---
//{ "DungeonRuinNightClear0", "" },
{ "DungeonRuinNightClear1", "A dark figure scampers away." },
// { "DungeonRuinNightClear2", "" },
// { "DungeonRuinNightClear3", "" },
// { "DungeonRuinNightClear4", "" },
//---
{ "DungeonRuinDayCloudy0", "The wind wrestles you as you move." },
{ "DungeonRuinDayCloudy1", "The clouds form a weird pattern." },
// { "DungeonRuinDayCloudy2", "" },
// { "DungeonRuinDayCloudy3", "" },
// { "DungeonRuinDayCloudy4", "" },
//---
{ "DungeonRuinNightCloudy0", "The air around the dungeon has a fine mist." },
{ "DungeonRuinNightCloudy1", "The clouds look discoloured." },
// { "DungeonRuinNightCloudy2", "" },
// { "DungeonRuinNightCloudy3", "" },
// { "DungeonRuinNightCloudy4", "" },
//---
{ "DungeonRuinDayRainy0", "The rain is rather stale." },
//{ "DungeonRuinDayRainy1", "" },
{ "DungeonRuinDayRainy2", "The drops are heavy on your shoulder." },
// { "DungeonRuinDayRainy3", "" },
// { "DungeonRuinDayRainy4", "" },
//---
{ "DungeonRuinNightRainy0", "The rain tastes a little foul." },
{ "DungeonRuinNightRainy1", "The drops seem to be tapping your shoulder." },
{ "DungeonRuinNightRainy2", "The puddles are greasy." },
// { "DungeonRuinNightRainy3", "" },
// { "DungeonRuinNightRainy4", "" },
//---
//{ "DungeonRuinDaySnowy0", "" },
{ "DungeonRuinDaySnowy1", "The snow covers some animal tracks." },
// { "DungeonRuinDaySnowy2", "" },
// { "DungeonRuinDaySnowy3", "" },
// { "DungeonRuinDaySnowy4", "" },
//---
//{ "DungeonRuinNightSnowy0", "" },
{ "DungeonRuinNightSnowy1", "A spell disrupted the snow here." },
// { "DungeonRuinNightSnowy2", "" },
// { "DungeonRuinNightSnowy3", "" },
// { "DungeonRuinNightSnowy4", "" },

//--- ---
// Graveyard Weather:
{ "GraveyardDayClear0", "The plantlife is agitated by the sun." },
{ "GraveyardDayClear1", "There seem to be faces in the plantgrowth." },
// { "GraveyardDayClear2", "" },
// { "GraveyardDayClear3", "" },
// { "GraveyardDayClear4", "" },
//---
{ "GraveyardNightClear0", "The heavens guide the dead." },
//{ "GraveyardNightClear1", "" },
//{ "GraveyardNightClear2", "" },
// { "GraveyardNightClear3", "" },
// { "GraveyardNightClear4", "" },
//---
{ "GraveyardDayCloudy0", "The locals say spirits can be seen in the morning fog." },
{ "GraveyardDayCloudy1", "Shadows move above the clouds." },
// { "GraveyardDayCloudy2", "" },
// { "GraveyardDayCloudy3", "" },
// { "GraveyardDayCloudy4", "" },
//---
{ "GraveyardNightCloudy0", "You smell a rotten stench." },
{ "GraveyardNightCloudy1", "The clouds have picked up speed." },
// { "GraveyardNightCloudy2", "" },
// { "GraveyardNightCloudy3", "" },
// { "GraveyardNightCloudy4", "" },
//---
{ "GraveyardDayRainy0", "Worms are writhing near you." },
{ "GraveyardDayRainy1", "Years of rainfall has eroded the gravestones." },
// { "GraveyardDayRainy2", "" },
// { "GraveyardDayRainy3", "" },
// { "GraveyardDayRainy4", "" },
//---
{ "GraveyardNightRainy0", "Stale water drips in your eyes." },
{ "GraveyardNightRainy1", "Some of the raindrops sizzle on the hedgerows." },
//{ "GraveyardNightRainy2", "" },
// { "GraveyardNightRainy3", "" },
// { "GraveyardNightRainy4", "" },
//---
{ "GraveyardDaySnowy0", "A shiver runs up your back." },
{ "GraveyardDaySnowy1", "There is some melting snow over a grave." },
// { "GraveyardDaySnowy2", "" },
// { "GraveyardDaySnowy3", "" },
// { "GraveyardDaySnowy4", "" },
//---
{ "GraveyardNightSnowy0", "The wind is colder than usual." },
{ "GraveyardNightSnowy1", "There are strange footsteps in the snow." },
// { "GraveyardNightSnowy2", "" },
// { "GraveyardNightSnowy3", "" },
// { "GraveyardNightSnowy4", "" },
//--- ---

//Temple Weather:
{ "ReligionTempleDayClear9", "Worshippers thank the Gods for the clear sky." },
{ "ReligionTempleNightClear9", "The heavens feel more empyreal here." },
{ "ReligionTempleDayCloudy0", "Worshippers thank the Gods for the clouds." },
{ "ReligionTempleNightCloudy0", "Calming figures form in the clouds." },
{ "ReligionTempleDayRainy0", "Worshippers thank the Gods for the rain." },
{ "ReligionTempleNightRainy0", "The rain seems to sparkle as it falls." },
{ "ReligionTempleDaySnowy0", "Worshippers thank the Gods for the snow." },
{ "ReligionTempleNightSnowy0", "The snowflakes are guided softly." },
//--- ---

//Coven Weather:
//{ "CovenDayClear9", "" },
{ "CovenNightClear9", "The stars seem to be watching." },
{ "CovenDayCloudy0", "The clouds churn and writhe." },
{ "CovenNightCloudy0", "The clouds seethe with your movement." },
{ "CovenDayRainy0", "The rain is acrid." },
{ "CovenNightRainy0", "The rain is caustic." },
{ "CovenDaySnowy0", "The snow isn't cold." },
{ "CovenNightSnowy0", "The snow stings as it lands." },
//--- ---

//ReligionCult Weather:
//{ "ReligionCultDayClear9", "" },
{ "ReligionCultNightClear9", "Obscure stars twinkle at you." },
{ "ReligionCultDayCloudy0", "The clouds swell erratically." },
{ "ReligionCultNightCloudy0", "The clouds heave with your movement." },
{ "ReligionCultDayRainy0", "The raindrops sizzle on the mound." },
{ "ReligionCultNightRainy0", "The rain is grainy." },
{ "ReligionCultDaySnowy0", "The snowflakes are contorted." },
{ "ReligionCultNightSnowy0", "The snow is sharp to the touch." },
//--- ---

//HomeFarms Weather:
{ "HomeFarmsDayClear9", "The crops indulge in Magnus' light." },
{ "HomeFarmsNightClear9", "Celestial verve invigorates the soil." },
//{ "HomeFarmsDayCloudy0", "" },
//{ "HomeFarmsNightCloudy0", "" },
{ "HomeFarmsDayRainy0", "The farmers pray for more sun." },
{ "HomeFarmsNightRainy0", "The soothing rain nourishes the soil." },
{ "HomeFarmsDaySnowy0", "The workers prepare for the first seed." },
{ "HomeFarmsNightSnowy0", "An ethereal presence preserves the soil." },
//--- ---

//HomeYourShips Weather:
{ "HomeYourShipsDayClear9", "The light shimmers off the water." },
{ "HomeYourShipsNightClear9", "The expanse of the heavens is wondrous." },
//{ "HomeYourShipsDayCloudy0", "" },
//{ "HomeYourShipsNightCloudy0", "" },
{ "HomeYourShipsDayRainy0", "The rain taps the deck in a rhythm." },
{ "HomeYourShipsNightRainy0", "The rain makes the sails hang heavy." },
{ "HomeYourShipsDaySnowy0", "The snow makes the deck slick." },
{ "HomeYourShipsNightSnowy0", "The snow builds on the deck." },
//--- ---

//Tavern Weather:
{ "TavernDayClear9", "Some bleary-eyed patrons squint in the sun." },
{ "TavernNightClear9", "You hear a toast to the heavens." },
//{ "TavernDayCloudy0", "" },
//{ "TavernNightCloudy0", "" },
{ "TavernDayRainy0", "The tavern provides relief from the rain." },
{ "TavernNightRainy0", "You can hear the raucous patrons through the rain." },
{ "TavernDaySnowy0", "The tavern's hearth warms many travellers." },
{ "TavernNightSnowy0", "The patrons' commotion pierces the cold, still air." },
//--- ---

//HomeWealthy Weather:
{ "HomeWealthyDayClear9", "The sun shines on polished metals." },
{ "HomeWealthyNightClear9", "The heavens glint off polished metals." },
//{ "HomeWealthyDayCloudy0", "" },
//{ "HomeWealthyNightCloudy0", "" },
{ "HomeWealthyDayRainy0", "The scintillating rain taps a rhythm." },
{ "HomeWealthyNightRainy0", "The ambient light shimmers in the puddles." },
{ "HomeWealthyDaySnowy0", "The snow is kept clear by the attendants." },
{ "HomeWealthyNightSnowy0", "You can smell the crackling fireplaces." },
//--- ---

//HomePoor Weather:
//{ "HomePoorDayClear9", "" },
{ "HomePoorNightClear9", "You hear a despaired prayer to the heavens." },
//{ "HomePoorDayCloudy0", "" },
{ "HomePoorNightCloudy0", "Dreary clouds shroud this bleak place." },
{ "HomePoorDayRainy0", "The rain pools around the house." },
{ "HomePoorNightRainy0", "Filthy puddles soak your feet." },
{ "HomePoorDaySnowy0", "The snow around the house seems dirty." },
{ "HomePoorNightSnowy0", "A frigid breeze rattles the windowpanes." },
//--- ---

            #endregion

            #region Day / Night texts:


// Wilderness Day/Night: 141
{ "NoneDay0", "Magnus imbues the land with magicka." },
//{ "NoneDay1", "" },
//{ "NoneDay2", "" },
//{ "NoneDay3", "" },
//{ "NoneDay4", "" },
//{ "NoneDay5", "" },
//{ "NoneDay6", "" },
//{ "NoneDay7", "" },
//{ "NoneDay8", "" },
//{ "NoneDay9", "" },
//---
{ "NoneNight0", "The bugs chirp a rhythm." },
//{ "NoneNight1", "" },
//{ "NoneNight2", "" },
//{ "NoneNight3", "" },
//{ "NoneNight4", "" },
//{ "NoneNight5", "" },
//{ "NoneNight6", "" },
//{ "NoneNight7", "" },
//{ "NoneNight8", "" },
//{ "NoneNight9", "" },
//--- ---
// City Day/Night:
{ "TownCityDay0", "You hear some neighbours arguing." },
{ "TownCityDay1", "You smell some freshly chopped wood." },
{ "TownCityDay2", "You catch the scent of a warm meal." },
//{ "TownCityDay3", "" },
{ "TownCityDay4", "Someone is playing a tune." },
//{ "TownCityDay5", "" },
//{ "TownCityDay6", "" },
//{ "TownCityDay7", "" },
//{ "TownCityDay8", "" },
//{ "TownCityDay9", "" },
//---
{ "TownCityNight0", "You smell the smoke of a fireplace." },
{ "TownCityNight1", "Someone is humming a tune." },
//{ "TownCityNight2", "" },
//{ "TownCityNight3", "" },
{ "TownCityNight4", "You hear some laughter in a house." },
{ "TownCityNight5", "You can hear some drunken patrons." },
{ "TownCityNight6", "Someone is snoring loudly." },
{ "TownCityNight7", "You smell some ale on the breeze." },
// { "TownCityNight8", "" },
// { "TownCityNight9", "" },
//--- ---
// Hamlet Day/Night:
{ "TownHamletDay0", "Some herbs are being smoked." },
{ "TownHamletDay1", "Someone is chopping wood." },
//{ "TownHamletDay2", "" },
{ "TownHamletDay3", "A waft of exciting spices finds your nose." },
// { "TownHamletDay4", "" },
//{ "TownHamletDay5", "" },
// { "TownHamletDay6", "" },
//{ "TownHamletDay7", "" },
//{ "TownHamletDay8", "" },
//{ "TownHamletDay9", "" },
//---
//{ "TownHamletNight0", "" },
{ "TownHamletNight1", "Someone is smoking something." },
{ "TownHamletNight2", "The homes are filled with life and laughter." },
//{ "TownHamletNight3", "" },
{ "TownHamletNight4", "You hear some restless animals." },
{ "TownHamletNight5", "A cat scurries after a rodent." },
//{ "TownHamletNight6", "" },
// { "TownHamletNight7", "" },
// { "TownHamletNight8", "" },
//{ "TownHamletNight9", "" },
//--- ---
// Village Day/Night:
//{ "TownVillageDay0", "" },
{ "TownVillageDay1", "Someone calls for a dog in the distance." },
//{ "TownVillageDay2", "" },
{ "TownVillageDay3", "The smell of fresh bread fills the air." },
{ "TownVillageDay4", "A local is chopping firewood." },
{ "TownVillageDay5", "Someone is smoking some meat." },
{ "TownVillageDay6", "Some neighbours are laughing together." },
//{ "TownVillageDay7", "" },
//{ "TownVillageDay8", "" },
//{ "TownVillageDay9", "" },
//---
{ "TownVillageNight0", "A pig has gotten into some cabbages." },
//{ "TownVillageNight1", "" },
{ "TownVillageNight2", "You can hear a fireplace crackling." },
{ "TownVillageNight3", "The street lights bounce off the homes." },
//{ "TownVillageNight4", "" },
//{ "TownVillageNight5", "" },
//{ "TownVillageNight6", "" },
//{ "TownVillageNight7", "" },
//{ "TownVillageNight8", "" },
//{ "TownVillageNight9", "" },
//--- ---
// Tavern Day/Night:
//{ "TavernDay0", "" },
{ "TavernDay1", "A plate is smashed, followed by laughter." },
{ "TavernDay2", "Many of the residents are tavern workers." },
//{ "TavernDay3", "" },
//{ "TavernDay4", "" },
//{ "TavernDay5", "" },
//{ "TavernDay6", "" },
//{ "TavernDay7", "" },
{ "TavernDay8", "A drunkard thinks he's your friend." },
//---
//{ "TavernNight0", "" },
{ "TavernNight1", "You hear the patrons bellowing a tune." },
{ "TavernNight2", "You pass a questionable puddle." },
{ "TavernNight3", "You can smell the fire, feast and foam." },
//{ "TavernNight4", "" },
{ "TavernNight5", "Someone was passed out here recently." },
//{ "TavernNight6", "" },
{ "TavernNight7", "It sounds like a fight has broken out." },
//--- ---
// Farms Day/Night:
//{ "HomeFarmsDay0", "" },
{ "HomeFarmsDay1", "The air is a mix of scents." },
//{ "HomeFarmsDay2", "" },
{ "HomeFarmsDay3", "The animals make their presence known." },
{ "HomeFarmsDay4", "A slight breeze sways the crops." },
{ "HomeFarmsDay5", "You see some wagon tracks here." },
{ "HomeFarmsDay6", "One of the workers is jealous of his friend's new hoe." },
//---
{ "HomeFarmsNight0", "There are some decomposing vegetables nearby." },
//{ "HomeFarmsNight1", "" },
{ "HomeFarmsNight2", "The animals are settling down." },
//{ "HomeFarmsNight3", "" },
//{ "HomeFarmsNight4", "" },
//--- ---
// WealthyHomes Day/Night:
//{ "HomeWealthyDay0", "" },
//{ "HomeWealthyDay1", "" },
{ "HomeWealthyDay2", "A silver caraff is being used as a flower pot." },
{ "HomeWealthyDay3", "You see fine fabrics with ornate buckles." },
// { "HomeWealthyDay4", "" },
//{ "HomeWealthyDay5", "" },
{ "HomeWealthyDay6", "Workers tend to the gardens." },
{ "HomeWealthyDay7", "The animals are well kept." },
{ "HomeWealthyDay8", "You spot a young woman wearing nordic silk." },
//{ "HomeWealthyDay9", "" },
//---
//{ "HomeWealthyNight0", "" },
{ "HomeWealthyNight1", "You hear the fireplaces crackling." },
//{ "HomeWealthyNight2", "" },
//{ "HomeWealthyNight3", "" },
//{ "HomeWealthyNight4", "" },
//{ "HomeWealthyNight5", "" },
//--- ---
// PoorHomes Day/Night:
//{ "HomePoorDay0", "" },
{ "HomePoorDay1", "You watch your step among the droppings." },
{ "HomePoorDay2", "Someone is coughing." },
//{ "HomePoorDay3", "" },
{ "HomePoorDay4", "You make out an unused wagon trail." },
{ "HomePoorDay5", "There's garbage strewn about." },
{ "HomePoorDay6", "Holes in the roof are roughly patched." },
// { "HomePoorDay7", "" },
// { "HomePoorDay8", "" },
// { "HomePoorDay9", "" },
//---
{ "HomePoorNight0", "A sneeze can be heard from the house." },
{ "HomePoorNight1", "Something smells bad." },
{ "HomePoorNight2", "Some rodents squeak and scatter." },
{ "HomePoorNight3", "You think something was buried here." },
{ "HomePoorNight4", "You hear someone crying." },
//--- ---
// PlayerShip Day/Night:
//{ "HomeYourShipsDay0", "" },
{ "HomeYourShipsDay1", "You hear the wind whipping the sails." },
// { "HomeYourShipsDay2", "" },
// { "HomeYourShipsDay3", "" },
// { "HomeYourShipsDay4", "" },
//---
//{ "HomeYourShipsNight0", "" },
// { "HomeYourShipsNight1", "" },
{ "HomeYourShipsNight2", "The sails flap lazily in the breeze." },
// { "HomeYourShipsNight3", "" },
// { "HomeYourShipsNight4", "" },
//--- ---
// Graveyard Day/Night:
{ "GraveyardDay0", "Some decorations wilt on a gravestone." },
{ "GraveyardDay1", "A makeshift grave was dug here." },
{ "GraveyardDay2", "Something was digging here." },
{ "GraveyardDay3", "This engraving is from ages ago." },
{ "GraveyardDay4", "One of the graves has some fresh turned earth." },
//---
{ "GraveyardNight0", "Some fresh flowers rest on a grave." },
{ "GraveyardNight1", "Something is making a thumping noise." },
//{ "GraveyardNight2", "" },
{ "GraveyardNight3", "Pray the dead stay dead." },
{ "GraveyardNight4", "You feel as if you aren't alone." },
//--- ---
// Coven Day/Night:
{ "CovenDay0", "You smell a bubbling pot." },
{ "CovenDay1", "Some potions are stashed out of the light." },
{ "CovenDay2", "They stare at you." },
{ "CovenDay3", "\"The Stricture\" can be read on a piece of parchment." },
{ "CovenDay4", "Access to great power can be obtained here." },
{ "CovenDay5", "A thin smoke rises." },
// { "CovenDay6", "" },
// { "CovenDay7", "" },
// { "CovenDay8", "" },
//---
{ "CovenNight0", "A strange shadow drifts away." },
{ "CovenNight1", "A dark energy lingers here." },
{ "CovenNight2", "Potions glow faintly under some cloth." },
{ "CovenNight3", "Ancient rituals disturb the locals." },
{ "CovenNight4", "A witch has succumbed to a trance." },
{ "CovenNight5", "They speak not, but you hear." },
{ "CovenNight6", "An arrid smoke lingers." },
{ "CovenNight7", "You see someone when you close your eyes" },
// { "CovenNight8", "" },
//--- ---
// Temple Day/Night:
{ "ReligionTempleDay0", "The residents recite religious texts." },
{ "ReligionTempleDay1", "Some devotees are wearing ceremonial garb." },
{ "ReligionTempleDay2", "An elder blesses your path." },
{ "ReligionTempleDay3", "A young pilgrim gestures to the sky." },
{ "ReligionTempleDay4", "A beggar receives some aid." },
{ "ReligionTempleDay5", "Some chimes signal a prayer." },
{ "ReligionTempleDay6", "People speak softly near the temple." },
{ "ReligionTempleDay7", "An elder is reading a holy book." },
{ "ReligionTempleDay8", "The worshippers seem to float as they walk." },
{ "ReligionTempleDay9", "A pilgrim is stitching some religious attire." },
//---
{ "ReligionTempleNight0", "A pipe is being smoked." },
{ "ReligionTempleNight1", "You hear people praying." },
{ "ReligionTempleNight2", "The windows have religious markings." },
{ "ReligionTempleNight3", "You hear laughter from the houses." },
{ "ReligionTempleNight4", "There is a tranquil ambiance." },
{ "ReligionTempleNight5", "Chanting can be heard \"Obey your Emperor\"." },
{ "ReligionTempleNight6", "Chanting can be heard \"Study the Covenants\"." },
{ "ReligionTempleNight7", "Chanting can be heard \"Worship the Eight\"." },
{ "ReligionTempleNight8", "Chanting can be heard \"Do your duty\"." },
{ "ReligionTempleNight9", "Chanting can be heard \"Heed the commands of the Saints and Priests\"." },
//--- ---
// Cult Day/Night:
{ "ReligionCultDay0", "The day illuminates all deeds." },
{ "ReligionCultDay1", "Special herbs are being burned." },
{ "ReligionCultDay2", "The years have aged this place." },
{ "ReligionCultDay3", "You hear profane chanting." },
{ "ReligionCultDay4", "This building is contorted." },
//---
{ "ReligionCultNight0", "A low humming can be heard." },
{ "ReligionCultNight1", "An unusual smell lingers in the air." },
{ "ReligionCultNight2", "Many voices stop at once." },
{ "ReligionCultNight3", "A distant laugh echoes past." },
{ "ReligionCultNight4", "A blade is being sharpened." },
//--- ---
// Dungeon Day/Night:
//{ "DungeonLabyrinthDay0", "" },
{ "DungeonLabyrinthDay1", "There are shreds of a cloak on the ground." },
{ "DungeonLabyrinthDay2", "Scraps of metal and bone are everywhere." },
{ "DungeonLabyrinthDay3", "A warning is scratched onto the entrance." },
{ "DungeonLabyrinthDay4", "A religious marking has been corrupted." },
//{ "DungeonLabyrinthDay5", "" },
{ "DungeonLabyrinthDay6", "Many travellers have fallen here." },
{ "DungeonLabyrinthDay7", "You feel a strange draw to the dungeon entrance." },
//{ "DungeonLabyrinthDay8", "" },
//{ "DungeonLabyrinthDay9", "" },
//---
{ "DungeonLabyrinthNight0", "You feel bones underfoot." },
{ "DungeonLabyrinthNight1", "Ghostly warnings haunt your ears." },
//{ "DungeonLabyrinthNight2", "" },
{ "DungeonLabyrinthNight3", "The forces of evil lurk here." },
{ "DungeonLabyrinthNight4", "Lights dim in this area." },
//{ "DungeonLabyrinthNight5", "" },
// { "DungeonLabyrinthNight6", "" },
//{ "DungeonLabyrinthNight7", "" },
{ "DungeonLabyrinthNight8", "The entrance is shrouded in darkness." },
// { "DungeonLabyrinthNight9", "" },
//--- ---

//{ "DungeonKeepDay0", "" },
//{ "DungeonKeepDay1", "" },
{ "DungeonKeepDay2", "There are some tracks leading into the dungeon." },
//{ "DungeonKeepDay3", "" },
{ "DungeonKeepDay4", "Blood was spilled recently." },
{ "DungeonKeepDay5", "A tribute was left for the dead." },
{ "DungeonKeepDay6", "Something big was dragged away from here." },
//{ "DungeonKeepDay7", "" },
{ "DungeonKeepDay8", "There is a great sadness here." },
{ "DungeonKeepDay9", "An inscription reads \"may the Gods protect you\"." },
//---
//{ "DungeonKeepNight0", "" },
//{ "DungeonKeepNight1", "" },
{ "DungeonKeepNight2", "The air is deadly still." },
{ "DungeonKeepNight3", "You feel watched." },
{ "DungeonKeepNight4", "Bugs call out a warning." },
//{ "DungeonKeepNight5", "" },
//{ "DungeonKeepNight6", "" },
{ "DungeonKeepNight7", "The darkness hides the entrance." },
// { "DungeonKeepNight8", "" },
// { "DungeonKeepNight9", "" },
//--- ---

{ "DungeonRuinDay0", "Adventurers have been here recently." },
{ "DungeonRuinDay1", "Someone was camping nearby." },
{ "DungeonRuinDay2", "These religious symbols are rather fresh." },
//{ "DungeonRuinDay3", "" },
{ "DungeonRuinDay4", "The door is ajar." },
//{ "DungeonRuinDay5", "" },
{ "DungeonRuinDay6", "Haggard birds fly overhead." },
//{ "DungeonRuinDay7", "" },
//{ "DungeonRuinDay8", "" },
//{ "DungeonRuinDay9", "" },
//---
{ "DungeonRuinNight0", "A loose stone tumbles to the ground." },
{ "DungeonRuinNight1", "The air is musty." },
//{ "DungeonRuinNight2", "" },
{ "DungeonRuinNight3", "The darkness is cloaking the entrance." },
//{ "DungeonRuinNight4", "" },
//{ "DungeonRuinNight5", "" },
// { "DungeonRuinNight6", "" },
// { "DungeonRuinNight7", "" },
// { "DungeonRuinNight8", "" },
// { "DungeonRuinNight9", "" },
//--- ---


            #endregion

            #region Dungeon texts:



// Dungeon: Crypt 190 
{ "Crypt0", "Flies buzz around you." },
{ "Crypt1", "A current of air blows past you." },
{ "Crypt2", "You smell some dried blood." },
{ "Crypt3", "You brush a cobweb off your shoulder." },
{ "Crypt4", "The air here is very stiff." },
{ "Crypt5", "This place smells strongly of death." },
{ "Crypt6", "You hear very faint whispers." },
{ "Crypt7", "A strange shadow moves and vanishes." },
{ "Crypt8", "Tiny bugs scurry away from you." },
{ "Crypt9", "You sense an unholy energy." },

// Dungeon: OrcStronghold  
{ "OrcStronghold0", "Your mouth fills with ash when you breathe." },
{ "OrcStronghold1", "The cobwebs are filled with fur." },
{ "OrcStronghold2", "Animal marks are everywhere." },
{ "OrcStronghold3", "Orcs have drawn some markings here." },
{ "OrcStronghold4", "It smells like Orc blood." },
{ "OrcStronghold5", "The walls are slimy." },
{ "OrcStronghold6", "Some bones have been crushed." },
{ "OrcStronghold7", "A primitive spell scarred the floor." },
{ "OrcStronghold8", "Charcoal smoke lingers in the air." },
{ "OrcStronghold9", "There are faded slash marks." },

// Dungeon: HumanStronghold
{ "HumanStronghold0", "The air is stagnant." },
{ "HumanStronghold1", "The cobwebs are grimy." },
{ "HumanStronghold2", "Dust fills old scratches in the walls." },
{ "HumanStronghold3", "Metal fragments litter the floor." },
{ "HumanStronghold4", "You can smell some blood." },
{ "HumanStronghold5", "You smell burnt wood." },
{ "HumanStronghold6", "Someone spilled ale here." },
{ "HumanStronghold7", "A spell has stained the floor." },
{ "HumanStronghold8", "Flies scatter as you move." },
{ "HumanStronghold9", "Figures seem to form in the shadows." },

// Dungeon: Prison
{ "Prison0", "The stone is cold and filthy." },
{ "Prison1", "You see frantic scribblings nearby." },
{ "Prison2", "You smell the dead." },
{ "Prison3", "You see drops of blood." },
{ "Prison4", "Dead flies fill the cobwebs." },
{ "Prison5", "You hear whispers from the darkness." },
{ "Prison6", "The shadows seem to change and move." },
{ "Prison7", "You smell the remnants of poison." },
{ "Prison8", "Someone tried digging here." },
{ "Prison9", "Metal bars rattle in the distance." },

// Dungeon: Desecrated Temple
{ "DesecratedTemple0", "You sense profane magic in the air." },
{ "DesecratedTemple1", "You see a prayer to the Gods scrawled here." },
{ "DesecratedTemple2", "Someone scratched a religious symbol." },
{ "DesecratedTemple3", "The smell of death is overwhelming." },
{ "DesecratedTemple4", "You feel a rift of energy." },
{ "DesecratedTemple5", "Vengeful spirits roam these depths." },
{ "DesecratedTemple6", "There's a harsh tingling on your skin." },
{ "DesecratedTemple7", "A fine dust covers everything." },
{ "DesecratedTemple8", "Movement blends into shadows." },
{ "DesecratedTemple9", "The sanctity of this place has been fouled." },

// Dungeon: Mine 
{ "Mine0", "The floor has dried blood." },
{ "Mine1", "Small bugs flee your step." },
{ "Mine2", "Your mouth fills with soot when you breathe." },
{ "Mine3", "You notice writing in a strange language." },
{ "Mine4", "Cobwebs fill some cracks in the walls." },
{ "Mine5", "The ground is unusually warm here." },
{ "Mine6", "Some animals have marked their territory." },
{ "Mine7", "The air is stale and suffocating." },
{ "Mine8", "Something tried to dig here." },
{ "Mine9", "There are chisel marks on some stones." },

// Dungeon: Natural Cave
{ "NaturalCave0", "You hear a tiny bat flutter away." },
{ "NaturalCave1", "The shadows seem to change shape." },
{ "NaturalCave2", "Bugs slink into the corners." },
{ "NaturalCave3", "The floor is damp and grimy." },
{ "NaturalCave4", "The air is stale." },
{ "NaturalCave5", "Flies swarm some animal droppings." },
{ "NaturalCave6", "You see some gnarled fur here." },
{ "NaturalCave7", "Cobwebs fill the cracks and corners." },
{ "NaturalCave8", "You smell dried blood." },
{ "NaturalCave9", "Animals have made a home in here." },

// Dungeon: Coven
{ "Coven0", "You see someone when you close your eyes." },
{ "Coven1", "You hear whispering." },
{ "Coven2", "Chanting pursues you from afar." },
{ "Coven3", "You feel very dark energies here." },
{ "Coven4", "You wipe some oddly-colored dust from your face." },
{ "Coven5", "You feel light pin pricks on your skin." },
{ "Coven6", "Magic has stained the walls." },
{ "Coven7", "This area smells of festered concoctions." },
{ "Coven8", "Smashed potion bottles litter the area." },
{ "Coven9", "Laughter echoes in your mind." },

// Dungeon: VampireHaunt
{ "VampireHaunt0", "The air is damp and stale." },
{ "VampireHaunt1", "The floor is sticky with blood." },
{ "VampireHaunt2", "You smell blood." },
{ "VampireHaunt3", "A tiny bat flies away." },
{ "VampireHaunt4", "The air here is disturbed." },
{ "VampireHaunt5", "Unreadable markings cover the floor." },
{ "VampireHaunt6", "The shadows dominate your vision." },
{ "VampireHaunt7", "A smashed vial of blood crinkles underfoot." },
{ "VampireHaunt8", "A gust of cool air hits you." },
{ "VampireHaunt9", "You can feel your heart beating." },

// Dungeon: Laboratory
{ "Laboratory0", "A stinging vapour flows over your feet." },
{ "Laboratory1", "The air is a mix of noxious fumes." },
{ "Laboratory2", "Abandoned notes fade on the walls." },
{ "Laboratory3", "A fine haze stings your nose." },
{ "Laboratory4", "You feel concentrated magical forces." },
{ "Laboratory5", "A caustic liquid has scarred the floor." },
{ "Laboratory6", "The air suddenly turns cold." },
{ "Laboratory7", "You sense volatile magicka in this area." },
{ "Laboratory8", "An evil laugh echoes past." },
{ "Laboratory9", "Some shattered glass crinkles underfoot." },

// Dungeon: HarpyNest
{ "HarpyNest0", "Flies roam the grimy walls." },
{ "HarpyNest1", "The stench of harpy is unbearable." },
{ "HarpyNest2", "Animal droppings stain the floor." },
{ "HarpyNest3", "The floor has some dried blood." },
{ "HarpyNest4", "Caustic magicka festered here." },
{ "HarpyNest5", "You brush some cobwebs off your shoulder." },
{ "HarpyNest6", "The floor bears faint scratch marks." },
{ "HarpyNest7", "A primitive spell was cast here." },
{ "HarpyNest8", "Carrion stench strikes your nose." },
{ "HarpyNest9", "The scurrying bugs sound like a whisper." },

// Dungeon: RuinedCastle
{ "RuinedCastle0", "You smell the smoke of a fire." },
{ "RuinedCastle1", "The shadows trick your eyes." },
{ "RuinedCastle2", "You see ancient markings here." },
{ "RuinedCastle3", "The floor is sticky from mead." },
{ "RuinedCastle4", "The smell of death fills the air." },
{ "RuinedCastle5", "Dust fills the cobwebs." },
{ "RuinedCastle6", "A smashed bottle crinkles underfoot." },
{ "RuinedCastle7", "The undead poison the air." },
{ "RuinedCastle8", "Flies swirl in the air." },
{ "RuinedCastle9", "Unholy sounds echo off the walls." },

// Dungeon: SpiderNest
{ "SpiderNest0", "Webs fill the cracks in the walls." },
{ "SpiderNest1", "A tiny spider skitters across the floor." },
{ "SpiderNest2", "You hear bugs scurrying." },
{ "SpiderNest3", "You smell rancid blood." },
{ "SpiderNest4", "The floor is slightly sticky." },
{ "SpiderNest5", "Some venom has scarred the wall." },
{ "SpiderNest6", "The bugs have gone silent." },
{ "SpiderNest7", "The air is stiff and bitter." },
{ "SpiderNest8", "You brush a spider off your arm." },
{ "SpiderNest9", "A small spider crawls out of your pack." },

// Dungeon: GiantStronghold
{ "GiantStronghold0", "Animals have left their marks." },
{ "GiantStronghold1", "The stench of giants fills the air." },
{ "GiantStronghold2", "Big footprints cover the floor." },
{ "GiantStronghold3", "A stench blows past you." },
{ "GiantStronghold4", "The cobwebs are sickly and matted." },
{ "GiantStronghold5", "A fight left deep scratches and grooves." },
{ "GiantStronghold6", "Your movement has stirred up some fur." },
{ "GiantStronghold7", "You hear bugs coursing and writhing." },
{ "GiantStronghold8", "Dust covers some dried blood." },
{ "GiantStronghold9", "An old spell has scarred the floor." },

// Dungeon: DragonsDen
{ "DragonsDen0", "Dried cobwebs fill cracks in the wall." },
{ "DragonsDen1", "The floor has been hardened by heat." },
{ "DragonsDen2", "There are scratches on the walls." },
{ "DragonsDen3", "You smell some blood." },
{ "DragonsDen4", "The bugs flee into hiding." },
{ "DragonsDen5", "Magic was used here." },
{ "DragonsDen6", "Ancient power courses through the air." },
{ "DragonsDen7", "You smell smoke." },
{ "DragonsDen8", "Some bones have gnaw marks." },
{ "DragonsDen9", "Fur was shed here." },

// Dungeon: BarbarianStronghold
{ "BarbarianStronghold0", "There are bootprints in the dust." },
{ "BarbarianStronghold1", "Ancient evil darkens these corridors." },
{ "BarbarianStronghold2", "There are old cobwebs on the walls." },
{ "BarbarianStronghold3", "The flies are unbearable." },
{ "BarbarianStronghold4", "You see tufts of thick, coarse fur." },
{ "BarbarianStronghold5", "You smell the smoke of a fireplace." },
{ "BarbarianStronghold6", "The floor is sticky with wine." },
{ "BarbarianStronghold7", "Fire scorched the floor here." },
{ "BarbarianStronghold8", "A faded sigil is just visible here." },
{ "BarbarianStronghold9", "You faintly hear distant laughter." },

// Dungeon: VolcanicCaves
{ "VolcanicCaves0", "You feel some air currents along the floor." },
{ "VolcanicCaves1", "Blood has stained the stones." },
{ "VolcanicCaves2", "You stir up some fur with your movement." },
{ "VolcanicCaves3", "The earth rumbles softly." },
{ "VolcanicCaves4", "Animals are attracted to the warmth." },
{ "VolcanicCaves5", "A whiff of sulfur singes your nose." },
{ "VolcanicCaves6", "The air burns your throat." },
{ "VolcanicCaves7", "Everything is covered in ash." },
{ "VolcanicCaves8", "The darkness plays tricks on you." },
{ "VolcanicCaves9", "You smell something burning." },

// Dungeon: ScorpionNest
{ "ScorpionNest0", "Tiny bits of animal bones litter this area." },
{ "ScorpionNest1", "Your mouth fills with dust when you breathe." },
{ "ScorpionNest2", "The shadows seem to move behind you." },
{ "ScorpionNest3", "You stir up some fur." },
{ "ScorpionNest4", "Dark forces twist the life here." },
{ "ScorpionNest5", "Flies litter the cobwebs." },
{ "ScorpionNest6", "A tiny scorpion crawls out of your pack." },
{ "ScorpionNest7", "The air is stale." },
{ "ScorpionNest8", "Some venom scarred the floor here." },
{ "ScorpionNest9", "The insects near you scatter." },

// Dungeon: Cemetery
{ "Cemetery0", "Decaying cobwebs line the walls." },
{ "Cemetery1", "Pray the dead do not seek vengeance." },
{ "Cemetery2", "You smell decomposing bodies." },
{ "Cemetery3", "The air is putrid." },
{ "Cemetery4", "There's a thumping sound." },
{ "Cemetery5", "Faint whispers haunt the air." },
{ "Cemetery6", "Restless spirits chill the air." },
{ "Cemetery7", "You feel the gaze of the dead upon you." },
{ "Cemetery8", "There are scratches on the floor." },
{ "Cemetery9", "Bugs scurry into hiding."}

            #endregion
        };

    }
}
