// Project:         RoleplayRealism mod for Daggerfall Unity (http://www.dfworkshop.net)
// Copyright:       Copyright (C) 2022 Regnier
// License:         MIT License (http://www.opensource.org/licenses/mit-license.php)
// Author:          Regnier

using System.Collections;

namespace AmbientText
{
    public class AmbientText
    {
        /* Keys are in the following format, and if a key is not present no msg is displayed.
         *  Inside dungeon: <dungeonType><0-9>
         *  Outside:        <locType><climate><0-9>
         *                  <locType><dayNight><0-9>
         *                  <locType><dayNight><weather><0-9>
         * Where:
         *  locType  = None,TownCity,TownHamlet,TownVillage,HomeFarms,DungeonLabyrinth,ReligionTemple,Tavern,DungeonKeep,HomeWealthy,ReligionCult,DungeonRuin,HomePoor,Graveyard,Coven,HomeYourShips
         *  climate  = Desert, Swamp, Woods, Mountains, Ocean
         *  dayNight = Day, Night
         *  weather  = Clear, Cloudy, Rainy, Snowy
         *  dungeonType = Crypt,OrcStronghold,HumanStronghold,Prison,DesecratedTemple,Mine,NaturalCave,Coven,VampireHaunt,Laboratory,HarpyNest,RuinedCastle,SpiderNest,GiantStronghold,DragonsDen,BarbarianStronghold,VolcanicCaves,ScorpionNest,Cemetery
         */
        internal static IDictionary AmbientTexts = new Hashtable()
        {
            #region Climate texts:

            // Wilderness climates:
            { "NoneDesert0", "The sand slides under your feet" },
            { "NoneDesert1", "There are some dried bones under the sand here." },
            { "NoneDesert2", "" },
            { "NoneDesert3", "A tiny lizard scampers about." },
            { "NoneDesert4", "A snake submerges in the sand." },
            { "NoneDesert5", "There are scorpion tracks here." },
            { "NoneDesert6", "Thick fur is buried in sand" },
            { "NoneDesert7", "You see some footprints in the sand." },
            { "NoneDesert8", "A baby scorpion crosses your path." },
            { "NoneDesert9", "You squint to keep the sand from your eyes" },

            { "NoneSwamp0", "Someone recently burned oil here." },
            { "NoneSwamp1", "A reptile calls in the distance." },
            { "NoneSwamp2", "Trails lead off through the mud" },
            { "NoneSwamp3", "" },
            { "NoneSwamp4", "This ground emits gases." },
            { "NoneSwamp5", "Your feet are covered in mud" },
            { "NoneSwamp6", "An argonian was here recently" },
            { "NoneSwamp7", "You breathe the thick, damp air" },
            { "NoneSwamp8", "The bugs are unbearable" },
            { "NoneSwamp9", "You stub your toe on a rotten stump" },

            { "NoneWoods0", "One could get lost out here" },
            { "NoneWoods1", "A horse neighs in the distance." },
            { "NoneWoods2", "This arboreal scent is very relaxing." },
            { "NoneWoods3", "Twigs snap underneath you." },
            { "NoneWoods4", "" },
            { "NoneWoods5", "Broken bottles signal an old campsite." },
            { "NoneWoods6", "The branches scratch and poke you" },
            { "NoneWoods7", "An animal shrieks in the tree near you" },
            { "NoneWoods8", "It looks like spriggans have been here" },
            { "NoneWoods9", "The forest canopy provides some shelter" },

            { "NoneMountains0", "You step in a bear track" },
            { "NoneMountains1", "You hear an animal in the distance" },
            { "NoneMountains2", "You cross over some old bones." },
            { "NoneMountains3", "There are some snake holes here." },
            { "NoneMountains4", "You tread carefully around the jagged rocks" },
            { "NoneMountains5", "The air is thin and unsatisfying" },
            { "NoneMountains6", "Sounds echo off the hills" },
            { "NoneMountains7", "Your foot lands next to a tough, spiky plant" },
            { "NoneMountains8", "You startle some birds" },
            { "NoneMountains9", "You feel watched" },

            { "NoneOcean0", "Calm waves roll around you." },
            { "NoneOcean1", "The smell of the sea fills your lungs." },
            { "NoneOcean2", "You wonder what foul beasts reside in the deep" },
            { "NoneOcean3", "The waves are hypnotizing" },
            { "NoneOcean4", "Some seabirds shriek and flap their wings" },
            { "NoneOcean5", "You inhale some water" },
            { "NoneOcean6", "The ocean breeze revitalizes you" },
            { "NoneOcean7", "The sound of the ocean is like a lullaby" },
            { "NoneOcean8", "You remember that time you almost drowned" },
            { "NoneOcean9", "You check the water for Slaughterfish" },

            // City climates:
            { "TownCityDesert0", "You smell roasting scorpion." },
{ "TownCityDesert1", "Many people have walked these paths" },
{ "TownCityDesert2", "" },
{ "TownCityDesert3", "" },
{ "TownCityDesert4", "" },
{ "TownCityDesert5", "A welcoming oasis in these lands" },
{ "TownCityDesert6", "The streets make walking in the sand a bit easier" },
{ "TownCityDesert7", "The cityfolk protect their belongings from the sand" },
{ "TownCityDesert8", "" },
{ "TownCityDesert9", "A lizard snatches a beetle and runs off" },
---
{ "TownCitySwamp0", "" },
{ "TownCitySwamp1", "Your feet weigh heavily in this damp soil." },
{ "TownCitySwamp2", "" },
{ "TownCitySwamp3", "The smokey flames help keep the bugs away" },
{ "TownCitySwamp4", "You hear some croaking frogs in the distance" },
{ "TownCitySwamp5", "The smell of mud is replaced by fresh baked bread" },
{ "TownCitySwamp6", "The cityfolk make the most of their environment" },
{ "TownCitySwamp7", "Taverns can provide a bed free from mud" },
{ "TownCitySwamp8", "" },
{ "TownCitySwamp9", "" },
---
{ "TownCityWoods0", "The smell of roast pig fills the air." },
{ "TownCityWoods1", "You see a sturdy walking stick leaning nearby" },
{ "TownCityWoods2", "" },
{ "TownCityWoods3", "The smell of wood smoke is soothing" },
{ "TownCityWoods4", "A fletcher minds his craft" },
{ "TownCityWoods5", "" },
{ "TownCityWoods6", "The thick tree cover makes this place feel secure" },
{ "TownCityWoods7", "You wonder if you'll see a Wood Elf" },
{ "TownCityWoods8", "" },
{ "TownCityWoods9", "The cityfolk whisper of tree spirits" },
---
{ "TownCityMountains0", "This area smells heavily of roast chicken." },
{ "TownCityMountains1", "The wind can be quite strong" },
{ "TownCityMountains2", "The city is well situated in the mountains" },
{ "TownCityMountains3", "The cityfolk feel they are closer to The Divines here" },
{ "TownCityMountains4", "Some of the rocks have religious markings" },
{ "TownCityMountains5", "The city walls contain decorated mountain rocks" },
{ "TownCityMountains6", "Some believe the evergreens point to The Divines " },
{ "TownCityMountains7", "" },
{ "TownCityMountains8", "" },
{ "TownCityMountains9", "" },

            // Hamlet climates:
      { "TownHamletDesert0", "" },
{ "TownHamletDesert1", "" },
{ "TownHamletDesert2", "There must be some camels nearby" },
{ "TownHamletDesert3", "This village seems to cater to travellers often" },
{ "TownHamletDesert4", "A villager sweeps away some sand" },
{ "TownHamletDesert5", "The villagers seem to have what they need here" },
{ "TownHamletDesert6", "The streets make it easier to get around" },
{ "TownHamletDesert7", "" },
{ "TownHamletDesert8", "" },
{ "TownHamletDesert9", "A swell of sand stings your eyes" },
---
{ "TownHamletSwamp0", "" },
{ "TownHamletSwamp1", "There seem to be fewer bugs in the village" },
{ "TownHamletSwamp2", "Your feet need to be dried by a fire" },
{ "TownHamletSwamp3", "A frog leaps out from under your footstep" },
{ "TownHamletSwamp4", "You slip on a root" },
{ "TownHamletSwamp5", "The moss grows rapidly in this area" },
{ "TownHamletSwamp6", "Seeing the glow of the fires is soothing" },
{ "TownHamletSwamp7", "" },
{ "TownHamletSwamp8", "A villager drops their basket in the mud" },
{ "TownHamletSwamp9", "" },
---
{ "TownHamletWoods0", "The birds sing and flutter" },
{ "TownHamletWoods1", "You brush some twigs off your shoulder" },
{ "TownHamletWoods2", "The smell of woodfire is welcoming" },
{ "TownHamletWoods3", "The trees make this a peaceful setting" },
{ "TownHamletWoods4", "The villagers seem concerned with spriggans in the area" },
{ "TownHamletWoods5", "Someone has whittled a figure of the Eternal Champion" },
{ "TownHamletWoods6", "" },
{ "TownHamletWoods7", "" },
{ "TownHamletWoods8", "" },
{ "TownHamletWoods9", "" },
---
{ "TownHamletMountains0", "You smell a wonderous spice from someones window" },
{ "TownHamletMountains1", "" },
{ "TownHamletMountains2", "The rocks are adorned with decoration" },
{ "TownHamletMountains3", "You can feel the breeze on your skin" },
{ "TownHamletMountains4", "The air is very fresh and clean up here" },
{ "TownHamletMountains5", "Birds ride the air currents above you" },
{ "TownHamletMountains6", "" },
{ "TownHamletMountains7", "Villagers pray atop the peaks" },
{ "TownHamletMountains8", "" },
{ "TownHamletMountains9", "" },

            // Village climates:
  { "TownVillageDesert0", "The sand builds on the sides of the houses" },
{ "TownVillageDesert1", "A lizard rests in the sand nearby" },
{ "TownVillageDesert2", "A dog is digging in the sand" },
{ "TownVillageDesert3", "A tavern with cold drink is all you think of now" },
{ "TownVillageDesert4", "The locals fear lizardmen may find their homes" },
{ "TownVillageDesert5", "The heat rises off the sand behind you" },
{ "TownVillageDesert6", "A camel is eyeing you" },
{ "TownVillageDesert7", "The vulture overhead flys off" },
{ "TownVillageDesert8", "" },
{ "TownVillageDesert9", "" },
---
{ "TownVillageSwamp0", "" },
{ "TownVillageSwamp1", "The smell of wood fires replaces the stale bog" },
{ "TownVillageSwamp2", "" },
{ "TownVillageSwamp3", "A snake slips by your foot" },
{ "TownVillageSwamp4", "" },
{ "TownVillageSwamp5", "A crow caws and flys off" },
{ "TownVillageSwamp6", "Your feet slide on the muddy ground" },
{ "TownVillageSwamp7", "You hope to find an accomodating tavern" },
{ "TownVillageSwamp8", "" },
{ "TownVillageSwamp9", "" },
---
{ "TownVillageWoods0", "You hear someone chopping wood" },
{ "TownVillageWoods1", "You smell the smoke of a fire" },
{ "TownVillageWoods2", "A sturdy walking stick rests next to a house" },
{ "TownVillageWoods3", "" },
{ "TownVillageWoods4", "An owl startles you with a hoot" },
{ "TownVillageWoods5", "You step over a root in the path" },
{ "TownVillageWoods6", "It's a very peaceful life here" },
{ "TownVillageWoods7", "This is a place to rest your legs" },
{ "TownVillageWoods8", "You hear the wind rustle the leaves" },
{ "TownVillageWoods9", "" },
---
{ "TownVillageMountains0", "Rocks are shaped and used as decoration" },
{ "TownVillageMountains1", "The wind blows through the houses" },
{ "TownVillageMountains2", "There's a well worn merchant path" },
{ "TownVillageMountains3", "The streets are welcoming after travelling the terrain" },
{ "TownVillageMountains4", "The mountains dwarf this modest place" },
{ "TownVillageMountains5", "Mountain flowers adorn most windows" },
{ "TownVillageMountains6", "" },
{ "TownVillageMountains7", "" },
{ "TownVillageMountains8", "You hear some birds nearby" },
{ "TownVillageMountains9", "" },

            // Tavern climates:
        { "TavernDesert0", "You wipe the sand from your eyes" },
{ "TavernDesert1", "This place had better keep the drink flowing" },
{ "TavernDesert2", "There's a concerning clump of sand nearby" },
{ "TavernDesert3", "A lizard has made this tavern it's home" },
{ "TavernDesert4", "" },
{ "TavernDesert5", "An  old mug is half buried in the sand" },
{ "TavernDesert6", "A camel munches and grunts at you" },
{ "TavernDesert7", "" },
{ "TavernDesert8", "" },
{ "TavernDesert9", "You can smell the ale from here" },
---
{ "TavernSwamp0", "" },
{ "TavernSwamp1", "The area is quite muddy" },
{ "TavernSwamp2", "Many a weary traveller has stopped here" },
{ "TavernSwamp3", "The smell of ale is all you notice" },
{ "TavernSwamp4", "There are animal bones here" },
{ "TavernSwamp5", "" },
{ "TavernSwamp6", "You cant wait to escape these bugs" },
{ "TavernSwamp7", "Someone is passed out around back" },
{ "TavernSwamp8", "" },
{ "TavernSwamp9", "You hope for fresh food" },
---
{ "TavernWoods0", "Someone is swaying behind a tree" },
{ "TavernWoods1", "" },
{ "TavernWoods2", "You lust after the thought of a drink" },
{ "TavernWoods3", "the scent of the fire pursues you" },
{ "TavernWoods4", "You see a patron carrying a large leg of pork" },
{ "TavernWoods5", "" },
{ "TavernWoods6", "" },
{ "TavernWoods7", "This seems to be a popular establishment" },
{ "TavernWoods8", "You almost couldnt find this place through the trees" },
{ "TavernWoods9", "" },
---
{ "TavernMountains0", "The rocks are covered in broken glass" },
{ "TavernMountains1", "You can see and hear this place for a mile" },
{ "TavernMountains2", "It sounds like a fight has broken out" },
{ "TavernMountains3", "You can feel the drink on your lips already" },
{ "TavernMountains4", "You think you spot a nest among the rocks" },
{ "TavernMountains5", "You hear a swell of birds not far off" },
{ "TavernMountains6", "theres an old pair of pants on the rocks" },
{ "TavernMountains7", "" },
{ "TavernMountains8", "" },
{ "TavernMountains9", "A drunkard thinks he's your friend" },

            // Farm climates:
        { "HomeFarmsDesert0", "Maybe there's some food to spare" },
{ "HomeFarmsDesert1", "It must be hard work to get a prosperous yield" },
{ "HomeFarmsDesert2", "The workers have carefully tended the crops" },
{ "HomeFarmsDesert3", "When the wind subsides you can smell the farm" },
{ "HomeFarmsDesert4", "Some religious symbols are marked around the crops" },
{ "HomeFarmsDesert5", "" },
{ "HomeFarmsDesert6", "The Divines must help this family grow crops out here" },
{ "HomeFarmsDesert7", "" },
{ "HomeFarmsDesert8", "These people feed the nearby towns and villages" },
{ "HomeFarmsDesert9", "" },
---
{ "HomeFarmsSwamp0", "There's plenty of water for the soil here" },
{ "HomeFarmsSwamp1", "You swat a fly away" },
{ "HomeFarmsSwamp2", "" },
{ "HomeFarmsSwamp3", "" },
{ "HomeFarmsSwamp4", "" },
{ "HomeFarmsSwamp5", "" },
{ "HomeFarmsSwamp6", "" },
{ "HomeFarmsSwamp7", "The birds have found some seeds to peck at" },
{ "HomeFarmsSwamp8", "Hopefully the farmhands feel like sharing" },
{ "HomeFarmsSwamp9", "These people feed many others in their region" },
---
{ "HomeFarmsWoods0", "You hope for a generous farmhand" },
{ "HomeFarmsWoods1", "They've cleared the trees to get sun on the crops" },
{ "HomeFarmsWoods2", "This land can be difficult to manage" },
{ "HomeFarmsWoods3", "" },
{ "HomeFarmsWoods4", "" },
{ "HomeFarmsWoods5", "" },
{ "HomeFarmsWoods6", "" },
{ "HomeFarmsWoods7", "This farm is vital to feeding the locals" },
{ "HomeFarmsWoods8", "This place feels private and peaceful" },
{ "HomeFarmsWoods9", "" },
---
{ "HomeFarmsMountains0", "A careful hand can grow a field of crops here" },
{ "HomeFarmsMountains1", "The Divines are held dear for mountain growers" },
{ "HomeFarmsMountains2", "Mountain rocks reinforce their walls" },
{ "HomeFarmsMountains3", "" },
{ "HomeFarmsMountains4", "The farmhand work hard to maximize their yield" },
{ "HomeFarmsMountains5", "" },
{ "HomeFarmsMountains6", "" },
{ "HomeFarmsMountains7", "" },
{ "HomeFarmsMountains8", "The yield here will feed people in the surrounding area" },
{ "HomeFarmsMountains9", "" },

            // Mansion climates:
       { "HomeWealthyDesert0", "This estate is more well off than others" },
{ "HomeWealthyDesert1", "There is a squire eyeing you" },
{ "HomeWealthyDesert2", "You wonder how this person affords this" },
{ "HomeWealthyDesert3", "" },
{ "HomeWealthyDesert4", "" },
{ "HomeWealthyDesert5", "" },
{ "HomeWealthyDesert6", "These estates are maintained for lords of the region" },
{ "HomeWealthyDesert7", "" },
{ "HomeWealthyDesert8", "More is spent on water than many make in a year" },
{ "HomeWealthyDesert9", "" },
---
{ "HomeWealthySwamp0", "You see very high quality wares in use" },
{ "HomeWealthySwamp1", "" },
{ "HomeWealthySwamp2", "This place is more ornate than many others" },
{ "HomeWealthySwamp3", "The workers have styled the plantgrowth on the houses" },
{ "HomeWealthySwamp4", "" },
{ "HomeWealthySwamp5", "" },
{ "HomeWealthySwamp6", "The ground isnt as muddy as most other places" },
{ "HomeWealthySwamp7", "You see a princely looking figure in the window" },
{ "HomeWealthySwamp8", "" },
{ "HomeWealthySwamp9", "" },
---
{ "HomeWealthyWoods0", "These houses are sturdy and secure" },
{ "HomeWealthyWoods1", "Many caravans come through here with goods" },
{ "HomeWealthyWoods2", "" },
{ "HomeWealthyWoods3", "" },
{ "HomeWealthyWoods4", "" },
{ "HomeWealthyWoods5", "" },
{ "HomeWealthyWoods6", "The animals have shiny, healthy coats" },
{ "HomeWealthyWoods7", "" },
{ "HomeWealthyWoods8", "That smell on the air, you didnt think that spice was available here" },
{ "HomeWealthyWoods9", "This is fit for a King" },
---
{ "HomeWealthyMountains0", "The cost of these building materials is astounding" },
{ "HomeWealthyMountains1", "" },
{ "HomeWealthyMountains2", "Flowers decorate these buildings" },
{ "HomeWealthyMountains3", "They've left decorations on the surrounding rocks" },
{ "HomeWealthyMountains4", "You wonder what exotic items these walls hold" },
{ "HomeWealthyMountains5", "" },
{ "HomeWealthyMountains6", "" },
{ "HomeWealthyMountains7", "Some of the rocks have carvings inlet with gems" },
{ "HomeWealthyMountains8", "The animals water is clear and plentiful" },
{ "HomeWealthyMountains9", "" },

            // Hovel climates:
       { "HomePoorDesert0", "The house has fallen into disrepair" },
{ "HomePoorDesert1", "" },
{ "HomePoorDesert2", "Some birds are pecking at old bones" },
{ "HomePoorDesert3", "" },
{ "HomePoorDesert4", "" },
{ "HomePoorDesert5", "" },
{ "HomePoorDesert6", "This place should be abandoned" },
{ "HomePoorDesert7", "The sand has covered some of the old structures" },
{ "HomePoorDesert8", "You pain to see someone live like this" },
{ "HomePoorDesert9", "Maybe this place used to be nice" },
---
{ "HomePoorSwamp0", "You see a broken wagon wheel" },
{ "HomePoorSwamp1", "" },
{ "HomePoorSwamp2", "This house is barely standing" },
{ "HomePoorSwamp3", "The soil looks spent" },
{ "HomePoorSwamp4", "The swampland smells preferable to this place" },
{ "HomePoorSwamp5", "" },
{ "HomePoorSwamp6", "The wood here is rotting" },
{ "HomePoorSwamp7", "" },
{ "HomePoorSwamp8", "" },
{ "HomePoorSwamp9", "Some broken equipment is discarded nearby" },
---
{ "HomePoorWoods0", "The forest is starting to swallow this place" },
{ "HomePoorWoods1", "You doubt many people even know this exists" },
{ "HomePoorWoods2", "The house looks broken down" },
{ "HomePoorWoods3", "A window shutter creaks and slams in the breeze" },
{ "HomePoorWoods4", "The buildings look torn apart" },
{ "HomePoorWoods5", "" },
{ "HomePoorWoods6", "You hope no one lives here" },
{ "HomePoorWoods7", "You dont want to stay here very long" },
{ "HomePoorWoods8", "" },
{ "HomePoorWoods9", "" },
---
{ "HomePoorMountains0", "The ground is rocky and uneven" },
{ "HomePoorMountains1", "You wince at the squalor" },
{ "HomePoorMountains2", "You sense this used to be a reputable establishment" },
{ "HomePoorMountains3", "" },
{ "HomePoorMountains4", "Only scavengers are seen near here" },
{ "HomePoorMountains5", "This place feels dreary" },
{ "HomePoorMountains6", "You hope to be done your business and leave" },
{ "HomePoorMountains7", "You wonder about who would live here" },
{ "HomePoorMountains8", "" },
{ "HomePoorMountains9", "Someone tried to scratch a religious symbol here" },

           // Graveyard Climates:
{ "GraveyardDesert0", "Some bones are half buried in the sand" },
{ "GraveyardDesert1", "Scavengers indicate a recent burial" },
{ "GraveyardDesert2", "A fat lizard has burrowed near a grave" },
{ "GraveyardDesert3", "A vulture circles above you" },
{ "GraveyardDesert4", "The sand finds its way into your gear" },
{ "GraveyardDesert5", "Shifting sands have toppled some gravestones" },
{ "GraveyardDesert6", "The crypt emits a humming" },
{ "GraveyardDesert7", "Beetles scurry from your step" },
{ "GraveyardDesert8", "There are some old dried flowers buried in the sand" },
{ "GraveyardDesert9", "" },
---
{ "GraveyardSwamp0", "Sounds are coming from the crypt" },
{ "GraveyardSwamp1", "The bugs are large and confident" },
{ "GraveyardSwamp2", "The vegetation has gone rancid" },
{ "GraveyardSwamp3", "It suddenly feels cold" },
{ "GraveyardSwamp4", "" },
{ "GraveyardSwamp5", "" },
{ "GraveyardSwamp6", "" },
{ "GraveyardSwamp7", "Something was dragged through the mud" },
{ "GraveyardSwamp8", "" },
{ "GraveyardSwamp9", "An old symbol of The Nine has nearly vanished" },
---
{ "GraveyardWoods0", "The trees around this site look diseased" },
{ "GraveyardWoods1", "The crows near here sound sick" },
{ "GraveyardWoods2", "You think you see someone in the forest" },
{ "GraveyardWoods3", "The tree nearest to you shakes" },
{ "GraveyardWoods4", "Birds are nesting near the graves" },
{ "GraveyardWoods5", "The roots have pushed over a tombstone" },
{ "GraveyardWoods6", "A wooden decoration has rotted" },
{ "GraveyardWoods7", "The crypt sends out a ringing sound" },
{ "GraveyardWoods8", "This religious symbol is meant to protect the dead" },
{ "GraveyardWoods9", "" },
---
{ "GraveyardMountains0", "There are scratches on the rocks" },
{ "GraveyardMountains1", "Stones are used to decorate the graves" },
{ "GraveyardMountains2", "A voice calls from the crypt" },
{ "GraveyardMountains3", "The ground here is a reddish brown" },
{ "GraveyardMountains4", "" },
{ "GraveyardMountains5", "" },
{ "GraveyardMountains6", "" },
{ "GraveyardMountains7", "A ritual was performed here" },
{ "GraveyardMountains8", ""Here lies my only love"" },
{ "GraveyardMountains9", "" },
--- ---

--- ---// Coven Climates:
{ "CovenDesert0", "The beldam's presence is striking" },
{ "CovenDesert1", "Twisted patterns have formed in the sand" },
{ "CovenDesert2", "Some sort of energy melted the sand here" },
{ "CovenDesert3", "You smell strange ingredients" },
{ "CovenDesert4", "" },
{ "CovenDesert5", "" },
{ "CovenDesert6", "" },
{ "CovenDesert7", "" },
{ "CovenDesert8", "" },
{ "CovenDesert9", "" },
---
{ "CovenSwamp0", "There are strange grooves in the mud" },
{ "CovenSwamp1", "The beldam stands facing you" },
{ "CovenSwamp2", "" },
{ "CovenSwamp3", "The bugs and reptiles slink nearer" },
{ "CovenSwamp4", "" },
{ "CovenSwamp5", "" },
{ "CovenSwamp6", "" },
{ "CovenSwamp7", "" },
{ "CovenSwamp8", "" },
{ "CovenSwamp9", "" },
---
{ "CovenWoods0", "The trees seem to curl around you" },
{ "CovenWoods1", "" },
{ "CovenWoods2", "You brush a spider off your leg" },
{ "CovenWoods3", "The beldams eyes are hypnotizing" },
{ "CovenWoods4", "" },
{ "CovenWoods5", "" },
{ "CovenWoods6", "" },
{ "CovenWoods7", "" },
{ "CovenWoods8", "" },
{ "CovenWoods9", "" },
---
{ "CovenMountains0", "Its as if they have never moved from this spot" },
{ "CovenMountains1", "The beldam stares without blinking" },
{ "CovenMountains2", "Their chanting echoes in the hills" },
{ "CovenMountains3", "" },
{ "CovenMountains4", "The rocks are decorated with bones" },
{ "CovenMountains5", "" },
{ "CovenMountains6", "" },
{ "CovenMountains7", "" },
{ "CovenMountains8", "" },
{ "CovenMountains9", "" },
--- ---

--- ---// Temple Climates:
{ "ReligionTempleDesert0", "Pilgrims make the treck here to worship" },
{ "ReligionTempleDesert1", "The temple is accepting visitors" },
{ "ReligionTempleDesert2", "A symbol for The Nine is placed in a window" },
{ "ReligionTempleDesert3", "You feel a concentration of energy" },
{ "ReligionTempleDesert4", "Donations are said to give luck" },
{ "ReligionTempleDesert5", "Temples are said to offer cures, even to non members" },
{ "ReligionTempleDesert6", "You smell ceremonial fire" },
{ "ReligionTempleDesert7", "Some lizards rest near the temple" },
{ "ReligionTempleDesert8", "Caravans keep this place well stocked" },
{ "ReligionTempleDesert9", "The temple has resonated a pattern in the sand" },
---
{ "ReligionTempleSwamp0", "Devotees place designs in the moss on the temple" },
{ "ReligionTempleSwamp1", "You can see people in the temple" },
{ "ReligionTempleSwamp2", "You feel a rush of energy" },
{ "ReligionTempleSwamp3", "Someone has scratched a mark for The Nine" },
{ "ReligionTempleSwamp4", "Donations help keep the temple clean" },
{ "ReligionTempleSwamp5", "If you are ill, the temple can help you" },
{ "ReligionTempleSwamp6", "The wildlife seems relaxed near the temple" },
{ "ReligionTempleSwamp7", "The dirt around the temple has a pattern forming" },
{ "ReligionTempleSwamp8", "Songbirds adorn the temple" },
{ "ReligionTempleSwamp9", "" },
---
{ "ReligionTempleWoods0", "There are religious markings on the trees" },
{ "ReligionTempleWoods1", "Someone has whittled a religious statue" },
{ "ReligionTempleWoods2", "Woodland animals rest near the temple" },
{ "ReligionTempleWoods3", "Eight and One is written on a tree stump" },
{ "ReligionTempleWoods4", "Someone lights a candle in the temple" },
{ "ReligionTempleWoods5", "The donations from locals are put to good use" },
{ "ReligionTempleWoods6", "Temples are known to cure any who seek it" },
{ "ReligionTempleWoods7", "" },
{ "ReligionTempleWoods8", "" },
{ "ReligionTempleWoods9", "You feel a swell of energy" },
---
{ "ReligionTempleMountains0", "You feel a focus of energy" },
{ "ReligionTempleMountains1", "The rocks have religious markings" },
{ "ReligionTempleMountains2", "There are prayer sites in the surrounding hills" },
{ "ReligionTempleMountains3", "Someone just finished a prayer in the temple" },
{ "ReligionTempleMountains4", "Donations are accepted by members of the faith" },
{ "ReligionTempleMountains5", "This looks like a Talos symbol" },
{ "ReligionTempleMountains6", "You can cure an illness in the temple" },
{ "ReligionTempleMountains7", "" },
{ "ReligionTempleMountains8", "" },
{ "ReligionTempleMountains9", "" },
--- ---

--- ---// Cult Climates
{ "ReligionCultDesert0", "A discreet place to practice rituals" },
{ "ReligionCultDesert1", "Thick smoke pollutes the air" },
{ "ReligionCultDesert2", "You are met with intense eyes" },
{ "ReligionCultDesert3", "The building has been eroded by sand and wind" },
{ "ReligionCultDesert4", "Religious carvings are placed in the sand" },
{ "ReligionCultDesert5", "" },
{ "ReligionCultDesert6", "" },
{ "ReligionCultDesert7", "" },
{ "ReligionCultDesert8", "" },
{ "ReligionCultDesert9", "" },
---
{ "ReligionCultSwamp0", "Truely zealous devotees congregate here" },
{ "ReligionCultSwamp1", "The moss is creeping up the rocks" },
{ "ReligionCultSwamp2", "There's some discoloured smoke rising" },
{ "ReligionCultSwamp3", "Footprints litter the mud" },
{ "ReligionCultSwamp4", "You step on a bug you've never seen before" },
{ "ReligionCultSwamp5", "" },
{ "ReligionCultSwamp6", "" },
{ "ReligionCultSwamp7", "" },
{ "ReligionCultSwamp8", "" },
{ "ReligionCultSwamp9", "" },
---
{ "ReligionCultWoods0", "A sickly smoke drifts nearby" },
{ "ReligionCultWoods1", "Not much grows here" },
{ "ReligionCultWoods2", "The crows sound haggard" },
{ "ReligionCultWoods3", "There are faces in the trees" },
{ "ReligionCultWoods4", "A scrap of parchment blows past" },
{ "ReligionCultWoods5", "Fanatics are drawn to this place" },
{ "ReligionCultWoods6", "" },
{ "ReligionCultWoods7", "" },
{ "ReligionCultWoods8", "" },
{ "ReligionCultWoods9", "" },
---
{ "ReligionCultMountains0", "Fanatics are intoxicated by The Divines" },
{ "ReligionCultMountains1", "" },
{ "ReligionCultMountains2", "There are bug carcasses littered about" },
{ "ReligionCultMountains3", "The air has changed" },
{ "ReligionCultMountains4", "The ground rumbles slightly" },
{ "ReligionCultMountains5", "" },
{ "ReligionCultMountains6", "" },
{ "ReligionCultMountains7", "" },
{ "ReligionCultMountains8", "" },
{ "ReligionCultMountains9", "" },
--- ---

--- ---// Dungeon Climates:
{ "DungeonLabyrinthDesert0", "A hot gust of wind burns your eyes" },
{ "DungeonLabyrinthDesert1", "The ground writhes and devours all the fallen" },
{ "DungeonLabyrinthDesert2", "The sand covers countless dead" },
{ "DungeonLabyrinthDesert3", "The sand feels like molten blades" },
{ "DungeonLabyrinthDesert4", "You hear horrible sounds underground" },
{ "DungeonLabyrinthDesert5", "The wildlife stays far from here" },
{ "DungeonLabyrinthDesert6", "The sand is coarse and discolored" },
{ "DungeonLabyrinthDesert7", "A religious item is stained in blood" },
{ "DungeonLabyrinthDesert8", "Pray the desert consumes this place" },
{ "DungeonLabyrinthDesert9", "Theres a deathly howl coming from the deep" },
---
{ "DungeonLabyrinthSwamp0", "The dirt near the dungeon is sizzling and hissing" },
{ "DungeonLabyrinthSwamp1", "The wretched stench of death is powerful" },
{ "DungeonLabyrinthSwamp2", "The worms are fat and sickly" },
{ "DungeonLabyrinthSwamp3", "A crow seems to laugh at you" },
{ "DungeonLabyrinthSwamp4", "Painful faces appear in the mud" },
{ "DungeonLabyrinthSwamp5", "Bugs try to burrow in your skin" },
{ "DungeonLabyrinthSwamp6", "The mud is a deep reddish brown" },
{ "DungeonLabyrinthSwamp7", "Your mouth fills with rot as you breathe" },
{ "DungeonLabyrinthSwamp8", "" },
{ "DungeonLabyrinthSwamp9", "A body is mostly consumed in mud" },
---
{ "DungeonLabyrinthWoods0", "There are scratches on the trees" },
{ "DungeonLabyrinthWoods1", "The branches are twisted like hooks" },
{ "DungeonLabyrinthWoods2", "The trees creak and moan" },
{ "DungeonLabyrinthWoods3", "The roots have grown wild and gluttonous" },
{ "DungeonLabyrinthWoods4", "Deadly enemies are coarsing underground" },
{ "DungeonLabyrinthWoods5", "The trees stab and slash at you" },
{ "DungeonLabyrinthWoods6", "" },
{ "DungeonLabyrinthWoods7", "You feel the suffering inflicted here" },
{ "DungeonLabyrinthWoods8", "You hear something cry out in death" },
{ "DungeonLabyrinthWoods9", "Most turn back here..." },
---
{ "DungeonLabyrinthMountains0", "Screams echo off the mountains and meet your ear" },
{ "DungeonLabyrinthMountains1", "Blood is shed on the rocks" },
{ "DungeonLabyrinthMountains2", "The flies leech your blood" },
{ "DungeonLabyrinthMountains3", "The plants are dying" },
{ "DungeonLabyrinthMountains4", "Those marks aren't human" },
{ "DungeonLabyrinthMountains5", "The corpses are left by scavengers" },
{ "DungeonLabyrinthMountains6", "There are few capable of surviving this place" },
{ "DungeonLabyrinthMountains7", "The thin air is noxious and painful" },
{ "DungeonLabyrinthMountains8", "" },
{ "DungeonLabyrinthMountains9", "" },
--- ---

--- ---
{ "DungeonKeepDesert0", "A vulture circles overhead" },
{ "DungeonKeepDesert1", "The sand rolls over some bones" },
{ "DungeonKeepDesert2", "A ghastly lizard scurries from the dungeon door" },
{ "DungeonKeepDesert3", "A broken potion bottle fills with sand" },
{ "DungeonKeepDesert4", "A religious marking was drawn here for protection" },
{ "DungeonKeepDesert5", "Beetles are crawling on the archways" },
{ "DungeonKeepDesert6", "The sand grinds your feet and burns you" },
{ "DungeonKeepDesert7", "Animals scurry away carrying bones" },
{ "DungeonKeepDesert8", "" },
{ "DungeonKeepDesert9", "" },
---
{ "DungeonKeepSwamp0", "Snakes writhe around rusted armor" },
{ "DungeonKeepSwamp1", "Bugs swarm your eyes and ears" },
{ "DungeonKeepSwamp2", "There seems to be a grave here" },
{ "DungeonKeepSwamp3", "The moss around the entrance is dying" },
{ "DungeonKeepSwamp4", "A scorpion is feasting on a lizard" },
{ "DungeonKeepSwamp5", "Some hair is matted into the mud" },
{ "DungeonKeepSwamp6", "You taste the thick air as you breath" },
{ "DungeonKeepSwamp7", "" },
{ "DungeonKeepSwamp8", "You think you hear a shriek" },
{ "DungeonKeepSwamp9", "" },
---
{ "DungeonKeepWoods0", "The leaves drip an oily substance" },
{ "DungeonKeepWoods1", "Bugs crawl out of a skull" },
{ "DungeonKeepWoods2", "The trees are dead and dried out" },
{ "DungeonKeepWoods3", "The forest seems to whisper a warning" },
{ "DungeonKeepWoods4", "A religious relic has been desecrated" },
{ "DungeonKeepWoods5", "The woods twist around this place" },
{ "DungeonKeepWoods6", "The forest is playing tricks on you" },
{ "DungeonKeepWoods7", "A root seems to grab your foot" },
{ "DungeonKeepWoods8", "" },
{ "DungeonKeepWoods9", "" },
---
{ "DungeonKeepMountains0", "The plant life is sparse" },
{ "DungeonKeepMountains1", "Mountain stones are used to commemorate the dead" },
{ "DungeonKeepMountains2", "A religious symbol has some dead flowers next to it" },
{ "DungeonKeepMountains3", "The trees direct the dead to the afterlife" },
{ "DungeonKeepMountains4", "You think you hear a crash underground" },
{ "DungeonKeepMountains5", "Some destruction magic was cast here" },
{ "DungeonKeepMountains6", "The rocks are grimy and cold to the touch" },
{ "DungeonKeepMountains7", "You can't get a full breath of air" },
{ "DungeonKeepMountains8", "Something was killed here" },
{ "DungeonKeepMountains9", "" },
--- ---

--- ---
{ "DungeonRuinDesert0", "An old axe head has been dulled in the sand" },
{ "DungeonRuinDesert1", "The sand is coarser than usual" },
{ "DungeonRuinDesert2", "The bugs scurry away as you approach" },
{ "DungeonRuinDesert3", "Gnarled reptiles snap their jaws and hiss at you " },
{ "DungeonRuinDesert4", "The wind blows sand into the dungeon entrance" },
{ "DungeonRuinDesert5", "" },
{ "DungeonRuinDesert6", "Sand has gotten into an old potion" },
{ "DungeonRuinDesert7", "There is an air current from the dungeon" },
{ "DungeonRuinDesert8", "" },
{ "DungeonRuinDesert9", "The doorway is worn and scuffed" },
---
{ "DungeonRuinSwamp0", "Tracks lead into the dungeon" },
{ "DungeonRuinSwamp1", "The door is rotting off its hinges" },
{ "DungeonRuinSwamp2", "A jawbone sticks out of the mud" },
{ "DungeonRuinSwamp3", "You can hear the wildlife chatter" },
{ "DungeonRuinSwamp4", "The bugs are more aggressive" },
{ "DungeonRuinSwamp5", "Some moths rest near the entrance" },
{ "DungeonRuinSwamp6", "Something tried to eat a rat" },
{ "DungeonRuinSwamp7", "The swamp air is particularly thick" },
{ "DungeonRuinSwamp8", "The entrance door jostles in the breeze" },
{ "DungeonRuinSwamp9", "A faded potion recipe is tucked under a rock" },
---
{ "DungeonRuinWoods0", "A prayer site was erected in the trees" },
{ "DungeonRuinWoods1", "A crow caws and flys away" },
{ "DungeonRuinWoods2", "The trees seem to reach for you" },
{ "DungeonRuinWoods3", "The bark looks like it has ash on it" },
{ "DungeonRuinWoods4", "A rogue was making some arrows here" },
{ "DungeonRuinWoods5", "You can feel an air current from the dungeon" },
{ "DungeonRuinWoods6", "Someone put a rats head on a spike" },
{ "DungeonRuinWoods7", "Wind rustles the leaves like a whisper" },
{ "DungeonRuinWoods8", "" },
{ "DungeonRuinWoods9", "" },
---
{ "DungeonRuinMountains0", "Religious symbols are freshly painted on the rocks" },
{ "DungeonRuinMountains1", "A rock mound is used as a makeshift grave" },
{ "DungeonRuinMountains2", "Only spiky grass grows easily here" },
{ "DungeonRuinMountains3", "The dungeon air whistles through the doorway" },
{ "DungeonRuinMountains4", "There are footprints around the entrance" },
{ "DungeonRuinMountains5", "Someones old shield has wasted away in the weather" },
{ "DungeonRuinMountains6", "The air just got very thin" },
{ "DungeonRuinMountains7", "A bat was cooked and eaten" },
{ "DungeonRuinMountains8", "" },
{ "DungeonRuinMountains9", "The mountain peaks loom over you" },


            // Player Ship - Always Ocean Climate
         { "HomeYourShipsOcean0", "The waves sound like a lullaby" },
{ "HomeYourShipsOcean1", "The water extends for miles" },
{ "HomeYourShipsOcean2", "You check the water for beasts" },
{ "HomeYourShipsOcean3", "You can smell the water from here" },
{ "HomeYourShipsOcean4", "The ocean breeze moans "Kelle"" },

            #endregion

            #region Weather texts:

            // Wilderness Weather:
{ "NoneDayClear0", "You notice an ant trail beside you." },
{ "NoneDayClear1", "You squint your eyes in the sun" },
{ "NoneDayClear2", "A beautiful day to travel" },
{ "NoneDayClear3", "You can feel the sun on some exposed skin" },
{ "NoneDayClear4", "You watch your shadow creep along the landscape" },
---
{ "NoneNightClear0", "The stars are endless" },
{ "NoneNightClear1", "The tales of the Magna Ge come to mind" },
{ "NoneNightClear2", "You feel small at the expanse of stars" },
{ "NoneNightClear3", "The moons remind you of Baar Dau" },
{ "NoneNightClear4", "Masser and Secunda illuminate your path" },
---
{ "NoneDayCloudy0", "The cloud cover shield the suns rays" },
{ "NoneDayCloudy1", "Strong winds move the clouds" },
{ "NoneDayCloudy2", "" },
{ "NoneDayCloudy3", "" },
{ "NoneDayCloudy4", "" },
---
{ "NoneNightCloudy0", "It is difficult to travel without some moonlight" },
{ "NoneNightCloudy1", "The darkness cloaks some movement" },
{ "NoneNightCloudy2", "" },
{ "NoneNightCloudy3", "" },
{ "NoneNightCloudy4", "" },
---
{ "NoneDayRainy0", "A bug scurries out from under your footstep" },
{ "NoneDayRainy1", "Tracks here suggest a recent ambush." },
{ "NoneDayRainy2", "" },
{ "NoneDayRainy3", "" },
{ "NoneDayRainy4", "" },
---
{ "NoneNightRainy0", "A miserable night for travel" },
{ "NoneNightRainy1", "You feel a cold stream down your neck" },
{ "NoneNightRainy2", "The drops fall in a rhythm" },
{ "NoneNightRainy3", "" },
{ "NoneNightRainy4", "" },
---
{ "NoneDaySnowy0", "There's evidence of a recent camp here." },
{ "NoneDaySnowy1", "The shining snow nearly blinds you" },
{ "NoneDaySnowy2", "" },
{ "NoneDaySnowy3", "" },
{ "NoneDaySnowy4", "" },
---
{ "NoneNightSnowy0", "Snowfall and darkness cover your tracks" },
{ "NoneNightSnowy1", "" },
{ "NoneNightSnowy2", "" },
{ "NoneNightSnowy3", "" },
{ "NoneNightSnowy4", "" },

--- ---
// City Weather:
{ "TownCityDayClear0", "You see a large shipment being delivered" },
{ "TownCityDayClear1", "Someone is cooking a vegetable stew." },
{ "TownCityDayClear2", "A fresh breeze brushes past you" },
{ "TownCityDayClear3", "" },
{ "TownCityDayClear4", "" },
---
{ "TownCityNightClear0", "You spot a cat sneaking around the corner" },
{ "TownCityNightClear1", "You hear someone running away" },
{ "TownCityNightClear2", "The smell of burning fireplaces fills the air." },
{ "TownCityNightClear3", "The stars call to all life on Nirn" },
{ "TownCityNightClear4", "" },
---
{ "TownCityDayCloudy0", "Two children run by playing with sticks" },
{ "TownCityDayCloudy1", "Someone eyes you over their shoulder" },
{ "TownCityDayCloudy2", "Some children are climbing trees" },
{ "TownCityDayCloudy3", "" },
{ "TownCityDayCloudy4", "" },
---
{ "TownCityNightCloudy0", "You can hear some of the city night life" },
{ "TownCityNightCloudy1", "" },
{ "TownCityNightCloudy2", "The streetlamps and windows light your path" },
{ "TownCityNightCloudy3", "Cloud cover invites those who wish to stay hidden" },
{ "TownCityNightCloudy4", "" },
---
{ "TownCityDayRainy0", "Your cloth feels heavy in the damp air" },
{ "TownCityDayRainy1", "Cityfolk look out their windows longingly" },
{ "TownCityDayRainy2", "Someone sighs, "More miserable rain."" },
{ "TownCityDayRainy3", "Some children are splashing in a puddle" },
{ "TownCityDayRainy4", "Someone slips in mud and gets laughed at" },
---
{ "TownCityNightRainy0", "The cityfolk shelter their belongings from the rain" },
{ "TownCityNightRainy1", "Sounds like someone is dealing with a leak" },
{ "TownCityNightRainy2", "You think you hear someone running" },
{ "TownCityNightRainy3", "" },
{ "TownCityNightRainy4", "" },
---
{ "TownCityDaySnowy0", "The falling snow relaxes you." },
{ "TownCityDaySnowy1", "Some children pretend they're smoking a pipe" },
{ "TownCityDaySnowy2", "The crunch of the snow is satisfying" },
{ "TownCityDaySnowy3", "" },
{ "TownCityDaySnowy4", "" },
---
{ "TownCityNightSnowy0", "The days footprints are covered partially by the snow" },
{ "TownCityNightSnowy1", "There are some suspicious tracks around that house" },
{ "TownCityNightSnowy2", "You hear roaring fires in the homes" },
{ "TownCityNightSnowy3", "You can hear echoes in the still air" },
{ "TownCityNightSnowy4", "The crunchy snow is loud under your feet" },

--- ---
// Hamlet Weather:
{ "TownHamletDayClear0", "The locals stop to greet you" },
{ "TownHamletDayClear1", "The smell of frying meat whets your appetite" },
{ "TownHamletDayClear2", "One of the locals greets you" },
{ "TownHamletDayClear3", "" },
{ "TownHamletDayClear4", "" },
---
{ "TownHamletNightClear0", "A cat scurries after a rodent" },
{ "TownHamletNightClear1", "A child peers through the window at the stars" },
{ "TownHamletNightClear2", "Smoke from the chimneys rise into the sky" },
{ "TownHamletNightClear3", "The night sky provides some illumination" },
{ "TownHamletNightClear4", "You spot a shadow moving in the distance" },
---
{ "TownHamletDayCloudy0", "A few neighbours are stopping to chat" },
{ "TownHamletDayCloudy1", "Some villagers glance in your direction" },
{ "TownHamletDayCloudy2", "Two children run by playing with sticks" },
{ "TownHamletDayCloudy3", "" },
{ "TownHamletDayCloudy4", "" },
---
{ "TownHamletNightCloudy0", "You keep an eye on the dark alleys" },
{ "TownHamletNightCloudy1", "The cloud cover creates moving shadows" },
{ "TownHamletNightCloudy2", "" },
{ "TownHamletNightCloudy3", "" },
{ "TownHamletNightCloudy4", "" },
---
{ "TownHamletDayRainy0", "Someone calls a dog in the distance" },
{ "TownHamletDayRainy1", "A woman indulges in a gifted flower" },
{ "TownHamletDayRainy2", "A merchant tries to sell the last of his wares" },
{ "TownHamletDayRainy3", "People peer at you out of their windows" },
{ "TownHamletDayRainy4", "A man slips and falls and people walk past" },
---
{ "TownHamletNightRainy0", "You see figures in the windows" },
{ "TownHamletNightRainy1", "A tavern will ease the gloom" },
{ "TownHamletNightRainy2", "The rain masks your footsteps" },
{ "TownHamletNightRainy3", "Someone moves in the distance" },
{ "TownHamletNightRainy4", "You hear someone trying a lock." },
---
{ "TownHamletDaySnowy0", "An old man with a cane nods at you" },
{ "TownHamletDaySnowy1", "The villagers bundle their clothing for warmth" },
{ "TownHamletDaySnowy2", "Some kids are throwing snowballs at each other" },
{ "TownHamletDaySnowy3", "Someone attempted to form snow into the shape of a man" },
{ "TownHamletDaySnowy4", "" },
---
{ "TownHamletNightSnowy0", "There's sure to be a warm fire and cold drink here" },
{ "TownHamletNightSnowy1", "The crunch of your footsteps echo off the houses" },
{ "TownHamletNightSnowy2", "The snow will soon cover everything in sight" },
{ "TownHamletNightSnowy3", "A horse shakes some snow off its head" },
{ "TownHamletNightSnowy4", "" },

--- ---
// Village Weather:
{ "TownVillageDayClear0", "A soft breeze flutters some fabric" },
{ "TownVillageDayClear1", "You see some travellers in the distance" },
{ "TownVillageDayClear2", "A cat lays in the shade" },
{ "TownVillageDayClear3", "A tavern worker is talking to the locals" },
{ "TownVillageDayClear4", "A shipment of goods is tended to" },
---
{ "TownVillageNightClear0", "The night sky inspires the adventurous" },
{ "TownVillageNightClear1", "Young children gaze at the constellations from their windows" },
{ "TownVillageNightClear2", "" },
{ "TownVillageNightClear3", "" },
{ "TownVillageNightClear4", "" },
---
{ "TownVillageDayCloudy0", "You smell roast vegetables and beef" },
{ "TownVillageDayCloudy1", "An old man is teaching his grandchildren how to identify plants" },
{ "TownVillageDayCloudy2", "A grandmother pours warm tea for those who want some" },
{ "TownVillageDayCloudy3", "" },
{ "TownVillageDayCloudy4", "" },
---
{ "TownVillageNightCloudy0", "You hear some soft chatter in the homes" },
{ "TownVillageNightCloudy1", "The chimney smoke seems to touch the clouds" },
{ "TownVillageNightCloudy2", "The sparse light helps you navigate these streets" },
{ "TownVillageNightCloudy3", "" },
{ "TownVillageNightCloudy4", "" },
---
{ "TownVillageDayRainy0", "Many of the locals are keeping out of the rain" },
{ "TownVillageDayRainy1", "A man slips and is helped to his feet by the locals" },
{ "TownVillageDayRainy2", "A local puts a jacket on his horse" },
{ "TownVillageDayRainy3", "" },
{ "TownVillageDayRainy4", "" },
---
{ "TownVillageNightRainy0", "You hope to find what you need here" },
{ "TownVillageNightRainy1", "A warm, dry bed would be welcome" },
{ "TownVillageNightRainy2", "" },
{ "TownVillageNightRainy3", "" },
{ "TownVillageNightRainy4", "" },
---
{ "TownVillageDaySnowy0", "You can hear some children playing in the snow" },
{ "TownVillageDaySnowy1", "The locals help each other clear the snow" },
{ "TownVillageDaySnowy2", "An old man sits pondering life" },
{ "TownVillageDaySnowy3", "A shipment of goods has arrived" },
{ "TownVillageDaySnowy4", "" },
---
{ "TownVillageNightSnowy0", "You're thankful to be around some civilization" },
{ "TownVillageNightSnowy1", "The promise of warmth draws you to the tavern" },
{ "TownVillageNightSnowy2", "The snow may bury this whole town" },
{ "TownVillageNightSnowy3", "" },
{ "TownVillageNightSnowy4", "" },

--- ---// Dungeon Weather:
{ "DungeonLabyrinthDayClear0", "The sun can't cleanse a place so evil" },
{ "DungeonLabyrinthDayClear1", "The gods weep at the sight of this place" },
{ "DungeonLabyrinthDayClear2", "" },
{ "DungeonLabyrinthDayClear3", "" },
{ "DungeonLabyrinthDayClear4", "" },
---
{ "DungeonLabyrinthNightClear0", "This place feels dark and deadly" },
{ "DungeonLabyrinthNightClear1", "You hear echoes of death" },
{ "DungeonLabyrinthNightClear2", "" },
{ "DungeonLabyrinthNightClear3", "" },
{ "DungeonLabyrinthNightClear4", "" },
---
{ "DungeonLabyrinthDayCloudy0", "Stale air bursts forth like a breath" },
{ "DungeonLabyrinthDayCloudy1", "A grotesque bug hisses and flies at you" },
{ "DungeonLabyrinthDayCloudy2", "The clouds billow and writhe" },
{ "DungeonLabyrinthDayCloudy3", "" },
{ "DungeonLabyrinthDayCloudy4", "" },
---
{ "DungeonLabyrinthNightCloudy0", "Not even moonlight falls on this hellish place" },
{ "DungeonLabyrinthNightCloudy1", "Cloud cover cloaks the dead" },
{ "DungeonLabyrinthNightCloudy2", "Darkness breaches the edge of your vision" },
{ "DungeonLabyrinthNightCloudy3", "" },
{ "DungeonLabyrinthNightCloudy4", "" },
---
{ "DungeonLabyrinthDayRainy0", "The rain cant wash away the filth" },
{ "DungeonLabyrinthDayRainy1", "The puddles are dirty and greasy" },
{ "DungeonLabyrinthDayRainy2", "The rain intensifies the stench" },
{ "DungeonLabyrinthDayRainy3", "" },
{ "DungeonLabyrinthDayRainy4", "" },
---
{ "DungeonLabyrinthNightRainy0", "The rain hides the sounds of footsteps" },
{ "DungeonLabyrinthNightRainy1", "Any amount of rainfall is preferable to this hellhole" },
{ "DungeonLabyrinthNightRainy2", "" },
{ "DungeonLabyrinthNightRainy3", "The smell is unlike anything you've experienced" },
{ "DungeonLabyrinthNightRainy4", "" },
---
{ "DungeonLabyrinthDaySnowy0", "Carnage lays just beneath this peaceful snow covering" },
{ "DungeonLabyrinthDaySnowy1", "You can just make out dead figures in the snow" },
{ "DungeonLabyrinthDaySnowy2", "Twisted shapes form in the dirty snow" },
{ "DungeonLabyrinthDaySnowy3", "The glare off the snow seeks to blind you" },
{ "DungeonLabyrinthDaySnowy4", "" },
---
{ "DungeonLabyrinthNightSnowy0", "The snow shatters like glass as you get closer" },
{ "DungeonLabyrinthNightSnowy1", "A shiver runs up your back" },
{ "DungeonLabyrinthNightSnowy2", "The echo of the snow crunching surrounds you" },
{ "DungeonLabyrinthNightSnowy3", "" },
{ "DungeonLabyrinthNightSnowy4", "" },

--- ---
{ "DungeonKeepDayClear0", "The day darkens near here" },
{ "DungeonKeepDayClear1", "The suns rays fall onto this dreary place" },
{ "DungeonKeepDayClear2", "" },
{ "DungeonKeepDayClear3", "" },
{ "DungeonKeepDayClear4", "" },
---
{ "DungeonKeepNightClear0", "The stars offer a warning of this place" },
{ "DungeonKeepNightClear1", "Eery moonlight illuminates the area" },
{ "DungeonKeepNightClear2", "" },
{ "DungeonKeepNightClear3", "" },
{ "DungeonKeepNightClear4", "" },
---
{ "DungeonKeepDayCloudy0", "You can smell rotting flesh" },
{ "DungeonKeepDayCloudy1", "The clouds twist above the dungeon" },
{ "DungeonKeepDayCloudy2", "" },
{ "DungeonKeepDayCloudy3", "" },
{ "DungeonKeepDayCloudy4", "" },
---
{ "DungeonKeepNightCloudy0", "The damp air is sickly" },
{ "DungeonKeepNightCloudy1", "Sounds echo and turn sinister" },
{ "DungeonKeepNightCloudy2", "" },
{ "DungeonKeepNightCloudy3", "" },
{ "DungeonKeepNightCloudy4", "" },
---
{ "DungeonKeepDayRainy0", "It smells like the dead" },
{ "DungeonKeepDayRainy1", "The rain feels heavy and grimy" },
{ "DungeonKeepDayRainy2", "A bleak day to tread these grounds" },
{ "DungeonKeepDayRainy3", "" },
{ "DungeonKeepDayRainy4", "" },
---
{ "DungeonKeepNightRainy0", "The rain is still preferable to this place" },
{ "DungeonKeepNightRainy1", "Steam rises off the ground near the dungeon" },
{ "DungeonKeepNightRainy2", "The rain tastes foul" },
{ "DungeonKeepNightRainy3", "" },
{ "DungeonKeepNightRainy4", "" },
---
{ "DungeonKeepDaySnowy0", "Strange figures jut out of the ground, covered by snow" },
{ "DungeonKeepDaySnowy1", "The daylight shimmers off the snow into your eyes" },
{ "DungeonKeepDaySnowy2", "Large footprints litter the snow" },
{ "DungeonKeepDaySnowy3", "" },
{ "DungeonKeepDaySnowy4", "" },
---
{ "DungeonKeepNightSnowy0", "The entrance may get snowed in" },
{ "DungeonKeepNightSnowy1", "The cold air from the dungeon is oppressive" },
{ "DungeonKeepNightSnowy2", "A spell was used here" },
{ "DungeonKeepNightSnowy3", "" },
{ "DungeonKeepNightSnowy4", "" },

--- ---
{ "DungeonRuinDayClear9", "The flowers look unwell here" },
{ "DungeonRuinDayClear9", "The Divines light shines on this sad place" },
{ "DungeonRuinDayClear9", "" },
{ "DungeonRuinDayClear9", "" },
{ "DungeonRuinDayClear9", "" },
---
{ "DungeonRuinNightClear9", "The bugs buzz around your ears" },
{ "DungeonRuinNightClear9", "A dark figure scampers away" },
{ "DungeonRuinNightClear9", "" },
{ "DungeonRuinNightClear9", "" },
{ "DungeonRuinNightClear9", "" },
---
{ "DungeonRuinDayCloudy0", "The wind wrestles you as you move" },
{ "DungeonRuinDayCloudy0", "The clouds form a weird pattern" },
{ "DungeonRuinDayCloudy0", "" },
{ "DungeonRuinDayCloudy0", "" },
{ "DungeonRuinDayCloudy0", "" },
---
{ "DungeonRuinNightCloudy0", "The air around the dungeon has a fine mist" },
{ "DungeonRuinNightCloudy0", "The clouds look discoloured" },
{ "DungeonRuinNightCloudy0", "" },
{ "DungeonRuinNightCloudy0", "" },
{ "DungeonRuinNightCloudy0", "" },
---
{ "DungeonRuinDayRainy0", "The air is rather stale" },
{ "DungeonRuinDayRainy0", "There's a rusted helmet with a hole in it" },
{ "DungeonRuinDayRainy0", "The drops are heavy on your shoulder" },
{ "DungeonRuinDayRainy0", "" },
{ "DungeonRuinDayRainy0", "" },
---
{ "DungeonRuinNightRainy0", "The air smells a little foul" },
{ "DungeonRuinNightRainy0", "It feels like you're being tapped on the shoulder" },
{ "DungeonRuinNightRainy0", "" },
{ "DungeonRuinNightRainy0", "" },
{ "DungeonRuinNightRainy0", "" },
---
{ "DungeonRuinDaySnowy0", "An adventurers horse was parked here" },
{ "DungeonRuinDaySnowy0", "The snow covers some animal tracks" },
{ "DungeonRuinDaySnowy0", "" },
{ "DungeonRuinDaySnowy0", "" },
{ "DungeonRuinDaySnowy0", "" },
---
{ "DungeonRuinNightSnowy0", "The snow hides movement in the distance" },
{ "DungeonRuinNightSnowy0", "A frozen body is buried in the snow" },
{ "DungeonRuinNightSnowy0", "" },
{ "DungeonRuinNightSnowy0", "" },
{ "DungeonRuinNightSnowy0", "" },

--- ---// Graveyard Weather:
{ "GraveyardDayClear9", "The plantlife looks sick" },
{ "GraveyardDayClear9", "There seem to be faces in the plantgrowth" },
{ "GraveyardDayClear9", "" },
{ "GraveyardDayClear9", "" },
{ "GraveyardDayClear9", "" },
---
{ "GraveyardNightClear9", "You hear a distant yell" },
{ "GraveyardNightClear9", "Some animals pick at exposed bones" },
{ "GraveyardNightClear9", "The Gods call lost spirits into the expanse" },
{ "GraveyardNightClear9", "" },
{ "GraveyardNightClear9", "" },
---
{ "GraveyardDayCloudy0", "The locals say ghosts can be seen in the morning fog" },
{ "GraveyardDayCloudy0", "Shadows move above the clouds" },
{ "GraveyardDayCloudy0", "" },
{ "GraveyardDayCloudy0", "" },
{ "GraveyardDayCloudy0", "" },
---
{ "GraveyardNightCloudy0", "You smell a rotten stench" },
{ "GraveyardNightCloudy0", "The clouds have picked up speed" },
{ "GraveyardNightCloudy0", "" },
{ "GraveyardNightCloudy0", "" },
{ "GraveyardNightCloudy0", "" },
---
{ "GraveyardDayRainy0", "Worms are writhing near you" },
{ "GraveyardDayRainy0", "Years of rain has eroded the gravestones" },
{ "GraveyardDayRainy0", "" },
{ "GraveyardDayRainy0", "" },
{ "GraveyardDayRainy0", "" },
---
{ "GraveyardNightRainy0", "Stale water drips in your eyes" },
{ "GraveyardNightRainy0", "The rain doused a lit torch" },
{ "GraveyardNightRainy0", "There is a small gravestone with a childs toy on it" },
{ "GraveyardNightRainy0", "" },
{ "GraveyardNightRainy0", "" },
---
{ "GraveyardDaySnowy0", "A shiver runs up your back" },
{ "GraveyardDaySnowy0", "There is some melting snow over a grave" },
{ "GraveyardDaySnowy0", "" },
{ "GraveyardDaySnowy0", "" },
{ "GraveyardDaySnowy0", "" },
---
{ "GraveyardNightSnowy0", "The wind is colder than usual" },
{ "GraveyardNightSnowy0", "There are strange footsteps in the snow" },
{ "GraveyardNightSnowy0", "" },
{ "GraveyardNightSnowy0", "" },
{ "GraveyardNightSnowy0", "" },

            #endregion

            #region Day / Night texts:


           // Wilderness Day/Night:
{ "NoneDay0", "The Iliac bay expands before you" },
{ "NoneDay1", "You see some travellers on the horizon" },
{ "NoneDay2", "The distant landscape has inspired adventure for generations" },
{ "NoneDay3", "" },
{ "NoneDay4", "" },
{ "NoneDay5", "" },
{ "NoneDay6", "" },
{ "NoneDay7", "" },
{ "NoneDay8", "" },
{ "NoneDay9", "" },
---
{ "NoneNight0", "The night can be dangerous for some" },
{ "NoneNight1", "You think you hear movement behind you" },
{ "NoneNight2", "Shadows shift in the distance" },
{ "NoneNight3", "Beings with ill intent lurk in the night" },
{ "NoneNight4", "Two animals are fighting in the distance" },
{ "NoneNight5", "Nirn weaves a fateful melody of Mnemoli " },
{ "NoneNight6", "" },
{ "NoneNight7", "" },
{ "NoneNight8", "" },
{ "NoneNight9", "" },
--- ---
// City Day/Night:
{ "TownCityDay0", "You hear some neighbours arguing" },
{ "TownCityDay1", "A young one says "you smell!" and runs off" },
{ "TownCityDay2", "You catch the scent of a warm meal" },
{ "TownCityDay3", "A homeless man holds his hand out to strangers" },
{ "TownCityDay4", "Someone is playing a tune" },
{ "TownCityDay5", "You hear a merchant pushing his wares" },
{ "TownCityDay6", "Someone shouts for the guards" },
{ "TownCityDay7", "Someone calls out, “Fresh brewed ale!”" },
{ "TownCityDay8", "An old man tells a tale to some youngins" },
{ "TownCityDay9", "" },
---
{ "TownCityNight0", "The cityfolk secure their belongings at night" },
{ "TownCityNight1", "Someone is humming a tune" },
{ "TownCityNight2", "You hear someone fiddling with a lock." },
{ "TownCityNight3", "Distant guards call for a criminal to halt" },
{ "TownCityNight4", "" },
{ "TownCityNight5", "You can hear some drunken patrons" },
{ "TownCityNight6", "Someone is snoring loudly" },
{ "TownCityNight7", "You see someone watching you from their window" },
{ "TownCityNight8", "The houses are filled with life and laughter" },
{ "TownCityNight9", "" },
--- ---
// Hamlet Day/Night:
{ "TownHamletDay0", "You see a friendly face" },
{ "TownHamletDay1", "Someone is chopping wood" },
{ "TownHamletDay2", "A villager yawns as they work" },
{ "TownHamletDay3", "A waft of exciting spices find your nose" },
{ "TownHamletDay4", "" },
{ "TownHamletDay5", "A young one trips as they run by" },
{ "TownHamletDay6", "" },
{ "TownHamletDay7", "A horse neighs and scrapes the ground" },
{ "TownHamletDay8", "A child looks at you with awe" },
{ "TownHamletDay9", "A merchant tries to get your attention" },
---
{ "TownHamletNight0", "There is a group of youths talking nearby" },
{ "TownHamletNight1", "Someone is smoking something" },
{ "TownHamletNight2", "" },
{ "TownHamletNight3", "You hear some laughter in a house" },
{ "TownHamletNight4", "You hear some restless animals" },
{ "TownHamletNight5", "" },
{ "TownHamletNight6", "" },
{ "TownHamletNight7", "An old woman scowls at you and slams the door" },
{ "TownHamletNight8", "" },
{ "TownHamletNight9", "A young boy sneaks out of his house" },
--- ---
// Village Day/Night:
{ "TownVillageDay0", "One of the locals smiles at you" },
{ "TownVillageDay1", "" },
{ "TownVillageDay2", "The locals quiet as you pass" },
{ "TownVillageDay3", "The smell of fresh bread fills the air" },
{ "TownVillageDay4", "" },
{ "TownVillageDay5", "Someone is drying some fruit with smoke" },
{ "TownVillageDay6", "Some neighbours are laughing together" },
{ "TownVillageDay7", "A child asks a neighbour for some sugar" },
{ "TownVillageDay8", "Local children sprint past you in play" },
{ "TownVillageDay9", "A local is cleaning their window" },
---
{ "TownVillageNight0", "A pig got into some cabbages" },
{ "TownVillageNight1", "A quiet walk in peaceful streets" },
{ "TownVillageNight2", "You can hear someones fire crackling" },
{ "TownVillageNight3", "The street lights bounce off the houses" },
{ "TownVillageNight4", "" },
{ "TownVillageNight5", "Quite a cozy looking place" },
{ "TownVillageNight6", "You nearly trip on a cat" },
{ "TownVillageNight7", "A child has left her toy here for the next day" },
{ "TownVillageNight8", "" },
{ "TownVillageNight9", "" },
--- ---
// Tavern Day/Night:
{ "TavernDay0", "A few adventurers have just left" },
{ "TavernDay1", "A plate is smashed followed by laughter" },
{ "TavernDay2", "Someone was passed out here recently" },
{ "TavernDay3", "A man is walking gingerly, covering his eyes" },
{ "TavernDay4", "A barhand is carrying some meat, ready to be eaten" },
{ "TavernDay5", "The patrons scare the birds" },
{ "TavernDay6", "A worker sweeps the entrance" },
{ "TavernDay7", "" },
---
{ "TavernNight0", "A drunk figure stumbles off" },
{ "TavernNight1", "You hear the patrons bellowing a tune" },
{ "TavernNight2", "You pass a questionable puddle" },
{ "TavernNight3", "You can smell the fire, feast and foam" },
{ "TavernNight4", "Shapes move in the windows, a lively tavern" },
{ "TavernNight5", "A man stumbles up to you and falls down" },
{ "TavernNight6", "" },
{ "TavernNight7", "" },
--- ---
// Farms Day/Night:
{ "HomeFarmsDay0", "Everyone is out and working" },
{ "HomeFarmsDay1", "They've been working since dawn" },
{ "HomeFarmsDay2", "A rather attractive worker smiles at you" },
{ "HomeFarmsDay3", "The animals make their presence known" },
{ "HomeFarmsDay4", "A slight breeze sways the crops" },
{ "HomeFarmsDay5", "One of the workers is jealous of his friends new hoe" },
---
{ "HomeFarmsNight0", "You can smell some decomposing vegetables" },
{ "HomeFarmsNight1", "You smelled this farmstead before you saw it" },
{ "HomeFarmsNight2", "You hear the animals settling down" },
{ "HomeFarmsNight3", "you see some wagon tracks nearby" },
{ "HomeFarmsNight4", "The farmhands have left for the night" },
--- ---
// WealthyHomes Day/Night:
{ "HomeWealthyDay0", "The sun shines on the polished metals" },
{ "HomeWealthyDay1", "This person has afforded a comfortable life" },
{ "HomeWealthyDay2", "Some of the people seem very annoyed by your presence" },
{ "HomeWealthyDay3", "The children play in fine fabrics with gold buckles" },
{ "HomeWealthyDay4", "A silver caraff is being used as a flower pot" },
{ "HomeWealthyDay5", "Your arrival is met with some surprise" },
{ "HomeWealthyDay6", "A worker tends to the garden" },
{ "HomeWealthyDay7", "Even the workers have quality attire" },
{ "HomeWealthyDay8", "You spot a young woman wearing nordic silk" },
{ "HomeWealthyDay9", "The children carry trinkets you've never seen before" },
---
{ "HomeWealthyNight0", "A thief's dream" },
{ "HomeWealthyNight1", "The animals are kept in a strong pen" },
{ "HomeWealthyNight2", "A cat slinks by with a brass bell on its collar" },
{ "HomeWealthyNight3", "These people must pay dearly for protection" },
{ "HomeWealthyNight4", "A pony can be heard nearby" },
--- ---
// PoorHomes Day/Night:
{ "HomePoorDay0", "This is a rather depressing area" },
{ "HomePoorDay1", "You watch your step among the droppings" },
{ "HomePoorDay2", "Someone is heard coughing" },
{ "HomePoorDay3", "There's a poorly written sign" },
{ "HomePoorDay4", "You can see where a wagon trail used to exist" },
{ "HomePoorDay5", "There's garbage strewn about" },
{ "HomePoorDay6", "Holes in the roof are patched haphazardly" },
{ "HomePoorDay7", "" },
{ "HomePoorDay8", "" },
{ "HomePoorDay9", "" },
---
{ "HomePoorNight0", "A sneeze is heard from the house" },
{ "HomePoorNight1", "Something doesnt smell good" },
{ "HomePoorNight2", "Stray animals scamper about" },
{ "HomePoorNight3", "You think something was buried here" },
{ "HomePoorNight4", "You hear someone crying" },
--- ---
// PlayerShip Day/Night:
{ "HomeYourShipsDay0", "You see some movement in the distance" },
{ "HomeYourShipsDay1", "You hear the wind whipping the sails" },
{ "HomeYourShipsDay2", "" },
{ "HomeYourShipsDay3", "" },
{ "HomeYourShipsDay4", "" },
---
{ "HomeYourShipsNight0", "The bugs have made their way on board" },
{ "HomeYourShipsNight1", "You can see some city lights" },
{ "HomeYourShipsNight2", "The sails flap lazily in the breeze" },
{ "HomeYourShipsNight3", "" },
{ "HomeYourShipsNight4", "" },
--- ---
// Graveyard Day/Night:
{ "GraveyardDay0", "Some decorations wilt on a tombstone" },
{ "GraveyardDay1", "A makeshift grave was dug here" },
{ "GraveyardDay2", "A shovel has been discarded nearby" },
{ "GraveyardDay3", "This engraving is from ages ago" },
{ "GraveyardDay4", "You feel as if you aren't alone" },
---
{ "GraveyardNight0", "Some fresh flowers rest on a grave" },
{ "GraveyardNight1", "Something is making a thumping noise" },
{ "GraveyardNight2", "Something is running away" },
{ "GraveyardNight3", "Pray the dead stay dead" },
{ "GraveyardNight4", "One of the graves has some fresh turned earth" },
--- ---
// Coven Day/Night:
{ "CovenDay0", "There is a bubbling pot" },
{ "CovenDay1", "Some potions are stashed out of the light" },
{ "CovenDay2", "They stare at you" },
{ "CovenDay3", ""The Stricture" can be read on a piece of parchment" },
{ "CovenDay4", "Access to great power can be obtained here" },
{ "CovenDay5", "A thick smoke rises" },
{ "CovenDay6", "" },
{ "CovenDay7", "" },
{ "CovenDay8", "" },
---
{ "CovenNight0", "A strange shadow drifts away" },
{ "CovenNight1", "A dark energy lingers here" },
{ "CovenNight2", "Potions glow faintly under some cloth" },
{ "CovenNight3", "Ancient rituals disturb the locals" },
{ "CovenNight4", "A witch has succumb to a trance" },
{ "CovenNight5", "They speak not, but you hear" },
{ "CovenNight6", "An arrid smoke lingers" },
{ "CovenNight7", "" },
{ "CovenNight8", "" },
--- ---
// Temple Day/Night:
{ "ReligionTempleDay0", "The residents recite religious texts" },
{ "ReligionTempleDay1", "Some children are wearing ceremonial garb" },
{ "ReligionTempleDay2", "Pilgrims are huddled near a temple member" },
{ "ReligionTempleDay3", "A young child gestures to the sky" },
{ "ReligionTempleDay4", "A beggar receives some aid" },
{ "ReligionTempleDay5", "Some chimes signal a prayer" },
{ "ReligionTempleDay6", "People speak softly near the temple" },
{ "ReligionTempleDay7", "An elder is reading a holy book" },
{ "ReligionTempleDay8", "The worshippers seem to float as they walk" },
{ "ReligionTempleDay9", "A woman is stitching some religious attire" },
---
{ "ReligionTempleNight0", "A pipe is being smoked" },
{ "ReligionTempleNight1", "You hear people chanting" },
{ "ReligionTempleNight2", "The windows have religious markings" },
{ "ReligionTempleNight3", "You hear laughter in one of the houses" },
{ "ReligionTempleNight4", "You smell a spice pie" },
{ "ReligionTempleNight5", "Chanting can be heard "\"Obey your Emperor\"" },
{ "ReligionTempleNight6", "Chanting can be heard "Study the Covenants"" },
{ "ReligionTempleNight7", "Chanting can be heard "Worship the Eight"" },
{ "ReligionTempleNight8", "Chanting can be heard "Do your duty"" },
{ "ReligionTempleNight9", "Chanting can be heard "Heed the commands of the Saints and Priests"" },
--- ---
// Cult Day/Night:
{ "ReligionCultDay0", "The day illuminates all deeds" },
{ "ReligionCultDay1", "Special herbs are being burned" },
{ "ReligionCultDay2", "The years have aged this place" },
{ "ReligionCultDay3", "You hear some magic" },
{ "ReligionCultDay4", "This building is contorted" },
---
{ "ReligionCultNight0", "A low humming can be heard" },
{ "ReligionCultNight1", "An unusual smell lingers in the air" },
{ "ReligionCultNight2", "Many voices stop at once" },
{ "ReligionCultNight3", "A distant laugh echoes past" },
{ "ReligionCultNight4", "A blade is being sharpened" },
--- ---
// Dungeon Day/Night:
{ "DungeonLabyrinthDay0", "The daylight reveals blood stains" },
{ "DungeonLabyrinthDay1", "There is a shredded cloak on the ground" },
{ "DungeonLabyrinthDay2", "scraps of metal and bone are everywhere" },
{ "DungeonLabyrinthDay3", "A warning is scratched onto the entrance" },
{ "DungeonLabyrinthDay4", "This religious marking has been corrupted" },
{ "DungeonLabyrinthDay5", "You hear a thousand whispers beneath you" },
{ "DungeonLabyrinthDay6", "Many travellers have fallen here" },
{ "DungeonLabyrinthDay7", "You feel a strange draw to the dungeon entrance" },
{ "DungeonLabyrinthDay8", "Anguish shapes the minds of those who enter" },
{ "DungeonLabyrinthDay9", "" },
---
{ "DungeonLabyrinthNight0", "You feel bones underfoot" },
{ "DungeonLabyrinthNight1", "Ghostly warnings find your ears" },
{ "DungeonLabyrinthNight2", "This place tests the resolve of mortals" },
{ "DungeonLabyrinthNight3", "The forces of evil lurk here" },
{ "DungeonLabyrinthNight4", "" },
{ "DungeonLabyrinthNight5", "A gods forsaken oblivion hole" },
{ "DungeonLabyrinthNight6", "A brutal death flashes in your mind" },
{ "DungeonLabyrinthNight7", "You hear a desperate cry from the deep" },
{ "DungeonLabyrinthNight8", "The entrance is cloaked in the night" },
{ "DungeonLabyrinthNight9", "" },
--- ---

{ "DungeonKeepDay0", "Ritual markings are to protect those who tread" },
{ "DungeonKeepDay1", "Many adventurers fall pray to these depths" },
{ "DungeonKeepDay2", "There are some tracks leading into the dungeon" },
{ "DungeonKeepDay3", "A book of destruction magic is partially burned" },
{ "DungeonKeepDay4", "Blood was spilled recently" },
{ "DungeonKeepDay5", "A tribute is left for the dead." },
{ "DungeonKeepDay6", "Something big was dragged away from here" },
{ "DungeonKeepDay7", "There is a ripped cloak on the ground" },
{ "DungeonKeepDay8", "There is a great sadness here" },
{ "DungeonKeepDay9", "An inscription reads "may The Divines protect you"" },
---
{ "DungeonKeepNight0", "You think you hear something below" },
{ "DungeonKeepNight1", "Only the hearty survive" },
{ "DungeonKeepNight2", "The air is deadly still" },
{ "DungeonKeepNight3", "You feel watched" },
{ "DungeonKeepNight4", "Birds call out a warning" },
{ "DungeonKeepNight5", "Your senses perk up" },
{ "DungeonKeepNight6", "Visions of Oblivion flash in your mind" },
{ "DungeonKeepNight7", "The darkness hides the entrance" },
{ "DungeonKeepNight8", "" },
{ "DungeonKeepNight9", "" },
--- ---

{ "DungeonRuinDay0", "Adventurers have been here recently" },
{ "DungeonRuinDay1", "Someone was camping nearby" },
{ "DungeonRuinDay2", "These religious markings are rather fresh" },
{ "DungeonRuinDay3", "Someone tried to draw a map" },
{ "DungeonRuinDay4", "The door is ajar" },
{ "DungeonRuinDay5", "Someone had their wagon nearby" },
{ "DungeonRuinDay6", "Birds chirp and fly overhead" },
{ "DungeonRuinDay7", "What danger resides here?" },
{ "DungeonRuinDay8", "You think you hear something" },
{ "DungeonRuinDay9", "A broken sword is discarded nearby" },
---
{ "DungeonRuinNight0", "There's an odd sound..." },
{ "DungeonRuinNight1", "The air is musty" },
{ "DungeonRuinNight2", "Some bats squeak overhead" },
{ "DungeonRuinNight3", "The darkness is cloaking the entrance" },
{ "DungeonRuinNight4", "Someone discarded a used potion bottle" },
{ "DungeonRuinNight5", "You think you see someone..." },
{ "DungeonRuinNight6", "" },
{ "DungeonRuinNight7", "" },
{ "DungeonRuinNight8", "" },
{ "DungeonRuinNight9", "" },

            #endregion

            #region Dungeon texts:

            // Dungeon: Crypt
{ "Crypt0", "You sense something creeping behind you."}   ,
{ "Crypt1", "A gust of cold air blows past you."},
{ "Crypt2", "Was that a werewolf howl?"},
{ "Crypt3", "A beetle crosses your path."},
{ "Crypt4", "The air here is very stiff."},
{ "Crypt5", "This place smells strongly of death."},
{ "Crypt6", "You hear very faint whispers."},
{ "Crypt7", ""},
{ "Crypt8", "Tiny rodents scamper away from you."},
{ "Crypt9", ""},

            // Dungeon: OrcStronghold
{ "OrcStronghold0", "You notice broken fragments of a weapon."},
{ "OrcStronghold1", "This place smells terribly of orc."},
{ "OrcStronghold2", "The ground is smoothed here by dragged bodies."},
{ "OrcStronghold3", "Orcs seem to have slept here often."},
{ "OrcStronghold4", "You see writing in some primitive Orcish script."},
{ "OrcStronghold5", "Someone cries for help, far away."},
{ "OrcStronghold6", "Bits of fur and bone litter this area."},

            // Dungeon: HumanStronghold
{ "HumanStronghold0", "You hear the distant shot of an arrow."},
{ "HumanStronghold1", "Something rustles about."},
{ "HumanStronghold2", "You see unfamiliar markings scratched here."},
{ "HumanStronghold3", "Something flees from you."},
{ "HumanStronghold4", "The smell of death fills the air."},
{ "HumanStronghold5", "You smell burnt wood."},
{ "HumanStronghold6", "You vaguely smell ale."},
{ "HumanStronghold7", "Things are deathly quiet here."},
{ "HumanStronghold8", "A sigil is drawn here."},
{ "HumanStronghold9", "You could swear you hear whispers."},

            // Dungeon: Prison
{ "Prison0", "Scrawlings nearby plead for release." },
{ "Prison1", "You see tormented scribblings nearby." },
{ "Prison2", "The scent of a rotting corpse gathers here." },
{ "Prison3", "A broken key lies on the ground." },
{ "Prison4", "You notice tally marks scratched nearby." },
{ "Prison5", "Was that someone calling for help?" },
{ "Prison6", "You feel as if someone is watching you." },
{ "Prison7", "You could swear you just heard movement from afar." },
{ "Prison8", "Someone tried digging here." },
{ "Prison9", "Someone scratched an inaccurate map here." },

            // Dungeon: Desecrated Temple
{ "DesecratedTemple0", "You sense strong magic in the air." },
{ "DesecratedTemple1", "You see a prayer to Kynareth scrawled here." },
{ "DesecratedTemple2", "Someone scratched a prayer to Stendarr here." },
{ "DesecratedTemple3", "The feeling of death is overwhelming here." },
{ "DesecratedTemple4", "An upwelling of magic gathers near you." },
{ "DesecratedTemple5", "A hateful presence is nearby." },
{ "DesecratedTemple6", "Unholy energies permeate this area." },
{ "DesecratedTemple7", "Your thoughts are filled with daedra." },

            // Dungeon: Mine
{ "Mine0", "This ground is well worn." },
{ "Mine1", "Someone scratched several lines here." },
{ "Mine2", "Many footsteps have worn this ground smooth." },
{ "Mine3", "You notice writing in some kind of code." },
{ "Mine4", "You hear footsteps move away." },
{ "Mine5", "The ground is unusually warm here." },
{ "Mine6", "Tiny rodents flee from you." },
{ "Mine7", "A fly buzzes around your ear." },
{ "Mine8", "Someone tried to dig here." },
{ "Mine8", "Something pounds a surface far away." },


            // Dungeon: Natural Cave
{ "NaturalCave0", "You hear a cloud of bats flutter away." },
{ "NaturalCave1", "Old bear claws lie here." },
{ "NaturalCave2", "A snake crosses your path." },
{ "NaturalCave3", "Something tiny flees from you." },
{ "NaturalCave4", "You hear something rustling about." },
{ "NaturalCave5", "A moth flutters by." },
{ "NaturalCave6", "You see some wolf fur here." },
{ "NaturalCave7", "" },
{ "NaturalCave8", "Some whiskers litter the ground." },
{ "NaturalCave9", "" },

            // Dungeon: Coven
{ "Coven0", "Someone is watching you from afar." },
{ "Coven1", "You hear whispering." },
{ "Coven2", "Chanting echoes from far off." },
{ "Coven3", "You feel very dark energies here." },
{ "Coven4", "You wipe some oddly-colored dust from your face." },
{ "Coven5", "A small spider skitters in front of you." },
{ "Coven6", "" },
{ "Coven7", "This area smells of something burning." },
{ "Coven8", "" },
{ "Coven9", "You can’t shake the feeling of being watched." },

            // Dungeon: VampireHaunt
{ "VampireHaunt0", "You hear faint rustling." },
{ "VampireHaunt1", "Indistinct hissing comes from afar." },
{ "VampireHaunt2", "You smell blood." },
{ "VampireHaunt3", "A body was recently dragged through here." },
{ "VampireHaunt4", "The air here is disturbed." },
{ "VampireHaunt5", "Unintelligible markings cover the ground." },
{ "VampireHaunt6", "You notice a plea for help written here." },
{ "VampireHaunt7", "You see shards of a glass bottle mixed with blood." },
{ "VampireHaunt8", "A cold gust of air catches you off guard." },
{ "VampireHaunt9", "You smell death. Lots of it." },

            // Dungeon: Laboratory
{ "Laboratory0", "You see mineral deposits from a ruined atronach." },
{ "Laboratory1", "You notice rudimentary notes." },
{ "Laboratory2", "Unintelligible markings dot the ground." },
{ "Laboratory3", "You see some notes, thoroughly scratched out." },
{ "Laboratory4", "You feel concentrated magical forces." },
{ "Laboratory5", "The air grows very warm here." },
{ "Laboratory6", "The air here suddenly turns cold." },
{ "Laboratory7", "You sense volatile magicka in this area." },
{ "Laboratory8", "" },
{ "Laboratory9", "" },

            // Dungeon: HarpyNest
{ "HarpyNest0", "" },
{ "HarpyNest1", "The stench of harpy is unbearable here." },
{ "HarpyNest2", "You avoid stepping in harpy droppings." },
{ "HarpyNest3", "Faint echoes of cawing fill the air." },
{ "HarpyNest4", "Caustic magicka surround you momentarily." },
{ "HarpyNest5", "A worm crawls across your foot." },
{ "HarpyNest6", "The ground and walls bear faint scratch marks." },
{ "HarpyNest7", "Is something watching you..?" },
{ "HarpyNest8", "The stench here is truly awful." },

            // Dungeon: RuinedCastle
{ "RuinedCastle0", "You hear the distant shot of an arrow."},
{ "RuinedCastle1", "Something rustles about."},
{ "RuinedCastle2", "You see unfamiliar markings scratched here."},
{ "RuinedCastle3", "Something flees from you."},
{ "RuinedCastle4", "The smell of death fills the air."},
{ "RuinedCastle5", "You smell burnt wood."},
{ "RuinedCastle6", "You vaguely smell ale."},
{ "RuinedCastle7", "Things are deathly quiet here."},
{ "RuinedCastle8", "A sigil is drawn here."},
{ "RuinedCastle9", "You could swear you hear whispers."},

            // Dungeon: SpiderNest
{ "SpiderNest0", "Webs fill the cracks in the wall"},
{ "SpiderNest1", "A tiny spider skitters across the ground."},
{ "SpiderNest2", "You feel as though something is crawling above you."},
{ "SpiderNest3", "Something is scratching a surface nearby."},
{ "SpiderNest4", "The floor is slightly sticky"},
{ "SpiderNest5", ""},
{ "SpiderNest6", "You brush off a small spider."},
{ "SpiderNest7", "Eight tiny legs move across your feet."},
{ "SpiderNest8", "Something hisses in the distance."},
{ "SpiderNest9", "A small spider crawls out from among your possessions."},

            // Dungeon: GiantStronghold
{ "GiantStronghold0", "Many feet have smoothed the ground here."},
{ "GiantStronghold1", "The stench of unbathed skin fills the air."},
{ "GiantStronghold2", "Tiger whiskers litter this area."},
{ "GiantStronghold3", "This area smells of fur."},
{ "GiantStronghold4", "You think you hear lumbering steps."},
{ "GiantStronghold5", "Some giant used this area as a latrine."},
{ "GiantStronghold6", "Your movement has stirred up some fallen giant hair."},
{ "GiantStronghold7", "The ground shakes momentarily."},
{ "GiantStronghold8", "The ground shakes as something lumbers about."},

            // Dungeon: DragonsDen
{ "DragonsDen0", "You see wilted dragon scales."},
{ "DragonsDen1", "The floor here has been hardened by heat."},
{ "DragonsDen2", "There are scratches on the walls"},
{ "DragonsDen3", "A symbol of Akatosh is drawn in blood"},
{ "DragonsDen4", "You are reminded of Akavir"},
{ "DragonsDen5", ""},
{ "DragonsDen6", ""},
{ "DragonsDen7", "You smell smoke"},
{ "DragonsDen8", "A beetle scampers over your foot."},
{ "DragonsDen9", ""},

            // Dungeon: BarbarianStronghold
{ "BarbarianStronghold0", "You hear the distant shot of an arrow."},
{ "BarbarianStronghold1", "Something rustles about."},
{ "BarbarianStronghold2", "You see unfamiliar markings scratched here."},
{ "BarbarianStronghold3", "Something flees from you."},
{ "BarbarianStronghold4", "The smell of death fills the air."},
{ "BarbarianStronghold5", "You smell burnt wood."},
{ "BarbarianStronghold6", "You vaguely smell ale."},
{ "BarbarianStronghold7", "Things are deathly quiet here."},
{ "BarbarianStronghold8", "A sigil is drawn here."},
{ "BarbarianStronghold9", "You could swear you hear whispers."},

            // Dungeon: VolcanicCaves
{ "VolcanicCaves0", "You feel some vents of steam under the ground."},
{ "VolcanicCaves1", "The air is moving quickly here."},
{ "VolcanicCaves2", "A warm draft blows by."},
{ "VolcanicCaves3", "The earth rumbles softly."},
{ "VolcanicCaves4", ""},
{ "VolcanicCaves5", "You smell a whiff of sulfur."},
{ "VolcanicCaves6", "This area smells of charcoal."},
{ "VolcanicCaves7", "A summoning sigil was drawn and erased here."},
{ "VolcanicCaves8", "The air suddenly grows still."},
{ "VolcanicCaves9", "You smell something burning."},

            // Dungeon: ScorpionNest
{ "ScorpionNest0", "Tiny bits of animal corpses litter this area."},
{ "ScorpionNest1", "You see the remains of molted skin."},
{ "ScorpionNest2", "Flies buzz near you."},
{ "ScorpionNest3", ""},
{ "ScorpionNest4", ""},
{ "ScorpionNest5", "A small rat scampers away."},
{ "ScorpionNest6", "A tiny scorpion crawls out from your possessions."},
{ "ScorpionNest7", "The air is still here."},
{ "ScorpionNest8", ""},
{ "ScorpionNest9", "The insects near you dissipate."},

            // Dungeon: Cemetery
{ "Cemetery0", "A beetle creeps over your foot."},
{ "Cemetery1", "Did the ground just move?"},
{ "Cemetery2", "You smell decomposing bodies."},
{ "Cemetery3", "The air is tense here."},
{ "Cemetery4", "You sense something staring at you."},
{ "Cemetery5", "Faint whispers fill the air."},
{ "Cemetery6", "You feel unwelcome here."},
{ "Cemetery7", "You feel the gaze of the dead upon you."},
{ "Cemetery8", "Someone attempted to dig the ground here."},
{ "Cemetery9", "Bones clatter about faintly."}

            #endregion
        };

    }
}