// Project:         RoleplayRealism mod for Daggerfall Unity (http://www.dfworkshop.net)
// Copyright:       Copyright (C) 2022 Regnier
// License:         MIT License (http://www.opensource.org/licenses/mit-license.php)
// Author:          Regnier

using System.Collections;

namespace AmbientText
{
    public class AmbientText
    {
        /* Keys are in the following format, and if a key is not present no msg is displayed.
         *  Inside dungeon: <dungeonType><0-9>
         *  Outside:        <locType><climate><0-9>
         *                  <locType><dayNight><0-9>
         *                  <locType><dayNight><weather><0-9>
         * Where:
         *  locType  = None,TownCity,TownHamlet,TownVillage,HomeFarms,DungeonLabyrinth,ReligionTemple,Tavern,DungeonKeep,HomeWealthy,ReligionCult,DungeonRuin,HomePoor,Graveyard,Coven,HomeYourShips
         *  climate  = Desert, Swamp, Woods, Mountains, Ocean
         *  dayNight = Day, Night
         *  weather  = Clear, Cloudy, Rainy, Snowy
         *  dungeonType = Crypt,OrcStronghold,HumanStronghold,Prison,DesecratedTemple,Mine,NaturalCave,Coven,VampireHaunt,Laboratory,HarpyNest,RuinedCastle,SpiderNest,GiantStronghold,DragonsDen,BarbarianStronghold,VolcanicCaves,ScorpionNest,Cemetery
         */
        internal static IDictionary AmbientTexts = new Hashtable()
        {
            #region Climate texts:

            // Wilderness climates:
            { "NoneDesert0", "The sand here grows shallow." },
            { "NoneDesert1", "There are some dried bones under the sand here." },
            { "NoneDesert2", "There's evidence of a recent camp here." },
            { "NoneDesert3", "A tiny lizard scampers about." },
            { "NoneDesert4", "A snake submerges in the sand." },
            { "NoneDesert5", "There are scorpion tracks here." },
            { "NoneDesert6", "Is that werewolf fur?" },
            { "NoneDesert7", "You see some footprints in the sand." },
            { "NoneDesert8", "A baby scorpion crosses your path." },
            { "NoneDesert9", "You squint to keep the sand from your eyes" },

            { "NoneSwamp0", "Someone recently burned oil here." },
            { "NoneSwamp1", "A horse neighs in the distance." },
            { "NoneSwamp2", "You see tattered clothing." },
            { "NoneSwamp3", "Tracks here suggest a recent ambush." },
            { "NoneSwamp4", "This ground emits gases." },
            { "NoneSwamp5", "Your feet are covered in mud." },
            { "NoneSwamp6", "An argonian was here recently" },
            { "NoneSwamp7", "You breath the thick, damp air." },
            { "NoneSwamp8", "The bugs are unbearable." },
            { "NoneSwamp9", "You stub your toe on a rotten stump." },

            { "NoneWoods0", "You smell woodsmoke." },
            { "NoneWoods1", "A horse neighs in the distance." },
            { "NoneWoods2", "This arboreal smell is very relaxing." },
            { "NoneWoods3", "Twigs snap underneath you." },
            { "NoneWoods4", "You notice an ant trail beside you." },
            { "NoneWoods5", "Broken bottles signal an old campsite." },
            { "NoneWoods6", "The branches scratch and poke you" },
            { "NoneWoods7", "An animal shrieks in the tree nearby" },
            { "NoneWoods8", "It looks like spriggans have been here" },
            { "NoneWoods9", "The forest canopy provides some shelter" },

            { "NoneMountains0", "You see old wagon trails." },
            { "NoneMountains1", "A horse neighs in the distance." },
            { "NoneMountains2", "You cross over some old bones." },
            { "NoneMountains3", "There are some snake holes here." },
            { "NoneMountains4", "You tread carefully around the jagged rocks" },
            { "NoneMountains5", "The air is thin and unsatisfying" },
            { "NoneMountains6", "Sounds echo off the hills" },
            { "NoneMountains7", "Your foot lands next to a tough, spiky plant" },
            { "NoneMountains8", "You startle some birds" },
            { "NoneMountains9", "You feel watched" },

            { "NoneOcean0", "Calm waves roll around you." },
            { "NoneOcean1", "The smell of the sea fills your lungs." },
            { "NoneOcean2", "You wonder what foul beasts reside in the deep" },
            { "NoneOcean3", "The waves are hypnotizing" },
            { "NoneOcean4", "Some seabirds shriek and flap their wings" },
            { "NoneOcean5", "You brush the salt residue off" },
            { "NoneOcean6", "The ocean breeze revitalizes you" },
            { "NoneOcean7", "The sound of the ocean is like a lullaby" },
            { "NoneOcean8", "You remember that time you almost drowned" },
            { "NoneOcean9", "You check the water for Slaughterfish" },

            // City climates:
            { "TownCityDesert0", "You smell roasting scorpion." },
            { "TownCityDesert1", "You hear someone fiddling with a lock." },
            { "TownCityDesert3", "The smell of burning fireplaces fills the air." },
            { "TownCityDesert4", "You smell delicious food being cooked." },
            { "TownCityDesert5", "A welcoming oasis in these lands" },
            { "TownCityDesert6", "The streets make walking in the sand a bit easier" },
            { "TownCityDesert7", "The cityfolk protect their belongings from the sand" },
            { "TownCityDesert8", "You cant wait to get some shade" },
            { "TownCityDesert9", "A lizard snatches a beetle and runs off" },

            { "TownCitySwamp0", "You can smell someone cooking a vegetable stew." },
            { "TownCitySwamp1", "Footprints weigh heavily in this damp soil." },
            { "TownCitySwamp2", "People here keep their belongings secure" },
            { "TownCitySwamp3", "The smokey flames help keep the bugs away" },
            { "TownCitySwamp4", "You hear some croaking frogs in the distance" },
            { "TownCitySwamp5", "The smell of mud is briefly replaced by fresh baked bread" },
            { "TownCitySwamp7", "Taverns can provide a bed free from mud" },
            { "TownCitySwamp9", "Your clothing feels heavy in the damp air" },

            { "TownCityWoods0", "The smell of roast pig fills the air." },
            { "TownCityWoods1", "An old man leans on a sturdy walking stick" },
            { "TownCityWoods3", "The smell of wood smoke is soothing" },
            { "TownCityWoods4", "A fletcher minds his craft" },
            { "TownCityWoods5", "Some children are climbing trees" },
            { "TownCityWoods6", "The thick tree cover makes this place feel secure" },
            { "TownCityWoods7", "You wonder if you'll see a Wood Elf" },
            { "TownCityWoods9", "The cityfolk whisper of tree spirits" },

            { "TownCityMountains0", "This area smells heavily of roasting chicken." },
            { "TownCityMountains1", "The wind is quite strong" },
            { "TownCityMountains2", "The city is well situated in the mountains" },
            { "TownCityMountains3", "The cityfolk feel they are closer to the divines here" },
            { "TownCityMountains4", "Some of the rocks have markings" },
            { "TownCityMountains5", "The city walls contain decorated mountain rocks" },
            { "TownCityMountains6", "Some believe the evergreens point to The Divines" },
            { "TownCityMountains9", "A fresh breeze brushes past you" },

            // Town climates:
            { "TownVillageDesert1", "You can feel the drink on your lips already" },
            { "TownVillageDesert2", "There must be some camels nearby" },
            { "TownVillageDesert3", "This village seems to cater to travellers often" },
            { "TownVillageDesert4", "A villager sweeps away some sand" },
            { "TownVillageDesert5", "The villagers seem to have what they need here" },
            { "TownVillageDesert6", "The streets make it easier to get around" },
            { "TownVillageDesert9", "A swell of sand stings your eyes" },

            { "TownVillageSwamp0", "Some villagers glance in your direction" },
            { "TownVillageSwamp1", "There seem to be fewer bugs in the village" },
            { "TownVillageSwamp2", "Your feet need to be dried by a fire" },
            { "TownVillageSwamp3", "A frog leaps out from under your footstep" },
            { "TownVillageSwamp4", "You slip on a root" },
            { "TownVillageSwamp5", "The moss grows rapidly in this area" },
            { "TownVillageSwamp6", "Seeing the glow of the fires is soothing" },
            { "TownVillageSwamp7", "The smell of frying meat whets your appetite" },
            { "TownVillageSwamp8", "A villager slips and falls in the mud" },
            { "TownVillageSwamp9", "This place will ease the gloom" },

            { "TownVillageWoods0", "The birds sing and flutter" },
            { "TownVillageWoods1", "You brush the twigs off yourself" },
            { "TownVillageWoods2", "The smell of woodfire is welcome" },
            { "TownVillageWoods3", "The trees make this a peaceful setting" },
            { "TownVillageWoods4", "The villagers are concerned with spriggans in the area" },
            { "TownVillageWoods5", "An old man with a cane nods at you" },
            { "TownVillageWoods6", "There's sure to be a warm fire and cold drink here" },

            { "TownVillageMountains0", "You smell a wonderous spice from someones window" },
            { "TownVillageMountains1", "You're thankful to be around some civilization" },
            { "TownVillageMountains3", "You can feel the breeze on your skin" },
            { "TownVillageMountains4", "The air is very fresh and clean up here" },
            { "TownVillageMountains5", "Birds ride the air currents above you" },
            { "TownVillageMountains6", "A woman indulges in a gifted flower" },
            { "TownVillageMountains7", "Some villagers pray atop the peaks" },

            // Village climates:
            { "TownHamletDesert0", "The sand builds on the sides of the houses" },
            { "TownHamletDesert1", "A lizard rests in the shade nearby" },
            { "TownHamletDesert2", "A dog is digging in the sand" },
            { "TownHamletDesert3", "A tavern with cold drink is all you think of now" },
            { "TownHamletDesert5", "The heat rises off the sand behind you" },
            { "TownHamletDesert6", "A camel is eyeing you" },
            { "TownHamletDesert7", "The vulture overhead flys off" },

            { "TownHamletSwamp1", "The smell of wood fires replaces the stale bog" },
            { "TownHamletSwamp3", "A snake slips by your foot" },
            { "TownHamletSwamp4", "A soft breeze flutters some fabric" },
            { "TownHamletSwamp5", "A crow caws and flys off" },
            { "TownHamletSwamp6", "Your feet slide on the muddy ground" },
            { "TownHamletSwamp7", "You hope to find an accomodating tavern" },
            { "TownHamletSwamp9", "You smell roast vegetables and beef" },

            { "TownHamletWoods0", "You hear someone chopping wood" },
            { "TownHamletWoods1", "You smell the smoke of a fire" },
            { "TownHamletWoods4", "An owl startles you with a hoot" },
            { "TownHamletWoods5", "You step over a root in the path" },
            { "TownHamletWoods6", "It's a very peaceful life here" },
            { "TownHamletWoods7", "You cant wait to rest your legs" },
            { "TownHamletWoods8", "You hear the wind rustle the leaves" },

            { "TownHamletMountains1", "The wind blows through the houses" },
            { "TownHamletMountains2", "There's a well worn merchant path" },
            { "TownHamletMountains3", "The streets are welcoming after travelling the terrain" },
            { "TownHamletMountains4", "The mountains dwarf this modest Hamlet" },
            { "TownHamletMountains5", "You hope to find what you need here" },
            { "TownHamletMountains8", "You hear some birds nearby" },

            // Tavern climates:
            { "TavernDesert0", "You wipe the sand from your eyes" },
            { "TavernDesert1", "This place had better keep the drink flowing" },
            { "TavernDesert2", "There's a concerning clump of sand nearby" },
            { "TavernDesert3", "A lizard has made this tavern it's home" },
            { "TavernDesert5", "An  old mug is half buried in the sand" },
            { "TavernDesert6", "A camel munches and grunts at you" },
            { "TavernDesert9", "You can smell the ale from here" },

            { "TavernSwamp1", "The area is quite muddy" },
            { "TavernSwamp2", "Many a weary traveller has stopped here" },
            { "TavernSwamp3", "The smell of ale is all you notice" },
            { "TavernSwamp4", "There are animal bones here" },
            { "TavernSwamp6", "You cant wait to escape these bugs" },
            { "TavernSwamp7", "Someone is passed out around back" },
            { "TavernSwamp9", "You hope for fresh food" },

            { "TavernWoods0", "Someone is swaying behind a tree" },
            { "TavernWoods2", "You lust after the thought of a drink" },
            { "TavernWoods3", "the scent of the fire pursues you" },
            { "TavernWoods4", "You see a patron carrying a large leg of pork" },
            { "TavernWoods7", "This seems to be a popular establishment" },
            { "TavernWoods8", "You almost couldnt find this place through the trees" },

            { "TavernMountains0", "The rocks are covered in broken glass" },
            { "TavernMountains1", "You can see and hear this place for a mile" },
            { "TavernMountains2", "It sounds like a fight has broken out" },
            { "TavernMountains4", "You think you spot a nest among the rocks" },
            { "TavernMountains5", "You hear a swell of birds not far off" },
            { "TavernMountains6", "theres an old pair of pants on the rocks" },
            { "TavernMountains9", "A drunkard thinks he's your friend" },

            // Farm climates:
            { "HomeFarmsDesert0", "Maybe there's some food to spare" },
            { "HomeFarmsDesert1", "It must be hard work to get a prosperous yield" },
            { "HomeFarmsDesert2", "The workers have carefully tended the crops" },
            { "HomeFarmsDesert3", "When the wind subsides you can smell the farm" },
            { "HomeFarmsDesert4", "Some religious symbols are marked around the crops" },
            { "HomeFarmsDesert6", "The Divines must help this family grow crops out here" },
            { "HomeFarmsDesert8", "These people feed the nearby towns and villages" },

            { "HomeFarmsSwamp0", "There's plenty of water for the soil here" },
            { "HomeFarmsSwamp1", "You swat a fly away" },
            { "HomeFarmsSwamp7", "The birds have found some seeds to peck at" },
            { "HomeFarmsSwamp8", "Hopefully the farmhands feel like sharing" },
            { "HomeFarmsSwamp9", "These people feed many others in their region" },

            { "HomeFarmsWoods0", "You hope for a generous farmhand" },
            { "HomeFarmsWoods1", "They've cleared the trees to get sun on the crops" },
            { "HomeFarmsWoods2", "This land can be difficult to manage" },
            { "HomeFarmsWoods7", "This farm is vital to feeding the locals" },
            { "HomeFarmsWoods8", "This place feels private and peaceful" },

            { "HomeFarmsMountains0", "A careful hand can grow a field of crops here" },
            { "HomeFarmsMountains1", "The Divines are held dear for mountain growers" },
            { "HomeFarmsMountains2", "Mountain rocks reinforce their walls" },
            { "HomeFarmsMountains4", "The farmhand work hard to maximize their yield" },
            { "HomeFarmsMountains8", "The yield here will feed people in the surrounding area" },

            // Mansion climates:
            { "HomeWealthyDesert0", "This estate is more well off than others" },
            { "HomeWealthyDesert2", "You wonder how this person affords this" },
            { "HomeWealthyDesert6", "These estates are maintained for lords of the region" },
            { "HomeWealthyDesert8", "More is spent on water than many make in a year" },

            { "HomeWealthySwamp0", "You see very high quality wares in use" },
            { "HomeWealthySwamp1", "There is a squire eyeing you" },
            { "HomeWealthySwamp2", "This place is more ornate than many others" },
            { "HomeWealthySwamp3", "The workers have styled the plantgrowth on the houses" },
            { "HomeWealthySwamp6", "The ground isnt as muddy as most other places" },
            { "HomeWealthySwamp7", "You see a princely looking figure in the window" },

            { "HomeWealthyWoods0", "These houses are sturdy and secure" },
            { "HomeWealthyWoods1", "Many caravans come through here with goods" },
            { "HomeWealthyWoods6", "The animals have shiny, healthy coats" },
            { "HomeWealthyWoods8", "That smell on the air, you didnt think that spice was available here" },
            { "HomeWealthyWoods9", "This is fit for a King" },

            { "HomeWealthyMountains0", "The cost of these building materials is astounding" },
            { "HomeWealthyMountains2", "Flowers decorate these buildings" },
            { "HomeWealthyMountains3", "They've left decorations on the surrounding rocks" },
            { "HomeWealthyMountains4", "You wonder what exotic items these walls hold" },
            { "HomeWealthyMountains7", "Some of the rocks have carvings inlet with gems" },
            { "HomeWealthyMountains8", "The animals water is clear and plentiful" },

            // Hovel climates:
            { "HomePoorDesert0", "The house has fallen into disrepair" },
            { "HomePoorDesert2", "Some birds are pecking at old bones" },
            { "HomePoorDesert6", "This place should be abandoned" },
            { "HomePoorDesert7", "The sand has covered some of the old structures" },
            { "HomePoorDesert8", "You pain to see someone live like this" },
            { "HomePoorDesert9", "Maybe this place used to be nice" },

            { "HomePoorSwamp0", "You see a broken wagon wheel" },
            { "HomePoorSwamp2", "This house is barely standing" },
            { "HomePoorSwamp3", "The soil looks spent" },
            { "HomePoorSwamp4", "The swampland smells preferable to this place" },
            { "HomePoorSwamp6", "The wood here is rotting" },
            { "HomePoorSwamp9", "Some broken equipment is discarded nearby" },

            { "HomePoorWoods0", "The forest is starting to swallow this place" },
            { "HomePoorWoods1", "You doubt many people even know this exists" },
            { "HomePoorWoods2", "The house looks broken down" },
            { "HomePoorWoods3", "A window shutter creaks and slams in the breeze" },
            { "HomePoorWoods4", "The buildings look torn apart" },
            { "HomePoorWoods6", "You hope no one lives here" },
            { "HomePoorWoods7", "You dont want to stay here very long" },

            { "HomePoorMountains0", "The ground is rocky and uneven" },
            { "HomePoorMountains1", "You wince at the squalor" },
            { "HomePoorMountains2", "You sense this used to be a reputable establishment" },
            { "HomePoorMountains4", "Only scavengers are seen near here" },
            { "HomePoorMountains5", "This place feels dreary" },
            { "HomePoorMountains6", "You hope to be done your business and leave" },
            { "HomePoorMountains7", "You wonder about who would live here" },
            { "HomePoorMountains9", "Someone tried to scratch a religious symbol here" },

            // Graveyard climates:
            { "GraveyardDesert0", "Some bones are half buried in the sand" },
            { "GraveyardDesert1", "Scavengers indicate a recent burial" },
            { "GraveyardDesert3", "A vulture circles above you" },
            { "GraveyardDesert4", "A shiver runs up your back" },
            { "GraveyardDesert6", "A shovel has been discarded nearby" },
            { "GraveyardDesert7", "Beetles scurry from your step" },
            { "GraveyardDesert8", "There are some old dried flowers buried in the sand" },

            { "GraveyardSwamp0", "You smell a rotten stench" },
            { "GraveyardSwamp1", "The bugs are large and confident" },
            { "GraveyardSwamp3", "It suddenly feels cold" },
            { "GraveyardSwamp4", "There seem to be faces in the plantgrowth" },
            { "GraveyardSwamp5", "Worms are writhing near you" },
            { "GraveyardSwamp7", "Something was dragged through the mud" },
            { "GraveyardSwamp8", "You hear a low moan" },
            { "GraveyardSwamp9", "An old symbol of The Nine has nearly vanished" },

            { "GraveyardWoods0", "The trees around this site look diseased" },
            { "GraveyardWoods1", "The crows near here sound sick" },
            { "GraveyardWoods2", "You think you see someone out of the corner of your eye" },
            { "GraveyardWoods3", "The tree nearest to you shakes" },
            { "GraveyardWoods5", "The roots have push over a tombstone" },
            { "GraveyardWoods6", "There are scratches on the rock" },
            { "GraveyardWoods8", "This religious symbol is meant to protect the dead" },
            { "GraveyardWoods9", "There is a small gravestone with a child toy on it" },

            { "GraveyardMountains0", "The locals say ghosts can be seen in the morning fog" },
            { "GraveyardMountains1", "Rocks are used to decorate the graves" },
            { "GraveyardMountains2", "Birds are nesting near the graves" },
            { "GraveyardMountains3", "The ground here is a reddish brown" },
            { "GraveyardMountains4", "The wind is colder than usual" },
            { "GraveyardMountains5", "You hear a distant yell" },
            { "GraveyardMountains7", "A ritual was performed here" },
            { "GraveyardMountains8", "\"Here lies my only love\"" },

            // Coven climates:
            { "CovenDesert0", "The beldam's presence is striking" },
            { "CovenDesert1", "Twisted patterns have formed in the sand" },
            { "CovenDesert2", "Some sort of energy melted the sand here" },
            { "CovenDesert3", "You smell strange ingredients" },

            { "CovenSwamp0", "There are strange grooves in the mud" },
            { "CovenSwamp1", "The beldam stands facing you" },
            { "CovenSwamp3", "The bugs and reptiles slink nearer" },

            { "CovenWoods0", "The trees seem to curl around you" },
            { "CovenWoods2", "You brush a spider off your leg" },
            { "CovenWoods3", "The beldams eyes are hypnotizing" },

            { "CovenMountains0", "Its as if they have never moved from this spot" },
            { "CovenMountains1", "The beldam stares without blinking" },
            { "CovenMountains2", "Their chanting echoes in the hills" },
            { "CovenMountains4", "The rocks are decorated with bones" },

            // Temple climates:
            { "ReligionTempleDesert0", "Pilgrims make the treck here to worship" },
            { "ReligionTempleDesert1", "The temple is accepting visitors" },
            { "ReligionTempleDesert2", "A symbol for The Nine is placed in a window" },
            { "ReligionTempleDesert3", "You feel a concentration of energy" },
            { "ReligionTempleDesert4", "Donations are said to give luck" },
            { "ReligionTempleDesert5", "Temples are said to offer cures, even to non members" },
            { "ReligionTempleDesert6", "You smell ceremonial fire" },
            { "ReligionTempleDesert7", "Some lizards rest near the temple" },
            { "ReligionTempleDesert8", "Caravans keep this place well stocked" },
            { "ReligionTempleDesert9", "The temple has resonated a pattern in the sand" },

            { "ReligionTempleSwamp0", "Devotees place designs in the moss on the temple" },
            { "ReligionTempleSwamp1", "You can see people in the temple" },
            { "ReligionTempleSwamp2", "You feel a rush of energy" },
            { "ReligionTempleSwamp3", "Someone has scratched a mark for The Nine" },
            { "ReligionTempleSwamp4", "Donations help keep the temple clean" },
            { "ReligionTempleSwamp5", "If you are ill, the temple can help you" },
            { "ReligionTempleSwamp6", "The wildlife seems relaxed near the temple" },
            { "ReligionTempleSwamp7", "The dirt around the temple has a pattern forming" },
            { "ReligionTempleSwamp8", "Songbirds adorn the temple" },

            { "ReligionTempleWoods0", "There are religious markings on the trees" },
            { "ReligionTempleWoods1", "Someone has whittled a religious statue" },
            { "ReligionTempleWoods2", "Woodland animals rest near the temple" },
            { "ReligionTempleWoods3", "Eight and One is written on a tree stump" },
            { "ReligionTempleWoods4", "Someone lights a candle in the temple" },
            { "ReligionTempleWoods5", "The donations from locals are put to good use" },
            { "ReligionTempleWoods6", "Temples are known to cure any who seek it" },
            { "ReligionTempleWoods9", "You feel a swell of energy" },

            { "ReligionTempleMountains0", "You feel a focus of energy" },
            { "ReligionTempleMountains1", "The rocks have religious markings" },
            { "ReligionTempleMountains2", "There are prayer sites in the surrounding hills" },
            { "ReligionTempleMountains3", "Someone just finished a prayer in the temple" },
            { "ReligionTempleMountains4", "Donations are accepted by members of the faith" },
            { "ReligionTempleMountains5", "This looks like a Talos symbol" },
            { "ReligionTempleMountains6", "You can cure an illness in the temple" },

            { "ReligionCultDesert0", "A discreet place to practice rituals" },
            { "ReligionCultDesert1", "Thick smoke pollutes the air" },
            { "ReligionCultDesert2", "You are met with intense eyes" },
            { "ReligionCultDesert3", "The building has been eroded by sand and wind" },
            { "ReligionCultDesert4", "Religious carvings are placed in the sand" },

            { "ReligionCultSwamp0", "Truely zealous devotees congregate here" },
            { "ReligionCultSwamp1", "The moss is creeping up the rocks" },
            { "ReligionCultSwamp2", "There's some discoloured smoke rising" },
            { "ReligionCultSwamp3", "Footprints litter the mud" },
            { "ReligionCultSwamp4", "You step on a bug you've never seen before" },

            { "ReligionCultWoods0", "A sickly smoke drifts nearby" },
            { "ReligionCultWoods1", "Not much grows here" },
            { "ReligionCultWoods2", "The crows sound haggard" },
            { "ReligionCultWoods3", "There are faces in the trees" },
            { "ReligionCultWoods4", "A scrap of parchment blows past" },
            { "ReligionCultWoods5", "Fanatics are drawn to this place" },

            { "ReligionCultMountains0", "Fanatics are intoxicated by The Divines" },
            { "ReligionCultMountains2", "There are bug carcasses littered about" },
            { "ReligionCultMountains3", "The air has changed" },
            { "ReligionCultMountains4", "The ground rumbles slightly" },


            // Dungeon climates:
            { "DungeonLabyrinthDesert1", "Many travellers have fallen here" },
            { "DungeonLabyrinthDesert2", "The sand covers countless dead" },
            { "DungeonLabyrinthDesert3", "There is a great sadness here" },
            { "DungeonLabyrinthDesert4", "You hear horrible sounds underground" },
            { "DungeonLabyrinthDesert5", "The wildlife stays far from here" },
            { "DungeonLabyrinthDesert6", "The sand is coarse and discolored" },
            { "DungeonLabyrinthDesert7", "A religious item is stained in blood" },
            { "DungeonLabyrinthDesert9", "Theres a deathly howl coming from the deep" },

            { "DungeonLabyrinthSwamp1", "The wretched stench of death is powerful" },
            { "DungeonLabyrinthSwamp2", "The worms are fat and sickly" },
            { "DungeonLabyrinthSwamp3", "A crow seems to laugh at you" },
            { "DungeonLabyrinthSwamp6", "The mud is a reddish brown" },
            { "DungeonLabyrinthSwamp7", "Stale air bursts forth like a breath" },
            { "DungeonLabyrinthSwamp8", "This place feels dark and deadly" },
            { "DungeonLabyrinthSwamp9", "A body is mostly consumed in mud" },

            { "DungeonLabyrinthWoods0", "The trees have scratches on them" },
            { "DungeonLabyrinthWoods1", "You hear echoes underneath the ground" },
            { "DungeonLabyrinthWoods2", "The cold air from the dungeon is oppressive" },
            { "DungeonLabyrinthWoods4", "Deadly enemies are coarsing underground" },
            { "DungeonLabyrinthWoods7", "You feel the suffering inflicted here" },
            { "DungeonLabyrinthWoods8", "You hear something cry out in death" },
            { "DungeonLabyrinthWoods9", "Most turn back here..." },

            { "DungeonLabyrinthMountains0", "The stones are used to commemorate the dead" },
            { "DungeonLabyrinthMountains2", "The bugs leech your blood" },
            { "DungeonLabyrinthMountains3", "You feel decades of despair in this place" },
            { "DungeonLabyrinthMountains4", "Those marks aren't human" },
            { "DungeonLabyrinthMountains5", "It smells like the dead" },
            { "DungeonLabyrinthMountains6", "There are few capable of surviving this place" },
            { "DungeonLabyrinthMountains8", "The wind wrestles you as you move" },


            { "DungeonKeepDesert1", "The sand rolls over some bones" },
            { "DungeonKeepDesert2", "A ghastly lizard scurries from the dungeon door" },
            { "DungeonKeepDesert4", "A religious marking was drawn here for protection" },
            { "DungeonKeepDesert5", "Beetles are crawling on the archways" },
            { "DungeonKeepDesert6", "A broken potion bottle fills with sand" },
            { "DungeonKeepDesert7", "Animals scurry away carrying bones" },
            { "DungeonKeepDesert8", "The air from the dungeon is sickly" },
            { "DungeonKeepDesert9", "A vulture circles overhead" },

            { "DungeonKeepSwamp0", "Snakes writhe around rusted armor" },
            { "DungeonKeepSwamp1", "Bugs swarm your eyes and ears" },
            { "DungeonKeepSwamp3", "What danger resides here?" },
            { "DungeonKeepSwamp4", "There seems to be a grave here" },
            { "DungeonKeepSwamp6", "an inscription reads \"may The Divines protect you\"" },
            { "DungeonKeepSwamp8", "You think you hear a shriek" },
            { "DungeonKeepSwamp9", "The moss around the entrance is dying" },

            { "DungeonKeepWoods0", "A spell was used here" },
            { "DungeonKeepWoods1", "Bugs crawl out of a skull" },
            { "DungeonKeepWoods2", "The trees are dead and dried out" },
            { "DungeonKeepWoods3", "The forest seems to whisper a warning" },
            { "DungeonKeepWoods4", "A religious relic has been desecrated" },

            { "DungeonKeepWoods7", "You think you hear something" },
            { "DungeonKeepWoods8", "You can smell rotting flesh" },

            { "DungeonKeepMountains0", "Blood is shed on the rocks" },
            { "DungeonKeepMountains2", "A religious symbol has some dead flowers next to it" },
            { "DungeonKeepMountains4", "You think you hear a crash underground" },
            { "DungeonKeepMountains5", "Some destruction magic was cast here" },
            { "DungeonKeepMountains8", "Something was killed here" },
            { "DungeonKeepMountains9", "The plant life is sparse" },


            { "DungeonRuinDesert2", "The bugs scurry away as you approach" },
            { "DungeonRuinDesert3", "A broken sword is discarded nearby" },
            { "DungeonRuinDesert4", "There are a few religious markings nearby" },
            { "DungeonRuinDesert6", "An old potion has gotten sand in it" },
            { "DungeonRuinDesert7", "There is a slight breeze from the dungeon" },
            { "DungeonRuinDesert8", "The air is rather stale" },
            { "DungeonRuinDesert9", "The doorway is worn and scuffed" },

            { "DungeonRuinSwamp0", "Adventurers tracks lead into the dungeon" },
            { "DungeonRuinSwamp2", "There's a helmet with a hole in it" },
            { "DungeonRuinSwamp3", "You can hear the wildlife chatter" },
            { "DungeonRuinSwamp5", "Some moths rest near the entrance" },
            { "DungeonRuinSwamp6", "Something tried to eat a rat" },
            { "DungeonRuinSwamp8", "The entrance door jostles in the breeze" },
            { "DungeonRuinSwamp9", "A potion recipe is tucked under a rock" },

            { "DungeonRuinWoods0", "A prayer site was erected in the trees" },
            { "DungeonRuinWoods1", "A crow caws and flys away" },
            { "DungeonRuinWoods2", "The flowers look unwell here" },
            { "DungeonRuinWoods4", "A rogue was making some arrows here" },
            { "DungeonRuinWoods5", "You can feel an air current from the dungeon" },
            { "DungeonRuinWoods6", "Someone put a rats head on a spike" },
            { "DungeonRuinWoods7", "The air smells a little foul" },
            { "DungeonRuinWoods9", "The bugs buzz around your ears" },

            { "DungeonRuinMountains0", "Religious symbols are freshly painted on the rocks" },
            { "DungeonRuinMountains2", "The flowers are smaller and less colourful here" },
            { "DungeonRuinMountains3", "The dungeon air whistles through the doorway" },
            { "DungeonRuinMountains4", "There are footprints around the entrance" },
            { "DungeonRuinMountains5", "Someones old shield has wasted away in the weather" },
            { "DungeonRuinMountains6", "An adventurers horse was parked here" },
            { "DungeonRuinMountains7", "A bat was cooked and eaten" },
            { "DungeonRuinMountains8", "It is rather quiet" },


            // Player Ship - Always Ocean Climate
            { "HomeYourShipsOcean0", "The waves sound like a lullaby" },
            { "HomeYourShipsOcean1", "The water extends for miles" },
            { "HomeYourShipsOcean2", "You check the water for beasts" },
            { "HomeYourShipsOcean3", "You can smell the water from here" },
            { "HomeYourShipsOcean4", "The ocean breeze moans \"Kelle\"" },

            #endregion

            #region Weather texts:

            { "NoneDayClear0", "The day is so clear, you can see for miles." },
            { "NoneDayClear1", "The sky is so clear and blue." },
            { "NoneDayClear2", "Small rodents scamper about nearby." },
            { "NoneDayClear3", "You swat an insect buzzing in your ear." },

            { "NoneNightClear0", "Tonight it's so clear that you stop for a moment to marvel at the sheer number of stars overhead." },

            { "TownCityNightClear0", "The night sky seen from this city is marvellous" },


            { "NoneDayRainy0", "Your clothes are becoming soaked through." },
            { "NoneDayRainy1", "The rain is making the ground muddy." },

            { "NoneNightRainy0", "The rain is making the night even more inpenetrable." },

            { "NoneDaySnowy0", "You can see your breath." },
            { "NoneDaySnowy1", "The snow is starting to pile up around you." },

            { "TownCityDayRainy0", "Puddles are starting to form nearby." },
            { "TownCityDayRainy1", "Someone sighs, “More miserable rain.“" },

            { "TownCityNightRainy0", "Someone mutters, “Our house must be haunted.”" },

            { "TownCityDaySnowy0", "The falling snow relaxes you." },
            { "TownCityDaySnowy1", "You breathe in some crisp, cold air." },
            { "TownCityDaySnowy2", "You hear, “Fresh baked bread, children! Come inside!”" },
            { "TownCityDaySnowy3", "You overhear, “I can escort your caravan, for the right price.”" },

            { "TownCityNightSnowy0", "Someone says, “Get inside, before you catch cold!”" },

            { "TownCityNightCloudy0", "The streets are quiet and gloomy, giving the night an eery feeling." },

            #endregion

            #region Day / Night texts:

// REG: Not sure about these religious statements... where do they come from, inside the players head?
            { "NoneDay0", "The Nine say: Above all else, be good to one another." },
            { "NoneDay1", "Stendarr says: Be kind and generous to the people of Tamriel. Protect the weak, heal the sick, and give to the needy." },
            { "NoneDay2", "Arkay says: Honor the earth, its creatures, and the spirits, living and dead. Guard and tend the bounties of the mortal world, and do not profane the spirits of the dead." },
            { "NoneDay3", "Mara says: Live soberly and peacefully. Honor your parents, and preserve the peace and security of home and family." },
            { "NoneDay4", "Zenithar says: Work hard, and you will be rewarded. Spend wisely, and you will be comfortable. Never steal, or you will be punished." },
            { "NoneDay5", "Talos says: Be strong for war. Be bold against enemies and evil, and defend the people of Tamriel." },
            { "NoneDay6", "Kynareth says: Use Nature's gifts wisely. Respect her power, and fear her fury." },
            { "NoneDay7", "Dibella says: Open your heart to the noble secrets of art and love. Treasure the gifts of friendship. Seek joy and inspiration in the mysteries of love." },
            { "NoneDay8", "Julianos says: Know the truth. Observe the law. When in doubt, seek wisdom from the wise." },
            { "NoneDay9", "Akatosh says: Serve and obey your Emperor. Study the Covenants. Worship the Nine, do your duty, and heed the commands of the saints and priests." },

            { "NoneNight0", "The darkness is trying to lull you to sleep." },
            { "NoneNight1", "The dark night fills you with unease." },
            { "NoneNight2", "Bats flutter about overhead." },
            { "NoneNight3", "You think you hear movement behind you" },
            { "NoneNight4", "Two animals are fighting in the distance" },

            { "TownCityDay0", "You hear some neighbours arguing" },
            { "TownCityDay1", "A young one says \"You smell!\" and runs off" },
            { "TownCityDay2", "You catch the scent of a warm meal" },
            { "TownCityDay3", "You see a large shipment being delivered" },
            { "TownCityDay4", "Someone eyes you over their shoulder" },
            { "TownCityDay5", "You hear a merchant pushing his wares" },
            { "TownCityDay6", "Someone shouts, \"Give that back! Guards, help!\"" },
            { "TownCityDay7", "Someone calls out, \"Fresh brewed ale!\"" },
            { "TownCityDay8", "An old man tells a tale to some young'ns" },
            { "TownCityDay9", "Someone is playing a tune" },

            { "TownCityNight0", "You can hear some of the city night life" },
            { "TownCityNight1", "You spot a cat sneaking around the corner" },
            { "TownCityNight2", "You hear someone fiddling with a lock." },
            { "TownCityNight3", "Distant guards call for a criminal to halt" },
            { "TownCityNight4", "You hear someone running away" },
            { "TownCityNight5", "You can hear some drunken patrons" },
            { "TownCityNight6", "Someone is snoring loudly" },
            { "TownCityNight7", "You see someone watching you from their window" },
            { "TownCityNight8", "You hear a child crying somewhere in the distance" },
            { "TownCityNight9", "Someone is humming a tune" },

            { "TownVillageDay0", "You see a friendly face" },
            { "TownVillageDay1", "Someone is chopping wood" },
            { "TownVillageDay2", "Someone calls a dog in the distance" },
            { "TownVillageDay3", "A waft of exciting spices finds your nose" },
            { "TownVillageDay4", "The locals stop to greet you" },
            { "TownVillageDay5", "A young girl trips as she runs by" },
            { "TownVillageDay6", "Some neighbours are stopping to chat" },
            { "TownVillageDay7", "A horse neighs and scrapes the ground" },
            { "TownVillageDay8", "A child looks at you with awe" },
            { "TownVillageDay9", "A merchant tries to get your attention" },

            { "TownVillageNight0", "There is a group of youths talking nearby" },
            { "TownVillageNight1", "Someone is smoking something" },
            { "TownVillageNight2", "A cat scurries after a rodent" },
            { "TownVillageNight3", "You hear some laughter in a house" },
            { "TownVillageNight4", "You hear some restless animals" },
            { "TownVillageNight5", "You see figures in the windows" },
            { "TownVillageNight6", "You hear someone trying a lock." },
            { "TownVillageNight7", "An old woman scowls at you and slams the door" },
            { "TownVillageNight8", "You keep an eye on the dark alleys" },
            { "TownVillageNight9", "A young boy sneaks out of his house" },

            { "TownHamletDay0", "One of the locals smiles at you" },
            { "TownHamletDay1", "You see some travellers in the distance" },
            { "TownHamletDay2", "The locals quiet as you pass" },
            { "TownHamletDay3", "The smell of fresh bread fills the air" },
            { "TownHamletDay4", "An old man is teaching his grandson how to identify plants" },
            { "TownHamletDay5", "Someone is drying some fruit with smoke" },
            { "TownHamletDay6", "Some neighbours are laughing together" },
            { "TownHamletDay7", "A child asks a neighbour for some sugar" },
            { "TownHamletDay8", "Local children sprint past you in play" },
            { "TownHamletDay9", "A local is cleaning their window" },

            { "TownHamletNight0", "A pig got into some cabbages" },
            { "TownHamletNight1", "A quiet walk in peaceful streets" },
            { "TownHamletNight2", "You can hear someones fire crackling" },
            { "TownHamletNight3", "The street lights bounce off the houses" },
            { "TownHamletNight5", "Quite a cozy looking place" },
            { "TownHamletNight6", "You nearly trip on a cat" },
            { "TownHamletNight7", "A child has left his toy here for the next day" },

            { "TavernDay0", "A few adventurers have just left" },
            { "TavernDay1", "A plate is smashed followed by laughter" },
            { "TavernDay2", "Someone was passed out here recently" },
            { "TavernDay3", "A man is walking gingerly, covering his eyes" },
            { "TavernDay4", "A barhand is carrying some meat, ready to be eaten" },
            { "TavernDay5", "The patrons scare the birds" },
            { "TavernDay6", "A worker sweeps the entrance" },

            { "TavernNight0", "A drunk figure stumbles off" },
            { "TavernNight1", "You hear the patrons bellowing a tune" },
            { "TavernNight2", "You pass a questionable puddle" },
            { "TavernNight3", "You can smell the fire, feast and foam" },
            { "TavernNight4", "Shapes move in the windows, a lively tavern" },
            { "TavernNight5", "A man stumbles up to you and falls down" },

            { "HomeFarmsDay0", "Everyone is out and working" },
            { "HomeFarmsDay1", "The farm workers stare at you." },
            { "HomeFarmsDay2", "A rather attractive worker smiles at you" },
            { "HomeFarmsDay3", "The animals make their presence known" },
            { "HomeFarmsDay4", "A slight breeze sways the crops" },
            { "HomeFarmsDay5", "One of the workers is jealous of his friends new hoe" },
            { "HomeFarmsDay6", "The smell of livestock permeates the air" },

            { "HomeFarmsNight0", "You can smell some decomposing vegetables" },
            { "HomeFarmsNight1", "You smelled this farmstead before you saw it" },
            { "HomeFarmsNight2", "You hear the animals settling down" },
            { "HomeFarmsNight3", "you see some wagon tracks nearby" },
            { "HomeFarmsNight4", "The farmhands have left for the night" },

            { "HomeWealthyDay0", "The sun shines on the polished metals" },
            { "HomeWealthyDay1", "This person has afforded a comfortable life" },
            { "HomeWealthyDay2", "Some of the people seem very annoyed by your presence" },
            { "HomeWealthyDay3", "The children play in fine fabrics with gold buckles" },
            { "HomeWealthyDay4", "A silver caraff is being used as a flower pot" },
            { "HomeWealthyDay5", "Your arrival is met with some surprise" },
            { "HomeWealthyDay6", "A worker tends to the garden" },
            { "HomeWealthyDay7", "Even the workers have quality attire" },
            { "HomeWealthyDay8", "You spot a young woman wearing nordic silk" },
            { "HomeWealthyDay9", "The children carry trinkets you've never seen before" },

            { "HomeWealthyNight0", "This place is a thief's dream" },
            { "HomeWealthyNight1", "The animals are kept in a strong pen" },
            { "HomeWealthyNight2", "A cat slinks by with a brass bell on its collar" },
            { "HomeWealthyNight3", "These people must pay dearly for protection" },
            { "HomeWealthyNight4", "A pony can be heard nearby" },

            { "HomePoorDay0", "This is a rather depressing area" },
            { "HomePoorDay1", "You watch your step among the droppings" },
            { "HomePoorDay2", "Someone is heard coughing" },
            { "HomePoorDay3", "There's a poorly written sign" },
            { "HomePoorDay4", "You can see where a wagon trail used to exist" },
            { "HomePoorDay5", "There's garbage strewn about" },
            { "HomePoorDay6", "Holes in the roof are patched haphazardly" },

            { "HomePoorNight0", "A sneeze is heard from the house" },
            { "HomePoorNight1", "Something doesnt smell good" },
            { "HomePoorNight2", "Stray animals scamper about" },
            { "HomePoorNight3", "You think something was buried here" },
            { "HomePoorNight4", "You hear someone crying" },

            { "HomeYourShipsDay0", "You see some movement in the distance" },
            { "HomeYourShipsDay1", "You hear the wind whipping the sails" },

            { "HomeYourShipsNight0", "The bugs have made their way on board" },
            { "HomeYourShipsNight1", "You can see some city lights" },
            { "HomeYourShipsNight2", "The sails flap lazily in the breeze" },

            { "GraveyardDay0", "Some decorations wilt on a gravestone" },
            { "GraveyardDay1", "A makeshift grave was dug nearby" },
            { "GraveyardDay2", "Some animals pick at exposed bones" },
            { "GraveyardDay3", "This engraving is from ages ago" },
            { "GraveyardDay4", "The plantlife looks sick" },

            { "GraveyardNight0", "Some fresh flowers rest on a grave" },
            { "GraveyardNight1", "Something is making a thumping noise" },
            { "GraveyardNight2", "You hear something running away" },
            { "GraveyardNight3", "You feel as if you aren't alone" },
            { "GraveyardNight4", "One of the graves has some fresh turned earth" },

            { "CovenDay0", "There is a bubbling pot" },
            { "CovenDay1", "Some potions are stashed out of the light" },
            { "CovenDay2", "They stare at you" },
            { "CovenDay3", "\"The Stricture\" can be read on a piece of parchment" },
            { "CovenDay4", "Access to great power can be obtained here" },
            { "CovenDay5", "A thick smoke rises" },

            { "CovenNight0", "A strange shadow drifts away" },
            { "CovenNight1", "A dark energy lingers here" },
            { "CovenNight2", "Potions glow faintly under some cloth" },
            { "CovenNight3", "Ancient rituals disturb the locals" },
            { "CovenNight4", "A witch has succumb to a trance" },
            { "CovenNight5", "They speak not, but you hear" },
            { "CovenNight6", "An arrid smoke lingers" },

            { "ReligionTempleDay0", "The residents recite religious texts" },
            { "ReligionTempleDay1", "Some children are wearing ceremonial garb" },
            { "ReligionTempleDay2", "Pilgrims are huddled near a temple member" },
            { "ReligionTempleDay3", "A young child gestures to the sky" },
            { "ReligionTempleDay4", "A beggar receives some aid" },
            { "ReligionTempleDay5", "Some chimes signal a prayer" },
            { "ReligionTempleDay6", "People speak softly near the temple" },
            { "ReligionTempleDay7", "An elder is reading a holy book" },
            { "ReligionTempleDay8", "The worshippers seem to float as they walk" },
            { "ReligionTempleDay9", "A woman is stitching some religious attire" },

            { "ReligionTempleNight0", "A pipe is being smoked" },
            { "ReligionTempleNight1", "You hear people chanting" },
            { "ReligionTempleNight2", "The windows have religious markings" },
            { "ReligionTempleNight3", "You hear laughter in one of the houses" },
            { "ReligionTempleNight4", "You smell a spice pie" },
// REG: Not sure about these - are they being overheard?
            { "ReligionTempleNight5", "\"Obey your Emperor\"" },
            { "ReligionTempleNight6", "\"Study the Covenants\"" },
            { "ReligionTempleNight7", "\"Worship the Eight\"" },
            { "ReligionTempleNight8", "\"Do your duty\"" },
            { "ReligionTempleNight9", "\"Heed the commands of the Saints and Priests\"" },

            { "ReligionCultDay0", "The day illuminates all deeds" },
            { "ReligionCultDay1", "Special herbs are being burned" },
            { "ReligionCultDay2", "The years have aged this place" },
            { "ReligionCultDay3", "You hear some magic" },
            { "ReligionCultDay4", "This building is contorted" },

            { "ReligionCultNight0", "A low humming can be heard" },
            { "ReligionCultNight1", "An unusual smell lingers in the air" },
            { "ReligionCultNight2", "Many voices stop at once" },
            { "ReligionCultNight3", "A distant laugh echoes past" },
            { "ReligionCultNight4", "A blade is being sharpened" },


            { "DungeonLabyrinthDay0", "The daylight reveals blood stains" },
            { "DungeonLabyrinthDay1", "There is a shredded cloak on the ground" },
            { "DungeonLabyrinthDay2", "scraps of metal and bone are everywhere" },
            { "DungeonLabyrinthDay3", "A warning is scratched onto the entrance" },
            { "DungeonLabyrinthDay4", "This religious marking has been corrupted" },
            { "DungeonLabyrinthDay5", "You hear a thousand whispers beneath you" },

            { "DungeonLabyrinthNight0", "You feel bones underfoot" },
            { "DungeonLabyrinthNight1", "Ghostly warnings find your ears" },
            { "DungeonLabyrinthNight2", "This place tests the resolve of mortals" },
            { "DungeonLabyrinthNight3", "You feel a strange draw to the dungeon entrance" },
            { "DungeonLabyrinthNight4", "The smell is unlike anything you've experienced" },
            { "DungeonLabyrinthNight5", "A gods forsaken oblivion hole" },
            { "DungeonLabyrinthNight6", "A brutal death flashes in your mind" },
            { "DungeonLabyrinthNight7", "You hear a desperate cry from the deep" },
            { "DungeonLabyrinthNight8", "The entrance is cloaked in the night" },

            { "DungeonKeepDay0", "Ritual markings are to protect those who tread" },
            { "DungeonKeepDay1", "Many adventurers fall pray to these depths" },
            { "DungeonKeepDay2", "There are some tracks leading into the dungeon" },
            { "DungeonKeepDay3", "A book of destruction magic is partially burned" },
            { "DungeonKeepDay4", "Blood was spilled recently" },
            { "DungeonKeepDay5", "A tribute is left for the dead." },
            { "DungeonKeepDay6", "Something big was dragged away from here" },
            { "DungeonKeepDay7", "There is a ripped cloak on the ground" },

            { "DungeonKeepNight0", "You think you hear something underneath" },
            { "DungeonKeepNight1", "Only the hearty survive" },
            { "DungeonKeepNight2", "The air is deadly still" },
            { "DungeonKeepNight3", "You feel watched" },
            { "DungeonKeepNight4", "Birds call out a warning" },
            { "DungeonKeepNight5", "Your senses perk up" },
            { "DungeonKeepNight6", "Visions of Oblivion flash in your mind" },
            { "DungeonKeepNight7", "The darkness hides the entrance" },

            { "DungeonRuinDay0", "Adventurers have been here recently" },
            { "DungeonRuinDay1", "Someone was camping nearby" },
            { "DungeonRuinDay2", "These religious markings are rather fresh" },
            { "DungeonRuinDay3", "Someone tried to draw a map" },
            { "DungeonRuinDay4", "The door is ajar" },
            { "DungeonRuinDay5", "Someone had their wagon nearby" },
            { "DungeonRuinDay6", "Birds chirp and fly overhead" },

            { "DungeonRuinNight0", "It is eerily quiet" },
            { "DungeonRuinNight1", "The air is musty" },
            { "DungeonRuinNight2", "Some bats squeak overhead" },
            { "DungeonRuinNight3", "The darkness is cloaking the entrance" },
            { "DungeonRuinNight4", "Someone discarded a used potion bottle" },
            { "DungeonRuinNight5", "You think you see someone..." },
            { "DungeonRuinNight6", "Pray the dead stay dead" },

            #endregion

            #region Dungeon texts:

            // Dungeon: Crypt
            { "Crypt0", "You sense something creeping behind you."}   ,
            { "Crypt1", "A gust of cold air blows past you."},
            { "Crypt2", "Was that a werewolf howl?"},
            { "Crypt3", "A beetle crosses your path."},
            { "Crypt4", "The air here is very stiff."},
            { "Crypt5", "This place smells strongly of death."},
            { "Crypt6", "You hear very faint whispers."},
            { "Crypt8", "Tiny rodents scamper away from you."},

            // Dungeon: OrcStronghold
            { "OrcStronghold0", "You notice broken fragments of a weapon."},
            { "OrcStronghold1", "This place smells terribly of orc."},
            { "OrcStronghold2", "The ground is smoothed here by dragged bodies."},
            { "OrcStronghold3", "Orcs seem to have slept here often."},
            { "OrcStronghold4", "You see writing in some primitive Orcish script."},
            { "OrcStronghold5", "Someone cries for help, far away."},
            { "OrcStronghold6", "Bits of fur and bone litter this area."},

            // Dungeon: HumanStronghold
            { "HumanStronghold0", "You hear the distant shot of an arrow."},
            { "HumanStronghold1", "Something rustles about."},
            { "HumanStronghold2", "You see unfamiliar markings scratched here."},
            { "HumanStronghold3", "Something flees from you."},
            { "HumanStronghold4", "The smell of death fills the air."},
            { "HumanStronghold5", "You smell burnt wood."},
            { "HumanStronghold6", "You vaguely smell ale."},
            { "HumanStronghold7", "Things are deathly quiet here."},
            { "HumanStronghold8", "A strange sigil is drawn here."},
            { "HumanStronghold9", "You could swear you hear whispers."},

            // Dungeon: Prison
            { "Prison0", "Scrawlings nearby plead for release." },
            { "Prison1", "You see tormented scribblings nearby." },
            { "Prison2", "The scent of a rotting corpse gathers here." },
            { "Prison3", "A broken key lies on the ground." },
            { "Prison4", "You notice tally marks scratched nearby." },
            { "Prison5", "Was that someone calling for help?" },
            { "Prison6", "You feel as if someone is watching you." },
            { "Prison7", "You could swear you just heard movement from afar." },
            { "Prison8", "Someone tried digging here." },
            { "Prison9", "Someone scratched an inaccurate map here." },

            // Dungeon: Desecrated Temple
            { "DesecratedTemple0", "You sense strong magic in the air." },
            { "DesecratedTemple1", "You see a prayer to Kynareth scrawled here." },
            { "DesecratedTemple2", "Someone scratched a prayer to Stendarr here." },
            { "DesecratedTemple3", "The feeling of death is overwhelming here." },
            { "DesecratedTemple4", "An upwelling of magic gathers near you." },
            { "DesecratedTemple5", "A hateful presence is nearby." },
            { "DesecratedTemple6", "Unholy energies permeate this area." },
            { "DesecratedTemple7", "Your thoughts are filled with daedra." },

            // Dungeon: Mine
            { "Mine0", "This ground is well worn." },
            { "Mine1", "Someone scratched several lines here." },
            { "Mine2", "Many footsteps have worn this ground smooth." },
            { "Mine3", "You notice writing in some kind of code." },
            { "Mine4", "You hear footsteps move away." },
            { "Mine5", "The ground is unusually warm here." },
            { "Mine6", "Tiny rodents flee from you." },
            { "Mine7", "A fly buzzes around your ear." },
            { "Mine8", "Someone tried to dig here." },
            { "Mine9", "Something pounds a surface far away." },

            // Dungeon: Natural Cave
            { "NaturalCave0", "You hear a cloud of bats flutter away." },
            { "NaturalCave1", "Old bear claws lie here." },
            { "NaturalCave2", "A snake crosses your path." },
            { "NaturalCave3", "Something tiny flees from you." },
            { "NaturalCave4", "You hear something rustling about." },
            { "NaturalCave5", "A moth flutters by." },
            { "NaturalCave6", "You see some wolf fur here." },
            { "NaturalCave8", "Some whiskers litter the ground." },

            // Dungeon: Coven
            { "Coven0", "Someone is watching you from afar." },
            { "Coven1", "You hear whispering." },
            { "Coven2", "Chanting echoes from far off." },
            { "Coven3", "You feel very dark energies here." },
            { "Coven4", "You wipe some oddly-colored dust from your face." },
            { "Coven5", "A small spider skitters in front of you." },
            { "Coven7", "This area smells of something burning." },
            { "Coven9", "You can’t shake the feeling of being watched." },

            // Dungeon: VampireHaunt
            { "VampireHaunt0", "You hear faint rustling." },
            { "VampireHaunt1", "Indistinct hissing comes from afar." },
            { "VampireHaunt2", "You smell blood." },
            { "VampireHaunt3", "A body was recently dragged through here." },
            { "VampireHaunt4", "The air here is disturbed." },
            { "VampireHaunt5", "Unintelligible markings cover the ground." },
            { "VampireHaunt6", "You notice a plea for help written here." },
            { "VampireHaunt7", "You see shards of a glass bottle mixed with blood." },
            { "VampireHaunt8", "A cold gust of air catches you off guard." },
            { "VampireHaunt9", "You smell death. Lots of it." },

            // Dungeon: Laboratory
            { "Laboratory0", "You see mineral deposits from a ruined atronach." },
            { "Laboratory1", "You notice rudimentary notes." },
            { "Laboratory2", "Unintelligible markings dot the ground." },
            { "Laboratory3", "You see some notes, thoroughly scratched out." },
            { "Laboratory4", "You feel concentrated magical forces." },
            { "Laboratory5", "The air grows very warm here." },
            { "Laboratory6", "The air here suddenly turns cold." },
            { "Laboratory7", "You sense volatile magicka in this area." },

            // Dungeon: HarpyNest
            { "HarpyNest1", "The stench of harpy is unbearable here." },
            { "HarpyNest2", "You avoid stepping in harpy droppings." },
            { "HarpyNest3", "Faint echoes of cawing fill the air." },
            { "HarpyNest4", "Caustic magicka surround you momentarily." },
            { "HarpyNest5", "A worm crawls across your foot." },
            { "HarpyNest6", "The ground and walls bear faint scratch marks." },
            { "HarpyNest7", "Is something watching you..?" },
            { "HarpyNest8", "The stench here is truly awful." },

            // Dungeon: RuinedCastle
            { "RuinedCastle0", "You hear the distant shot of an arrow."},
            { "RuinedCastle1", "Something rustles about."},
            { "RuinedCastle2", "You see unfamiliar markings scratched here."},
            { "RuinedCastle3", "Something flees from you."},
            { "RuinedCastle4", "The smell of death fills the air."},
            { "RuinedCastle5", "You smell burnt wood."},
            { "RuinedCastle6", "You vaguely smell ale."},
            { "RuinedCastle7", "Things are deathly quiet here."},
            { "RuinedCastle8", "An unfamiliar sigil is drawn here."},
            { "RuinedCastle9", "You could swear you hear whispers."},

            // Dungeon: SpiderNest
            { "SpiderNest0", "Webs fill the cracks in the wall"},
            { "SpiderNest1", "A tiny spider skitters across the ground."},
            { "SpiderNest2", "You feel as though something is crawling above you."},
            { "SpiderNest3", "Something is scratching a surface nearby."},
            { "SpiderNest4", "The floor is slightly sticky"},
            { "SpiderNest6", "You brush off a small spider."},
            { "SpiderNest7", "Eight tiny legs move across your feet."},
            { "SpiderNest8", "Something hisses in the distance."},
            { "SpiderNest9", "A small spider crawls out from among your possessions."},

            // Dungeon: GiantStronghold
            { "GiantStronghold0", "Many feet have smoothed the ground here."},
            { "GiantStronghold1", "The stench of unbathed skin fills the air."},
            { "GiantStronghold2", "Tiger whiskers litter this area."},
            { "GiantStronghold3", "This area smells of fur."},
            { "GiantStronghold4", "You think you hear lumbering steps."},
            { "GiantStronghold5", "Some giant used this area as a latrine."},
            { "GiantStronghold6", "Your movement has stirred up some fallen giant hair."},
            { "GiantStronghold7", "The ground shakes momentarily."},
            { "GiantStronghold8", "The ground shakes as something lumbers about."},

            // Dungeon: DragonsDen
            { "DragonsDen0", "You see wilted dragon scales."},
            { "DragonsDen1", "The floor here has been hardened by heat."},
            { "DragonsDen2", "There are scratches on the walls"},
            { "DragonsDen3", "A symbol of Akatosh is drawn in blood"},
            { "DragonsDen4", "You are reminded of Akavir"},
            { "DragonsDen7", "You smell smoke"},
            { "DragonsDen8", "A beetle scampers over your foot."},

            // Dungeon: BarbarianStronghold
            { "BarbarianStronghold0", "You hear the distant shot of an arrow."},
            { "BarbarianStronghold1", "Something rustles about."},
            { "BarbarianStronghold2", "You see unfamiliar markings scratched here."},
            { "BarbarianStronghold3", "Something flees from you."},
            { "BarbarianStronghold4", "The smell of death fills the air."},
            { "BarbarianStronghold5", "You smell burnt wood."},
            { "BarbarianStronghold6", "You vaguely smell ale."},
            { "BarbarianStronghold7", "Things are deathly quiet here."},
            { "BarbarianStronghold8", "A crude sigil is drawn here."},
            { "BarbarianStronghold9", "You could swear you hear whispers."},

            // Dungeon: VolcanicCaves
            { "VolcanicCaves0", "You feel some vents of steam under the ground."},
            { "VolcanicCaves1", "The air is moving quickly here."},
            { "VolcanicCaves2", "A warm draft blows by."},
            { "VolcanicCaves3", "The earth rumbles softly."},
            { "VolcanicCaves5", "You smell a whiff of sulfur."},
            { "VolcanicCaves6", "This area smells of charcoal."},
            { "VolcanicCaves7", "A summoning sigil was drawn and erased here."},
            { "VolcanicCaves8", "The air suddenly grows still."},
            { "VolcanicCaves9", "You smell something burning."},

            // Dungeon: ScorpionNest
            { "ScorpionNest0", "Tiny bits of animal corpses litter this area."},
            { "ScorpionNest1", "You see the remains of molted skin."},
            { "ScorpionNest2", "Flies buzz near you."},
            { "ScorpionNest5", "A small rat scampers away."},
            { "ScorpionNest6", "A tiny scorpion crawls out from your possessions."},
            { "ScorpionNest7", "The air is still here."},
            { "ScorpionNest9", "The insects near you dissipate."},

            // Dungeon: Cemetery
            { "Cemetery0", "A beetle creeps over your foot."},
            { "Cemetery1", "Did the ground just move?"},
            { "Cemetery2", "You smell decomposing bodies."},
            { "Cemetery3", "The air is tense here."},
            { "Cemetery4", "You sense something staring at you."},
            { "Cemetery5", "Faint whispers fill the air."},
            { "Cemetery6", "You feel unwelcome here."},
            { "Cemetery7", "You feel the gaze of the dead upon you."},
            { "Cemetery8", "Someone attempted to dig the ground here."},

            #endregion
        };

    }
}